package net

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIProxyPortListener = "com.android.net.IProxyPortListener"

const (
	TransactionIProxyPortListenerSetProxyPort = binder.FirstCallTransaction + 0
)

type IProxyPortListener interface {
	AsBinder() binder.IBinder
	SetProxyPort(ctx context.Context, port int32) error
}

type ProxyPortListenerProxy struct {
	remote binder.IBinder
}

func NewProxyPortListenerProxy(
	remote binder.IBinder,
) *ProxyPortListenerProxy {
	return &ProxyPortListenerProxy{remote: remote}
}

func (p *ProxyPortListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IProxyPortListener = (*ProxyPortListenerProxy)(nil)

func (p *ProxyPortListenerProxy) SetProxyPort(
	ctx context.Context,
	port int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIProxyPortListener)
	_data.WriteInt32(port)

	_code, _err := p.remote.ResolveCode(DescriptorIProxyPortListener, "setProxyPort")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ProxyPortListenerStub dispatches incoming binder transactions
// to a typed IProxyPortListener implementation.
type ProxyPortListenerStub struct {
	Impl IProxyPortListener
}

var _ binder.TransactionReceiver = (*ProxyPortListenerStub)(nil)

func (s *ProxyPortListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIProxyPortListenerSetProxyPort:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_port, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetProxyPort(ctx, _arg_port)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
