package memtrack

// Code generated by aidlgen. DO NOT EDIT.

type MemtrackType int32

const (
	MemtrackTypeOTHER      MemtrackType = 0
	MemtrackTypeGL         MemtrackType = 1
	MemtrackTypeGRAPHICS   MemtrackType = 2
	MemtrackTypeMULTIMEDIA MemtrackType = 3
	MemtrackTypeCAMERA     MemtrackType = 4
)
