package interactive

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITvInteractiveAppServiceCallback = "android.media.tv.interactive.ITvInteractiveAppServiceCallback"

const (
	TransactionITvInteractiveAppServiceCallbackOnStateChanged = binder.FirstCallTransaction + 0
)

type ITvInteractiveAppServiceCallback interface {
	AsBinder() binder.IBinder
	OnStateChanged(ctx context.Context, type_ int32, state int32, error_ int32) error
}

type TvInteractiveAppServiceCallbackProxy struct {
	remote binder.IBinder
}

func NewTvInteractiveAppServiceCallbackProxy(
	remote binder.IBinder,
) *TvInteractiveAppServiceCallbackProxy {
	return &TvInteractiveAppServiceCallbackProxy{remote: remote}
}

func (p *TvInteractiveAppServiceCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITvInteractiveAppServiceCallback = (*TvInteractiveAppServiceCallbackProxy)(nil)

func (p *TvInteractiveAppServiceCallbackProxy) OnStateChanged(
	ctx context.Context,
	type_ int32,
	state int32,
	error_ int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInteractiveAppServiceCallback)
	_data.WriteInt32(type_)
	_data.WriteInt32(state)
	_data.WriteInt32(error_)

	_code, _err := p.remote.ResolveCode(DescriptorITvInteractiveAppServiceCallback, "onStateChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// TvInteractiveAppServiceCallbackStub dispatches incoming binder transactions
// to a typed ITvInteractiveAppServiceCallback implementation.
type TvInteractiveAppServiceCallbackStub struct {
	Impl ITvInteractiveAppServiceCallback
}

var _ binder.TransactionReceiver = (*TvInteractiveAppServiceCallbackStub)(nil)

func (s *TvInteractiveAppServiceCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionITvInteractiveAppServiceCallbackOnStateChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_type_, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_state, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_error_, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnStateChanged(ctx, _arg_type_, _arg_state, _arg_error_)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
