// Code generated by genparcelgo. DO NOT EDIT.

package keymaster

import (
	"github.com/xaionaro-go/binder/parcel"
)

type ExportResult struct {
	ResultCode int32
	// ExportData: opaque type — not yet supported
}

var _ parcel.Parcelable = (*ExportResult)(nil)

func (s *ExportResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.ResultCode)
	return nil
}

func (s *ExportResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.ResultCode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
