// Code generated by genparcelgo. DO NOT EDIT.

package telephony

import (
	"github.com/xaionaro-go/binder/parcel"
)

type CellInfoWcdma struct {
	// Dest: opaque type — not yet supported
	// Dest: opaque type — not yet supported
	// Dest: opaque type — not yet supported
}

var _ parcel.Parcelable = (*CellInfoWcdma)(nil)

func (s *CellInfoWcdma) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *CellInfoWcdma) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
