// Code generated by genparcelgo. DO NOT EDIT.

package media

import (
	"github.com/xaionaro-go/binder/parcel"
)

type AudioPresentation struct {
	// GetPresentationId(): opaque type — not yet supported
	// GetProgramId(): opaque type — not yet supported
	// GetULocale(): opaque type — not yet supported
	// GetMasteringIndication(): opaque type — not yet supported
	// HasAudioDescription(): opaque type — not yet supported
	// HasSpokenSubtitles(): opaque type — not yet supported
	// HasDialogueEnhancement(): opaque type — not yet supported
	// Labels: opaque type — not yet supported
}

var _ parcel.Parcelable = (*AudioPresentation)(nil)

func (s *AudioPresentation) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *AudioPresentation) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
