package media

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorICommunicationDeviceDispatcher = "android.media.ICommunicationDeviceDispatcher"

const (
	TransactionICommunicationDeviceDispatcherDispatchCommunicationDeviceChanged = binder.FirstCallTransaction + 0
)

type ICommunicationDeviceDispatcher interface {
	AsBinder() binder.IBinder
	DispatchCommunicationDeviceChanged(ctx context.Context, portId int32) error
}

type CommunicationDeviceDispatcherProxy struct {
	remote binder.IBinder
}

func NewCommunicationDeviceDispatcherProxy(
	remote binder.IBinder,
) *CommunicationDeviceDispatcherProxy {
	return &CommunicationDeviceDispatcherProxy{remote: remote}
}

func (p *CommunicationDeviceDispatcherProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ICommunicationDeviceDispatcher = (*CommunicationDeviceDispatcherProxy)(nil)

func (p *CommunicationDeviceDispatcherProxy) DispatchCommunicationDeviceChanged(
	ctx context.Context,
	portId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICommunicationDeviceDispatcher)
	_data.WriteInt32(portId)

	_, _err := p.remote.Transact(ctx, TransactionICommunicationDeviceDispatcherDispatchCommunicationDeviceChanged, binder.FlagOneway, _data)
	return _err
}
