// Code generated by genparcelgo. DO NOT EDIT.

package media

import (
	"github.com/xaionaro-go/binder/parcel"
)

type MediaSyncEvent struct {
	Type         int32
	AudioSession int32
}

var _ parcel.Parcelable = (*MediaSyncEvent)(nil)

func (s *MediaSyncEvent) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Type)
	p.WriteInt32(s.AudioSession)
	return nil
}

func (s *MediaSyncEvent) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Type, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.AudioSession, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
