package cam

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorICamHostControlTuneQuietlyFlag = "android.media.tv.extension.cam.ICamHostControlTuneQuietlyFlag"

const (
	TransactionICamHostControlTuneQuietlyFlagAddHcTuneQuietlyFlagListener    = binder.FirstCallTransaction + 0
	TransactionICamHostControlTuneQuietlyFlagRemoveHcTuneQuietlyFlagListener = binder.FirstCallTransaction + 1
	TransactionICamHostControlTuneQuietlyFlagGetHcTuneQuietlyFlag            = binder.FirstCallTransaction + 2
)

type ICamHostControlTuneQuietlyFlag interface {
	AsBinder() binder.IBinder
	AddHcTuneQuietlyFlagListener(ctx context.Context, listener ICamHostControlTuneQuietlyFlagListener) error
	RemoveHcTuneQuietlyFlagListener(ctx context.Context, listener ICamHostControlTuneQuietlyFlagListener) error
	GetHcTuneQuietlyFlag(ctx context.Context, sessionToken string) (os.Bundle, error)
}

type CamHostControlTuneQuietlyFlagProxy struct {
	remote binder.IBinder
}

func NewCamHostControlTuneQuietlyFlagProxy(
	remote binder.IBinder,
) *CamHostControlTuneQuietlyFlagProxy {
	return &CamHostControlTuneQuietlyFlagProxy{remote: remote}
}

func (p *CamHostControlTuneQuietlyFlagProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ICamHostControlTuneQuietlyFlag = (*CamHostControlTuneQuietlyFlagProxy)(nil)

func (p *CamHostControlTuneQuietlyFlagProxy) AddHcTuneQuietlyFlagListener(
	ctx context.Context,
	listener ICamHostControlTuneQuietlyFlagListener,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICamHostControlTuneQuietlyFlag)
	_data.WriteStrongBinder(listener.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorICamHostControlTuneQuietlyFlag, "addHcTuneQuietlyFlagListener")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *CamHostControlTuneQuietlyFlagProxy) RemoveHcTuneQuietlyFlagListener(
	ctx context.Context,
	listener ICamHostControlTuneQuietlyFlagListener,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICamHostControlTuneQuietlyFlag)
	_data.WriteStrongBinder(listener.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorICamHostControlTuneQuietlyFlag, "removeHcTuneQuietlyFlagListener")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *CamHostControlTuneQuietlyFlagProxy) GetHcTuneQuietlyFlag(
	ctx context.Context,
	sessionToken string,
) (os.Bundle, error) {
	var _result os.Bundle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICamHostControlTuneQuietlyFlag)
	_data.WriteString16(sessionToken)

	_code, _err := p.remote.ResolveCode(DescriptorICamHostControlTuneQuietlyFlag, "getHcTuneQuietlyFlag")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

// CamHostControlTuneQuietlyFlagStub dispatches incoming binder transactions
// to a typed ICamHostControlTuneQuietlyFlag implementation.
type CamHostControlTuneQuietlyFlagStub struct {
	Impl ICamHostControlTuneQuietlyFlag
}

var _ binder.TransactionReceiver = (*CamHostControlTuneQuietlyFlagStub)(nil)

func (s *CamHostControlTuneQuietlyFlagStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionICamHostControlTuneQuietlyFlagAddHcTuneQuietlyFlagListener:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_listener ICamHostControlTuneQuietlyFlagListener
		_ = _arg_listener
		_err := s.Impl.AddHcTuneQuietlyFlagListener(ctx, _arg_listener)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionICamHostControlTuneQuietlyFlagRemoveHcTuneQuietlyFlagListener:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_listener ICamHostControlTuneQuietlyFlagListener
		_ = _arg_listener
		_err := s.Impl.RemoveHcTuneQuietlyFlagListener(ctx, _arg_listener)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionICamHostControlTuneQuietlyFlagGetHcTuneQuietlyFlag:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_sessionToken, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetHcTuneQuietlyFlag(ctx, _arg_sessionToken)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
