package statusbar

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type RegisterStatusBarResult struct {
	DisabledFlags1          int32
	Appearance              int32
	ImeWindowVis            int32
	ImeBackDisposition      int32
	ShowImeSwitcher         bool
	DisabledFlags2          int32
	NavbarColorManagedByIme bool
	Behavior                int32
	RequestedVisibleTypes   int32
	PackageName             string
	TransientBarTypes       int32
}

var _ parcel.Parcelable = (*RegisterStatusBarResult)(nil)

func (s *RegisterStatusBarResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.DisabledFlags1)
	p.WriteInt32(s.Appearance)
	p.WriteInt32(s.ImeWindowVis)
	p.WriteInt32(s.ImeBackDisposition)
	p.WriteBool(s.ShowImeSwitcher)
	p.WriteInt32(s.DisabledFlags2)
	p.WriteBool(s.NavbarColorManagedByIme)
	p.WriteInt32(s.Behavior)
	p.WriteInt32(s.RequestedVisibleTypes)
	p.WriteString16(s.PackageName)
	p.WriteInt32(s.TransientBarTypes)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *RegisterStatusBarResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.DisabledFlags1, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Appearance, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ImeWindowVis, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ImeBackDisposition, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ShowImeSwitcher, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.DisabledFlags2, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.NavbarColorManagedByIme, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Behavior, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.RequestedVisibleTypes, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.TransientBarTypes, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
