package input

// Code generated by aidlgen. DO NOT EDIT.

type CableConnectionStatus int32

const (
	CableConnectionStatusUNKNOWN      CableConnectionStatus = 0
	CableConnectionStatusCONNECTED    CableConnectionStatus = 1
	CableConnectionStatusDISCONNECTED CableConnectionStatus = 2
)
