package util

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorICommandReceiver = "com.android.frameworks.perftests.am.util.ICommandReceiver"

const (
	TransactionICommandReceiverSendCommand = binder.FirstCallTransaction + 0
)

type ICommandReceiver interface {
	AsBinder() binder.IBinder
	SendCommand(ctx context.Context, command int32, seq int32, sourcePackage string, targetPackage string, flags int32, bundle os.Bundle) error
}

type CommandReceiverProxy struct {
	remote binder.IBinder
}

func NewCommandReceiverProxy(
	remote binder.IBinder,
) *CommandReceiverProxy {
	return &CommandReceiverProxy{remote: remote}
}

func (p *CommandReceiverProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ICommandReceiver = (*CommandReceiverProxy)(nil)

func (p *CommandReceiverProxy) SendCommand(
	ctx context.Context,
	command int32,
	seq int32,
	sourcePackage string,
	targetPackage string,
	flags int32,
	bundle os.Bundle,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICommandReceiver)
	_data.WriteInt32(command)
	_data.WriteInt32(seq)
	_data.WriteString16(sourcePackage)
	_data.WriteString16(targetPackage)
	_data.WriteInt32(flags)
	_data.WriteInt32(1)
	if _err := bundle.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorICommandReceiver, "sendCommand")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// CommandReceiverStub dispatches incoming binder transactions
// to a typed ICommandReceiver implementation.
type CommandReceiverStub struct {
	Impl ICommandReceiver
}

var _ binder.TransactionReceiver = (*CommandReceiverStub)(nil)

func (s *CommandReceiverStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionICommandReceiverSendCommand:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_command, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_sourcePackage, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_targetPackage, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_bundle os.Bundle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_bundle.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SendCommand(ctx, _arg_command, _arg_seq, _arg_sourcePackage, _arg_targetPackage, _arg_flags, _arg_bundle)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
