package euicc

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GetDefaultDownloadableSubscriptionListResult struct {
	Result int32
}

var _ parcel.Parcelable = (*GetDefaultDownloadableSubscriptionListResult)(nil)

func (s *GetDefaultDownloadableSubscriptionListResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Result)
	p.WriteInt32(-1) // null Subscriptions
	return nil
}

func (s *GetDefaultDownloadableSubscriptionListResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Result, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_arrLen, _arrErr := p.ReadInt32()
		if _arrErr != nil {
			return _arrErr
		}
		if _arrLen > 0 {
			return nil // non-empty typed_array Subscriptions: cannot skip
		}
	}
	return nil
}
