package common

// Code generated by aidlgen. DO NOT EDIT.

type WakeReason int32

const (
	WakeReasonUNKNOWN           WakeReason = 0
	WakeReasonPowerButton       WakeReason = 1
	WakeReasonGESTURE           WakeReason = 2
	WakeReasonWakeKey           WakeReason = 3
	WakeReasonWakeMotion        WakeReason = 4
	WakeReasonLID               WakeReason = 5
	WakeReasonDisplayGroupAdded WakeReason = 6
	WakeReasonTAP               WakeReason = 7
	WakeReasonLIFT              WakeReason = 8
	WakeReasonBIOMETRIC         WakeReason = 9
)
