package window

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TaskFragmentTransaction struct {
}

var _ parcel.Parcelable = (*TaskFragmentTransaction)(nil)

func (s *TaskFragmentTransaction) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteNullStrongBinder() // null TransactionToken
	p.WriteInt32(-1)          // null Changes
	return nil
}

func (s *TaskFragmentTransaction) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	if _, _, _binderErr := p.ReadNullableStrongBinder(); _binderErr != nil {
		return _binderErr
	}
	return nil // opaque Changes: cannot skip without known wire format
}
