package window

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TaskSnapshot struct {
	Id              int64
	Orientation     int32
	Rotation        int32
	IsLowResolution bool
	IsRealSnapshot  bool
	WindowingMode   int32
	Appearance      int32
	IsTranslucent   bool
	HasImeSurface   bool
}

var _ parcel.Parcelable = (*TaskSnapshot)(nil)

func (s *TaskSnapshot) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt64(s.Id)
	p.WriteInt32(-1) // null TopActivityComponent
	p.WriteInt32(-1) // null Snapshot!=null&&!mSnapshot.isClosed()?mSnapshot:null
	p.WriteInt32(-1) // null ColorSpace.getId()
	p.WriteInt32(s.Orientation)
	p.WriteInt32(s.Rotation)
	p.WriteInt32(-1) // null TaskSize
	p.WriteInt32(-1) // null ContentInsets
	p.WriteInt32(-1) // null LetterboxInsets
	p.WriteBool(s.IsLowResolution)
	p.WriteBool(s.IsRealSnapshot)
	p.WriteInt32(s.WindowingMode)
	p.WriteInt32(s.Appearance)
	p.WriteBool(s.IsTranslucent)
	p.WriteBool(s.HasImeSurface)
	return nil
}

func (s *TaskSnapshot) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Id, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.Orientation, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Rotation, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.IsLowResolution, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.IsRealSnapshot, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.WindowingMode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Appearance, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.IsTranslucent, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.HasImeSurface, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	return nil
}
