package admin

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorStartInstallingUpdateCallback = "android.app.admin.StartInstallingUpdateCallback"

const (
	TransactionStartInstallingUpdateCallbackOnStartInstallingUpdateError = binder.FirstCallTransaction + 0
)

type StartInstallingUpdateCallback interface {
	AsBinder() binder.IBinder
	OnStartInstallingUpdateError(ctx context.Context, errorCode int32, errorMessage string) error
}

type StartInstallingUpdateCallbackProxy struct {
	remote binder.IBinder
}

func NewStartInstallingUpdateCallbackProxy(
	remote binder.IBinder,
) *StartInstallingUpdateCallbackProxy {
	return &StartInstallingUpdateCallbackProxy{remote: remote}
}

func (p *StartInstallingUpdateCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ StartInstallingUpdateCallback = (*StartInstallingUpdateCallbackProxy)(nil)

func (p *StartInstallingUpdateCallbackProxy) OnStartInstallingUpdateError(
	ctx context.Context,
	errorCode int32,
	errorMessage string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorStartInstallingUpdateCallback)
	_data.WriteInt32(errorCode)
	_data.WriteString16(errorMessage)

	_code, _err := p.remote.ResolveCode(DescriptorStartInstallingUpdateCallback, "onStartInstallingUpdateError")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// StartInstallingUpdateCallbackStub dispatches incoming binder transactions
// to a typed StartInstallingUpdateCallback implementation.
type StartInstallingUpdateCallbackStub struct {
	Impl StartInstallingUpdateCallback
}

var _ binder.TransactionReceiver = (*StartInstallingUpdateCallbackStub)(nil)

func (s *StartInstallingUpdateCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionStartInstallingUpdateCallbackOnStartInstallingUpdateError:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_errorCode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_errorMessage, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnStartInstallingUpdateError(ctx, _arg_errorCode, _arg_errorMessage)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
