// Code generated by genparcelgo. DO NOT EDIT.

package admin

import (
	"github.com/xaionaro-go/binder/parcel"
)

type SystemUpdateInfo struct {
	// GetReceivedTime(): opaque type — not yet supported
	// GetSecurityPatchState(): opaque type — not yet supported
}

var _ parcel.Parcelable = (*SystemUpdateInfo)(nil)

func (s *SystemUpdateInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *SystemUpdateInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
