package telecom

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type CallEndpoint struct {
	Type int32
}

var _ parcel.Parcelable = (*CallEndpoint)(nil)

func (s *CallEndpoint) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null Name
	p.WriteInt32(s.Type)
	p.WriteInt32(-1) // null Identifier
	return nil
}

func (s *CallEndpoint) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	return nil // opaque Name: cannot skip without known wire format
	s.Type, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil // opaque Identifier: cannot skip without known wire format
	return nil
}
