package telecom

import (
	content "github.com/AndroidGoLab/binder/android/content"
	os "github.com/AndroidGoLab/binder/android/os"
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PhoneAccountHandle struct {
	Id            string
	ComponentName content.ComponentName
	UserHandle    os.UserHandle
}

var _ parcel.Parcelable = (*PhoneAccountHandle)(nil)

func (s *PhoneAccountHandle) MarshalParcel(
	p *parcel.Parcel,
) error {
	if _err := s.ComponentName.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteString16(s.Id)
	if _err := s.UserHandle.MarshalParcel(p); _err != nil {
		return _err
	}
	return nil
}

func (s *PhoneAccountHandle) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	if _err := s.ComponentName.UnmarshalParcel(p); _err != nil {
		return _err
	}
	s.Id, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	if _err := s.UserHandle.UnmarshalParcel(p); _err != nil {
		return _err
	}
	return nil
}
