package le

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type ResultStorageDescriptor struct {
	Type   int32
	Offset int32
	Length int32
}

var _ parcel.Parcelable = (*ResultStorageDescriptor)(nil)

func (s *ResultStorageDescriptor) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Type)
	p.WriteInt32(s.Offset)
	p.WriteInt32(s.Length)
	return nil
}

func (s *ResultStorageDescriptor) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Type, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Offset, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Length, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
