package autofill

import (
	"context"
	"fmt"
	graphics "github.com/xaionaro-go/binder/android/graphics"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAutofillWindowPresenter = "android.view.autofill.IAutofillWindowPresenter"

const (
	TransactionIAutofillWindowPresenterShow = binder.FirstCallTransaction + 0
	TransactionIAutofillWindowPresenterHide = binder.FirstCallTransaction + 1
)

type IAutofillWindowPresenter interface {
	AsBinder() binder.IBinder
	Show(ctx context.Context, p_ interface{}, transitionEpicenter graphics.Rect, fitsSystemWindows bool, layoutDirection int32) error
	Hide(ctx context.Context, transitionEpicenter graphics.Rect) error
}

type AutofillWindowPresenterProxy struct {
	remote binder.IBinder
}

func NewAutofillWindowPresenterProxy(
	remote binder.IBinder,
) *AutofillWindowPresenterProxy {
	return &AutofillWindowPresenterProxy{remote: remote}
}

func (p *AutofillWindowPresenterProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAutofillWindowPresenter = (*AutofillWindowPresenterProxy)(nil)

func (p *AutofillWindowPresenterProxy) Show(
	ctx context.Context,
	p_ interface{},
	transitionEpicenter graphics.Rect,
	fitsSystemWindows bool,
	layoutDirection int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAutofillWindowPresenter)
	_data.WriteInt32(1)
	if _err := transitionEpicenter.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(fitsSystemWindows)
	_data.WriteInt32(layoutDirection)

	_code, _err := p.remote.ResolveCode(DescriptorIAutofillWindowPresenter, "show")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AutofillWindowPresenterProxy) Hide(
	ctx context.Context,
	transitionEpicenter graphics.Rect,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAutofillWindowPresenter)
	_data.WriteInt32(1)
	if _err := transitionEpicenter.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIAutofillWindowPresenter, "hide")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// AutofillWindowPresenterStub dispatches incoming binder transactions
// to a typed IAutofillWindowPresenter implementation.
type AutofillWindowPresenterStub struct {
	Impl IAutofillWindowPresenter
}

var _ binder.TransactionReceiver = (*AutofillWindowPresenterStub)(nil)

func (s *AutofillWindowPresenterStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIAutofillWindowPresenterShow:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_p_ interface{}
		var _arg_transitionEpicenter graphics.Rect
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_transitionEpicenter.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_fitsSystemWindows, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_layoutDirection, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.Show(ctx, _arg_p_, _arg_transitionEpicenter, _arg_fitsSystemWindows, _arg_layoutDirection)
		_ = _err
		return nil, nil
	case TransactionIAutofillWindowPresenterHide:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_transitionEpicenter graphics.Rect
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_transitionEpicenter.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.Hide(ctx, _arg_transitionEpicenter)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
