package messaging

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIRadioMessaging = "android.hardware.radio.messaging.IRadioMessaging"

const (
	TransactionIRadioMessagingAcknowledgeIncomingGsmSmsWithPdu = binder.FirstCallTransaction + 0
	TransactionIRadioMessagingAcknowledgeLastIncomingCdmaSms   = binder.FirstCallTransaction + 1
	TransactionIRadioMessagingAcknowledgeLastIncomingGsmSms    = binder.FirstCallTransaction + 2
	TransactionIRadioMessagingDeleteSmsOnRuim                  = binder.FirstCallTransaction + 3
	TransactionIRadioMessagingDeleteSmsOnSim                   = binder.FirstCallTransaction + 4
	TransactionIRadioMessagingGetCdmaBroadcastConfig           = binder.FirstCallTransaction + 5
	TransactionIRadioMessagingGetGsmBroadcastConfig            = binder.FirstCallTransaction + 6
	TransactionIRadioMessagingGetSmscAddress                   = binder.FirstCallTransaction + 7
	TransactionIRadioMessagingReportSmsMemoryStatus            = binder.FirstCallTransaction + 8
	TransactionIRadioMessagingResponseAcknowledgement          = binder.FirstCallTransaction + 9
	TransactionIRadioMessagingSendCdmaSms                      = binder.FirstCallTransaction + 10
	TransactionIRadioMessagingSendCdmaSmsExpectMore            = binder.FirstCallTransaction + 11
	TransactionIRadioMessagingSendImsSms                       = binder.FirstCallTransaction + 12
	TransactionIRadioMessagingSendSms                          = binder.FirstCallTransaction + 13
	TransactionIRadioMessagingSendSmsExpectMore                = binder.FirstCallTransaction + 14
	TransactionIRadioMessagingSetCdmaBroadcastActivation       = binder.FirstCallTransaction + 15
	TransactionIRadioMessagingSetCdmaBroadcastConfig           = binder.FirstCallTransaction + 16
	TransactionIRadioMessagingSetGsmBroadcastActivation        = binder.FirstCallTransaction + 17
	TransactionIRadioMessagingSetGsmBroadcastConfig            = binder.FirstCallTransaction + 18
	TransactionIRadioMessagingSetResponseFunctions             = binder.FirstCallTransaction + 19
	TransactionIRadioMessagingSetSmscAddress                   = binder.FirstCallTransaction + 20
	TransactionIRadioMessagingWriteSmsToRuim                   = binder.FirstCallTransaction + 21
	TransactionIRadioMessagingWriteSmsToSim                    = binder.FirstCallTransaction + 22
)

type IRadioMessaging interface {
	AsBinder() binder.IBinder
	AcknowledgeIncomingGsmSmsWithPdu(ctx context.Context, serial int32, success bool, ackPdu string) error
	AcknowledgeLastIncomingCdmaSms(ctx context.Context, serial int32, smsAck CdmaSmsAck) error
	AcknowledgeLastIncomingGsmSms(ctx context.Context, serial int32, success bool, cause SmsAcknowledgeFailCause) error
	DeleteSmsOnRuim(ctx context.Context, serial int32, index int32) error
	DeleteSmsOnSim(ctx context.Context, serial int32, index int32) error
	GetCdmaBroadcastConfig(ctx context.Context, serial int32) error
	GetGsmBroadcastConfig(ctx context.Context, serial int32) error
	GetSmscAddress(ctx context.Context, serial int32) error
	ReportSmsMemoryStatus(ctx context.Context, serial int32, available bool) error
	ResponseAcknowledgement(ctx context.Context) error
	SendCdmaSms(ctx context.Context, serial int32, sms CdmaSmsMessage) error
	SendCdmaSmsExpectMore(ctx context.Context, serial int32, sms CdmaSmsMessage) error
	SendImsSms(ctx context.Context, serial int32, message ImsSmsMessage) error
	SendSms(ctx context.Context, serial int32, message GsmSmsMessage) error
	SendSmsExpectMore(ctx context.Context, serial int32, message GsmSmsMessage) error
	SetCdmaBroadcastActivation(ctx context.Context, serial int32, activate bool) error
	SetCdmaBroadcastConfig(ctx context.Context, serial int32, configInfo []CdmaBroadcastSmsConfigInfo) error
	SetGsmBroadcastActivation(ctx context.Context, serial int32, activate bool) error
	SetGsmBroadcastConfig(ctx context.Context, serial int32, configInfo []GsmBroadcastSmsConfigInfo) error
	SetResponseFunctions(ctx context.Context, radioMessagingResponse IRadioMessagingResponse, radioMessagingIndication IRadioMessagingIndication) error
	SetSmscAddress(ctx context.Context, serial int32, smsc string) error
	WriteSmsToRuim(ctx context.Context, serial int32, cdmaSms CdmaSmsWriteArgs) error
	WriteSmsToSim(ctx context.Context, serial int32, smsWriteArgs SmsWriteArgs) error
}

type RadioMessagingProxy struct {
	remote binder.IBinder
}

func NewRadioMessagingProxy(
	remote binder.IBinder,
) *RadioMessagingProxy {
	return &RadioMessagingProxy{remote: remote}
}

func (p *RadioMessagingProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IRadioMessaging = (*RadioMessagingProxy)(nil)

func (p *RadioMessagingProxy) AcknowledgeIncomingGsmSmsWithPdu(
	ctx context.Context,
	serial int32,
	success bool,
	ackPdu string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteBool(success)
	_data.WriteString16(ackPdu)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingAcknowledgeIncomingGsmSmsWithPdu, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) AcknowledgeLastIncomingCdmaSms(
	ctx context.Context,
	serial int32,
	smsAck CdmaSmsAck,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := smsAck.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingAcknowledgeLastIncomingCdmaSms, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) AcknowledgeLastIncomingGsmSms(
	ctx context.Context,
	serial int32,
	success bool,
	cause SmsAcknowledgeFailCause,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteBool(success)
	_data.WriteInt32(int32(cause))

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingAcknowledgeLastIncomingGsmSms, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) DeleteSmsOnRuim(
	ctx context.Context,
	serial int32,
	index int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteInt32(index)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingDeleteSmsOnRuim, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) DeleteSmsOnSim(
	ctx context.Context,
	serial int32,
	index int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteInt32(index)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingDeleteSmsOnSim, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) GetCdmaBroadcastConfig(
	ctx context.Context,
	serial int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingGetCdmaBroadcastConfig, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) GetGsmBroadcastConfig(
	ctx context.Context,
	serial int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingGetGsmBroadcastConfig, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) GetSmscAddress(
	ctx context.Context,
	serial int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingGetSmscAddress, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) ReportSmsMemoryStatus(
	ctx context.Context,
	serial int32,
	available bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteBool(available)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingReportSmsMemoryStatus, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) ResponseAcknowledgement(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingResponseAcknowledgement, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SendCdmaSms(
	ctx context.Context,
	serial int32,
	sms CdmaSmsMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := sms.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSendCdmaSms, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SendCdmaSmsExpectMore(
	ctx context.Context,
	serial int32,
	sms CdmaSmsMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := sms.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSendCdmaSmsExpectMore, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SendImsSms(
	ctx context.Context,
	serial int32,
	message ImsSmsMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := message.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSendImsSms, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SendSms(
	ctx context.Context,
	serial int32,
	message GsmSmsMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := message.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSendSms, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SendSmsExpectMore(
	ctx context.Context,
	serial int32,
	message GsmSmsMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := message.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSendSmsExpectMore, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetCdmaBroadcastActivation(
	ctx context.Context,
	serial int32,
	activate bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteBool(activate)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetCdmaBroadcastActivation, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetCdmaBroadcastConfig(
	ctx context.Context,
	serial int32,
	configInfo []CdmaBroadcastSmsConfigInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if configInfo == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(configInfo)))
		for _, _item := range configInfo {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetCdmaBroadcastConfig, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetGsmBroadcastActivation(
	ctx context.Context,
	serial int32,
	activate bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteBool(activate)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetGsmBroadcastActivation, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetGsmBroadcastConfig(
	ctx context.Context,
	serial int32,
	configInfo []GsmBroadcastSmsConfigInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if configInfo == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(configInfo)))
		for _, _item := range configInfo {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetGsmBroadcastConfig, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetResponseFunctions(
	ctx context.Context,
	radioMessagingResponse IRadioMessagingResponse,
	radioMessagingIndication IRadioMessagingIndication,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteStrongBinder(radioMessagingResponse.AsBinder().Handle())
	_data.WriteStrongBinder(radioMessagingIndication.AsBinder().Handle())

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetResponseFunctions, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) SetSmscAddress(
	ctx context.Context,
	serial int32,
	smsc string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	_data.WriteString16(smsc)

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingSetSmscAddress, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) WriteSmsToRuim(
	ctx context.Context,
	serial int32,
	cdmaSms CdmaSmsWriteArgs,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := cdmaSms.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingWriteSmsToRuim, binder.FlagOneway, _data)
	return _err
}

func (p *RadioMessagingProxy) WriteSmsToSim(
	ctx context.Context,
	serial int32,
	smsWriteArgs SmsWriteArgs,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioMessaging)
	_data.WriteInt32(serial)
	if _err := smsWriteArgs.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioMessagingWriteSmsToSim, binder.FlagOneway, _data)
	return _err
}
