package tts

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITextToSpeechSessionCallback = "android.speech.tts.ITextToSpeechSessionCallback"

const (
	TransactionITextToSpeechSessionCallbackOnConnected    = binder.FirstCallTransaction + 0
	TransactionITextToSpeechSessionCallbackOnDisconnected = binder.FirstCallTransaction + 1
	TransactionITextToSpeechSessionCallbackOnError        = binder.FirstCallTransaction + 2
)

type ITextToSpeechSessionCallback interface {
	AsBinder() binder.IBinder
	OnConnected(ctx context.Context, session ITextToSpeechSession, serviceBinder binder.IBinder) error
	OnDisconnected(ctx context.Context) error
	OnError(ctx context.Context, errorInfo string) error
}

type TextToSpeechSessionCallbackProxy struct {
	remote binder.IBinder
}

func NewTextToSpeechSessionCallbackProxy(
	remote binder.IBinder,
) *TextToSpeechSessionCallbackProxy {
	return &TextToSpeechSessionCallbackProxy{remote: remote}
}

func (p *TextToSpeechSessionCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITextToSpeechSessionCallback = (*TextToSpeechSessionCallbackProxy)(nil)

func (p *TextToSpeechSessionCallbackProxy) OnConnected(
	ctx context.Context,
	session ITextToSpeechSession,
	serviceBinder binder.IBinder,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITextToSpeechSessionCallback)
	_data.WriteStrongBinder(session.AsBinder().Handle())
	_data.WriteStrongBinder(serviceBinder.Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITextToSpeechSessionCallback, "onConnected")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TextToSpeechSessionCallbackProxy) OnDisconnected(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITextToSpeechSessionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITextToSpeechSessionCallback, "onDisconnected")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TextToSpeechSessionCallbackProxy) OnError(
	ctx context.Context,
	errorInfo string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITextToSpeechSessionCallback)
	_data.WriteString16(errorInfo)

	_code, _err := p.remote.ResolveCode(DescriptorITextToSpeechSessionCallback, "onError")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// TextToSpeechSessionCallbackStub dispatches incoming binder transactions
// to a typed ITextToSpeechSessionCallback implementation.
type TextToSpeechSessionCallbackStub struct {
	Impl ITextToSpeechSessionCallback
}

var _ binder.TransactionReceiver = (*TextToSpeechSessionCallbackStub)(nil)

func (s *TextToSpeechSessionCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionITextToSpeechSessionCallbackOnConnected:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_session ITextToSpeechSession
		_ = _arg_session
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_serviceBinder binder.IBinder
		_ = _arg_serviceBinder
		_err := s.Impl.OnConnected(ctx, _arg_session, _arg_serviceBinder)
		_ = _err
		return nil, nil
	case TransactionITextToSpeechSessionCallbackOnDisconnected:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnDisconnected(ctx)
		_ = _err
		return nil, nil
	case TransactionITextToSpeechSessionCallbackOnError:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_errorInfo, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnError(ctx, _arg_errorInfo)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
