package cardemulation

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type ApduServiceInfo struct {
	Description                 string
	OnHost                      bool
	OffHostName                 string
	StaticOffHostName           string
	RequiresDeviceUnlock        bool
	RequiresDeviceScreenOn      bool
	BannerResourceId            int32
	Uid                         int32
	SettingsActivityName        string
	CategoryOtherServiceEnabled bool
}

var _ parcel.Parcelable = (*ApduServiceInfo)(nil)

func (s *ApduServiceInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null Service
	p.WriteString16(s.Description)
	p.WriteBool(s.OnHost)
	p.WriteString16(s.OffHostName)
	p.WriteString16(s.StaticOffHostName)
	p.WriteInt32(0)  // placeholder StaticAidGroups.size()
	p.WriteInt32(-1) // null NewArrayList<AidGroup>(mStaticAidGroups.values())
	p.WriteInt32(0)  // placeholder DynamicAidGroups.size()
	p.WriteInt32(-1) // null NewArrayList<AidGroup>(mDynamicAidGroups.values())
	p.WriteBool(s.RequiresDeviceUnlock)
	p.WriteBool(s.RequiresDeviceScreenOn)
	p.WriteInt32(s.BannerResourceId)
	p.WriteInt32(s.Uid)
	p.WriteString16(s.SettingsActivityName)
	p.WriteBool(s.CategoryOtherServiceEnabled)
	p.WriteInt32(0)  // placeholder AutoTransact.size()
	p.WriteInt32(-1) // null AutoTransact
	return nil
}

func (s *ApduServiceInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	return nil // opaque Service: cannot skip without known wire format
	s.Description, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.OnHost, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.OffHostName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.StaticOffHostName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	if _, _err = p.ReadInt32(); _err != nil { // skip StaticAidGroups.size()
		return _err
	}
	return nil                                // opaque NewArrayList<AidGroup>(mStaticAidGroups.values()): cannot skip without known wire format
	if _, _err = p.ReadInt32(); _err != nil { // skip DynamicAidGroups.size()
		return _err
	}
	return nil // opaque NewArrayList<AidGroup>(mDynamicAidGroups.values()): cannot skip without known wire format
	s.RequiresDeviceUnlock, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.RequiresDeviceScreenOn, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.BannerResourceId, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Uid, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.SettingsActivityName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.CategoryOtherServiceEnabled, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	if _, _err = p.ReadInt32(); _err != nil { // skip AutoTransact.size()
		return _err
	}
	return nil // opaque AutoTransact: cannot skip without known wire format
	return nil
}
