package accessibilityservice

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBrailleDisplayConnection = "android.accessibilityservice.IBrailleDisplayConnection"

const (
	TransactionIBrailleDisplayConnectionDisconnect = binder.FirstCallTransaction + 0
	TransactionIBrailleDisplayConnectionWrite      = binder.FirstCallTransaction + 1
)

type IBrailleDisplayConnection interface {
	AsBinder() binder.IBinder
	Disconnect(ctx context.Context) error
	Write(ctx context.Context, output []byte) error
}

type BrailleDisplayConnectionProxy struct {
	remote binder.IBinder
}

func NewBrailleDisplayConnectionProxy(
	remote binder.IBinder,
) *BrailleDisplayConnectionProxy {
	return &BrailleDisplayConnectionProxy{remote: remote}
}

func (p *BrailleDisplayConnectionProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBrailleDisplayConnection = (*BrailleDisplayConnectionProxy)(nil)

func (p *BrailleDisplayConnectionProxy) Disconnect(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBrailleDisplayConnection)

	_code, _err := p.remote.ResolveCode(DescriptorIBrailleDisplayConnection, "disconnect")
	if _err != nil {
		_code = TransactionIBrailleDisplayConnectionDisconnect
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BrailleDisplayConnectionProxy) Write(
	ctx context.Context,
	output []byte,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBrailleDisplayConnection)
	if output == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(output)))
		for _, _item := range output {
			_data.WritePaddedByte(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBrailleDisplayConnection, "write")
	if _err != nil {
		_code = TransactionIBrailleDisplayConnectionWrite
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// BrailleDisplayConnectionStub dispatches incoming binder transactions
// to a typed IBrailleDisplayConnection implementation.
type BrailleDisplayConnectionStub struct {
	Impl IBrailleDisplayConnection
}

var _ binder.TransactionReceiver = (*BrailleDisplayConnectionStub)(nil)

func (s *BrailleDisplayConnectionStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBrailleDisplayConnectionDisconnect:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.Disconnect(ctx)
		_ = _err
		return nil, nil
	case TransactionIBrailleDisplayConnectionWrite:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_output []byte
		_ = _arg_output
		_err := s.Impl.Write(ctx, _arg_output)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
