package provider

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIS2CellIdsCallback = "android.location.provider.IS2CellIdsCallback"

const (
	TransactionIS2CellIdsCallbackOnResult = binder.FirstCallTransaction + 0
	TransactionIS2CellIdsCallbackOnError  = binder.FirstCallTransaction + 1
)

type IS2CellIdsCallback interface {
	AsBinder() binder.IBinder
	OnResult(ctx context.Context, s2CellIds []int64) error
	OnError(ctx context.Context) error
}

type S2CellIdsCallbackProxy struct {
	remote binder.IBinder
}

func NewS2CellIdsCallbackProxy(
	remote binder.IBinder,
) *S2CellIdsCallbackProxy {
	return &S2CellIdsCallbackProxy{remote: remote}
}

func (p *S2CellIdsCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IS2CellIdsCallback = (*S2CellIdsCallbackProxy)(nil)

func (p *S2CellIdsCallbackProxy) OnResult(
	ctx context.Context,
	s2CellIds []int64,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIS2CellIdsCallback)
	if s2CellIds == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(s2CellIds)))
		for _, _item := range s2CellIds {
			_data.WriteInt64(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIS2CellIdsCallback, "onResult")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *S2CellIdsCallbackProxy) OnError(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIS2CellIdsCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIS2CellIdsCallback, "onError")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// S2CellIdsCallbackStub dispatches incoming binder transactions
// to a typed IS2CellIdsCallback implementation.
type S2CellIdsCallbackStub struct {
	Impl IS2CellIdsCallback
}

var _ binder.TransactionReceiver = (*S2CellIdsCallbackStub)(nil)

func (s *S2CellIdsCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIS2CellIdsCallbackOnResult:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_s2CellIds []int64
		_ = _arg_s2CellIds
		_err := s.Impl.OnResult(ctx, _arg_s2CellIds)
		_ = _err
		return nil, nil
	case TransactionIS2CellIdsCallbackOnError:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnError(ctx)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
