package soundtrigger

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIRecognitionStatusCallback = "android.hardware.soundtrigger.IRecognitionStatusCallback"

const (
	TransactionIRecognitionStatusCallbackOnKeyphraseDetected           = binder.FirstCallTransaction + 0
	TransactionIRecognitionStatusCallbackOnGenericSoundTriggerDetected = binder.FirstCallTransaction + 1
	TransactionIRecognitionStatusCallbackOnRecognitionPaused           = binder.FirstCallTransaction + 2
	TransactionIRecognitionStatusCallbackOnRecognitionResumed          = binder.FirstCallTransaction + 3
	TransactionIRecognitionStatusCallbackOnPreempted                   = binder.FirstCallTransaction + 4
	TransactionIRecognitionStatusCallbackOnModuleDied                  = binder.FirstCallTransaction + 5
	TransactionIRecognitionStatusCallbackOnResumeFailed                = binder.FirstCallTransaction + 6
	TransactionIRecognitionStatusCallbackOnPauseFailed                 = binder.FirstCallTransaction + 7
)

type IRecognitionStatusCallback interface {
	AsBinder() binder.IBinder
	OnKeyphraseDetected(ctx context.Context, recognitionEvent SoundTriggerKeyphraseRecognitionEvent) error
	OnGenericSoundTriggerDetected(ctx context.Context, recognitionEvent SoundTriggerGenericRecognitionEvent) error
	OnRecognitionPaused(ctx context.Context) error
	OnRecognitionResumed(ctx context.Context) error
	OnPreempted(ctx context.Context) error
	OnModuleDied(ctx context.Context) error
	OnResumeFailed(ctx context.Context, status int32) error
	OnPauseFailed(ctx context.Context, status int32) error
}

type RecognitionStatusCallbackProxy struct {
	remote binder.IBinder
}

func NewRecognitionStatusCallbackProxy(
	remote binder.IBinder,
) *RecognitionStatusCallbackProxy {
	return &RecognitionStatusCallbackProxy{remote: remote}
}

func (p *RecognitionStatusCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IRecognitionStatusCallback = (*RecognitionStatusCallbackProxy)(nil)

func (p *RecognitionStatusCallbackProxy) OnKeyphraseDetected(
	ctx context.Context,
	recognitionEvent SoundTriggerKeyphraseRecognitionEvent,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)
	if _err := recognitionEvent.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onKeyphraseDetected"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnGenericSoundTriggerDetected(
	ctx context.Context,
	recognitionEvent SoundTriggerGenericRecognitionEvent,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)
	if _err := recognitionEvent.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onGenericSoundTriggerDetected"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnRecognitionPaused(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onRecognitionPaused"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnRecognitionResumed(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onRecognitionResumed"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnPreempted(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onPreempted"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnModuleDied(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onModuleDied"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnResumeFailed(
	ctx context.Context,
	status int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)
	_data.WriteInt32(status)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onResumeFailed"), binder.FlagOneway, _data)
	return _err
}

func (p *RecognitionStatusCallbackProxy) OnPauseFailed(
	ctx context.Context,
	status int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecognitionStatusCallback)
	_data.WriteInt32(status)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorIRecognitionStatusCallback, "onPauseFailed"), binder.FlagOneway, _data)
	return _err
}
