package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type Geofence struct {
	Latitude             float64
	Longitude            float64
	Radius               float32
	ExpirationRealtimeMs int64
}

var _ parcel.Parcelable = (*Geofence)(nil)

func (s *Geofence) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat64(s.Latitude)
	p.WriteFloat64(s.Longitude)
	p.WriteFloat32(s.Radius)
	p.WriteInt64(s.ExpirationRealtimeMs)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *Geofence) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Latitude, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Longitude, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Radius, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ExpirationRealtimeMs, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
