// Code generated by genparcelgo. DO NOT EDIT.

package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

type GnssClock struct {
	Flags                             int32
	LeapSecond                        int32
	TimeNanos                         int64
	TimeUncertaintyNanos              float64
	FullBiasNanos                     int64
	BiasNanos                         float64
	BiasUncertaintyNanos              float64
	DriftNanosPerSecond               float64
	DriftUncertaintyNanosPerSecond    float64
	HardwareClockDiscontinuityCount   int32
	ElapsedRealtimeNanos              int64
	ElapsedRealtimeUncertaintyNanos   float64
	ReferenceConstellationTypeForIsb  int32
	ReferenceCarrierFrequencyHzForIsb float64
	ReferenceCodeTypeForIsb           string
}

var _ parcel.Parcelable = (*GnssClock)(nil)

func (s *GnssClock) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Flags)
	p.WriteInt32(s.LeapSecond)
	p.WriteInt64(s.TimeNanos)
	p.WriteFloat64(s.TimeUncertaintyNanos)
	p.WriteInt64(s.FullBiasNanos)
	p.WriteFloat64(s.BiasNanos)
	p.WriteFloat64(s.BiasUncertaintyNanos)
	p.WriteFloat64(s.DriftNanosPerSecond)
	p.WriteFloat64(s.DriftUncertaintyNanosPerSecond)
	p.WriteInt32(s.HardwareClockDiscontinuityCount)
	p.WriteInt64(s.ElapsedRealtimeNanos)
	p.WriteFloat64(s.ElapsedRealtimeUncertaintyNanos)
	p.WriteInt32(s.ReferenceConstellationTypeForIsb)
	p.WriteFloat64(s.ReferenceCarrierFrequencyHzForIsb)
	p.WriteString16(s.ReferenceCodeTypeForIsb)
	return nil
}

func (s *GnssClock) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Flags, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.LeapSecond, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.TimeNanos, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.TimeUncertaintyNanos, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.FullBiasNanos, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.BiasNanos, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.BiasUncertaintyNanos, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.DriftNanosPerSecond, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.DriftUncertaintyNanosPerSecond, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.HardwareClockDiscontinuityCount, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.ElapsedRealtimeNanos, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.ElapsedRealtimeUncertaintyNanos, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.ReferenceConstellationTypeForIsb, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.ReferenceCarrierFrequencyHzForIsb, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.ReferenceCodeTypeForIsb, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	return nil
}
