// Code generated by genparcelgo. DO NOT EDIT.

package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

type GnssAntennaInfo struct {
	CarrierFrequencyMHz float64
	// PhaseCenterOffset: opaque type — not yet supported
	// PhaseCenterVariationCorrections: opaque type — not yet supported
	// SignalGainCorrections: opaque type — not yet supported
}

var _ parcel.Parcelable = (*GnssAntennaInfo)(nil)

func (s *GnssAntennaInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteFloat64(s.CarrierFrequencyMHz)
	return nil
}

func (s *GnssAntennaInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.CarrierFrequencyMHz, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	return nil
}
