package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GnssSignalType struct {
	ConstellationType  int32
	CarrierFrequencyHz float64
	CodeType           string
}

var _ parcel.Parcelable = (*GnssSignalType)(nil)

func (s *GnssSignalType) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.ConstellationType)
	p.WriteFloat64(s.CarrierFrequencyHz)
	p.WriteString16(s.CodeType)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *GnssSignalType) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ConstellationType, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.CarrierFrequencyHz, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.CodeType, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
