package tuner

// Code generated by aidlgen. DO NOT EDIT.

type FrontendIsdbtMode int32

const (
	FrontendIsdbtModeUNDEFINED FrontendIsdbtMode = 0
	FrontendIsdbtModeAUTO      FrontendIsdbtMode = (1 << 0)
	FrontendIsdbtModeMode1     FrontendIsdbtMode = (1 << 1)
	FrontendIsdbtModeMode2     FrontendIsdbtMode = (1 << 2)
	FrontendIsdbtModeMode3     FrontendIsdbtMode = (1 << 3)
)
