package location

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIContextHubTransactionCallback = "android.hardware.location.IContextHubTransactionCallback"

const (
	TransactionIContextHubTransactionCallbackOnQueryResponse       = binder.FirstCallTransaction + 0
	TransactionIContextHubTransactionCallbackOnTransactionComplete = binder.FirstCallTransaction + 1
)

type IContextHubTransactionCallback interface {
	AsBinder() binder.IBinder
	OnQueryResponse(ctx context.Context, result int32, nanoappList []NanoAppState) error
	OnTransactionComplete(ctx context.Context, result int32) error
}

type ContextHubTransactionCallbackProxy struct {
	remote binder.IBinder
}

func NewContextHubTransactionCallbackProxy(
	remote binder.IBinder,
) *ContextHubTransactionCallbackProxy {
	return &ContextHubTransactionCallbackProxy{remote: remote}
}

func (p *ContextHubTransactionCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IContextHubTransactionCallback = (*ContextHubTransactionCallbackProxy)(nil)

func (p *ContextHubTransactionCallbackProxy) OnQueryResponse(
	ctx context.Context,
	result int32,
	nanoappList []NanoAppState,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIContextHubTransactionCallback)
	_data.WriteInt32(result)
	if nanoappList == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(nanoappList)))
		for _, _item := range nanoappList {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIContextHubTransactionCallback, "onQueryResponse")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ContextHubTransactionCallbackProxy) OnTransactionComplete(
	ctx context.Context,
	result int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIContextHubTransactionCallback)
	_data.WriteInt32(result)

	_code, _err := p.remote.ResolveCode(DescriptorIContextHubTransactionCallback, "onTransactionComplete")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ContextHubTransactionCallbackStub dispatches incoming binder transactions
// to a typed IContextHubTransactionCallback implementation.
type ContextHubTransactionCallbackStub struct {
	Impl IContextHubTransactionCallback
}

var _ binder.TransactionReceiver = (*ContextHubTransactionCallbackStub)(nil)

func (s *ContextHubTransactionCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIContextHubTransactionCallbackOnQueryResponse:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_result, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_nanoappList []NanoAppState
		_ = _arg_nanoappList
		_err = s.Impl.OnQueryResponse(ctx, _arg_result, _arg_nanoappList)
		_ = _err
		return nil, nil
	case TransactionIContextHubTransactionCallbackOnTransactionComplete:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_result, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnTransactionComplete(ctx, _arg_result)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
