package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type NanoAppBinary struct {
}

var _ parcel.Parcelable = (*NanoAppBinary)(nil)

func (s *NanoAppBinary) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *NanoAppBinary) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
