package data

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TrafficDescriptor struct {
	Dnn string
}

var _ parcel.Parcelable = (*TrafficDescriptor)(nil)

func (s *TrafficDescriptor) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString16(s.Dnn)
	p.WriteBool(false) // placeholder OsAppId!=null
	return nil
}

func (s *TrafficDescriptor) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Dnn, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	if _, _err = p.ReadBool(); _err != nil { // skip OsAppId!=null
		return _err
	}
	return nil
}
