package broadcastradio

// Code generated by aidlgen. DO NOT EDIT.

type AnnouncementType byte

const (
	AnnouncementTypeINVALID   AnnouncementType = 0
	AnnouncementTypeEMERGENCY AnnouncementType = 1
	AnnouncementTypeWARNING   AnnouncementType = 2
	AnnouncementTypeTRAFFIC   AnnouncementType = 3
	AnnouncementTypeWEATHER   AnnouncementType = 4
	AnnouncementTypeNEWS      AnnouncementType = 5
	AnnouncementTypeEVENT     AnnouncementType = 6
	AnnouncementTypeSPORT     AnnouncementType = 7
	AnnouncementTypeMISC      AnnouncementType = 8
)
