package notification

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIConditionProvider = "android.service.notification.IConditionProvider"

const (
	TransactionIConditionProviderOnConnected   = binder.FirstCallTransaction + 0
	TransactionIConditionProviderOnSubscribe   = binder.FirstCallTransaction + 1
	TransactionIConditionProviderOnUnsubscribe = binder.FirstCallTransaction + 2
)

type IConditionProvider interface {
	AsBinder() binder.IBinder
	OnConnected(ctx context.Context) error
	OnSubscribe(ctx context.Context, conditionId interface{}) error
	OnUnsubscribe(ctx context.Context, conditionId interface{}) error
}

type ConditionProviderProxy struct {
	remote binder.IBinder
}

func NewConditionProviderProxy(
	remote binder.IBinder,
) *ConditionProviderProxy {
	return &ConditionProviderProxy{remote: remote}
}

func (p *ConditionProviderProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IConditionProvider = (*ConditionProviderProxy)(nil)

func (p *ConditionProviderProxy) OnConnected(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIConditionProvider)

	_code, _err := p.remote.ResolveCode(DescriptorIConditionProvider, "onConnected")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ConditionProviderProxy) OnSubscribe(
	ctx context.Context,
	conditionId interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIConditionProvider)

	_code, _err := p.remote.ResolveCode(DescriptorIConditionProvider, "onSubscribe")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ConditionProviderProxy) OnUnsubscribe(
	ctx context.Context,
	conditionId interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIConditionProvider)

	_code, _err := p.remote.ResolveCode(DescriptorIConditionProvider, "onUnsubscribe")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ConditionProviderStub dispatches incoming binder transactions
// to a typed IConditionProvider implementation.
type ConditionProviderStub struct {
	Impl IConditionProvider
}

var _ binder.TransactionReceiver = (*ConditionProviderStub)(nil)

func (s *ConditionProviderStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIConditionProviderOnConnected:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnConnected(ctx)
		_ = _err
		return nil, nil
	case TransactionIConditionProviderOnSubscribe:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_conditionId interface{}
		_err := s.Impl.OnSubscribe(ctx, _arg_conditionId)
		_ = _err
		return nil, nil
	case TransactionIConditionProviderOnUnsubscribe:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_conditionId interface{}
		_err := s.Impl.OnUnsubscribe(ctx, _arg_conditionId)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
