// Code generated by genparcelgo. DO NOT EDIT.

package notification

import (
	"github.com/xaionaro-go/binder/parcel"
)

type ZenModeConfig struct {
	User int32
	// AllowCalls?1:0: opaque type — not yet supported
	// AllowRepeatCallers?1:0: opaque type — not yet supported
	// AllowMessages?1:0: opaque type — not yet supported
	// AllowReminders?1:0: opaque type — not yet supported
	// AllowEvents?1:0: opaque type — not yet supported
	// AllowCallsFrom: opaque type — not yet supported
	// AllowMessagesFrom: opaque type — not yet supported
	// ManualRule: opaque type — not yet supported
	// AllowAlarms?1:0: opaque type — not yet supported
	// AllowMedia?1:0: opaque type — not yet supported
	// AllowSystem?1:0: opaque type — not yet supported
	// SuppressedVisualEffects: opaque type — not yet supported
	// AreChannelsBypassingDnd?1:0: opaque type — not yet supported
	// AllowConversations: opaque type — not yet supported
	// AllowConversationsFrom: opaque type — not yet supported
	// AllowPriorityChannels: opaque type — not yet supported
}

var _ parcel.Parcelable = (*ZenModeConfig)(nil)

func (s *ZenModeConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.User)
	return nil
}

func (s *ZenModeConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.User, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
