package autofill

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIInlineSuggestionUi = "android.service.autofill.IInlineSuggestionUi"

const (
	TransactionIInlineSuggestionUiGetSurfacePackage             = binder.FirstCallTransaction + 0
	TransactionIInlineSuggestionUiReleaseSurfaceControlViewHost = binder.FirstCallTransaction + 1
)

type IInlineSuggestionUi interface {
	AsBinder() binder.IBinder
	GetSurfacePackage(ctx context.Context, callback ISurfacePackageResultCallback) error
	ReleaseSurfaceControlViewHost(ctx context.Context) error
}

type InlineSuggestionUiProxy struct {
	remote binder.IBinder
}

func NewInlineSuggestionUiProxy(
	remote binder.IBinder,
) *InlineSuggestionUiProxy {
	return &InlineSuggestionUiProxy{remote: remote}
}

func (p *InlineSuggestionUiProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IInlineSuggestionUi = (*InlineSuggestionUiProxy)(nil)

func (p *InlineSuggestionUiProxy) GetSurfacePackage(
	ctx context.Context,
	callback ISurfacePackageResultCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInlineSuggestionUi)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIInlineSuggestionUi, "getSurfacePackage")
	if _err != nil {
		_code = TransactionIInlineSuggestionUiGetSurfacePackage
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InlineSuggestionUiProxy) ReleaseSurfaceControlViewHost(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInlineSuggestionUi)

	_code, _err := p.remote.ResolveCode(DescriptorIInlineSuggestionUi, "releaseSurfaceControlViewHost")
	if _err != nil {
		_code = TransactionIInlineSuggestionUiReleaseSurfaceControlViewHost
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// InlineSuggestionUiStub dispatches incoming binder transactions
// to a typed IInlineSuggestionUi implementation.
type InlineSuggestionUiStub struct {
	Impl IInlineSuggestionUi
}

var _ binder.TransactionReceiver = (*InlineSuggestionUiStub)(nil)

func (s *InlineSuggestionUiStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIInlineSuggestionUiGetSurfacePackage:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback ISurfacePackageResultCallback
		_ = _arg_callback
		_err := s.Impl.GetSurfacePackage(ctx, _arg_callback)
		_ = _err
		return nil, nil
	case TransactionIInlineSuggestionUiReleaseSurfaceControlViewHost:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.ReleaseSurfaceControlViewHost(ctx)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
