package gui

import (
	guiDeviceProductInfo "github.com/xaionaro-go/binder/android/gui/DeviceProductInfo"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type DeviceProductInfo struct {
	Name                   string
	ManufacturerPnpId      []byte
	ProductId              string
	ManufactureOrModelDate guiDeviceProductInfo.ManufactureOrModelDate
	RelativeAddress        []byte
}

var _ parcel.Parcelable = (*DeviceProductInfo)(nil)

func (s *DeviceProductInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteString16(s.Name)
	p.WriteByteArray(s.ManufacturerPnpId)
	p.WriteString16(s.ProductId)
	if _err := s.ManufactureOrModelDate.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteByteArray(s.RelativeAddress)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *DeviceProductInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.Name, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	s.ManufacturerPnpId, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	s.ProductId, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	if _err = s.ManufactureOrModelDate.UnmarshalParcel(p); _err != nil {
		return _err
	}

	s.RelativeAddress, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
