// Code generated by spec2go. DO NOT EDIT.

package os

import (
	"context"
	"fmt"

	"github.com/AndroidGoLab/binder/servicemanager"
)

// GetPowerManager retrieves the PowerService service and returns a typed proxy.
func GetPowerManager(
	ctx context.Context,
	sm *servicemanager.ServiceManager,
) (*PowerManagerProxy, error) {
	svc, err := sm.GetService(ctx, servicemanager.PowerService)
	if err != nil {
		return nil, fmt.Errorf("GetPowerManager: %w", err)
	}
	return NewPowerManagerProxy(svc), nil
}
