package os

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAccessor = "android.os.IAccessor"

const (
	TransactionIAccessorAddConnection   = binder.FirstCallTransaction + 0
	TransactionIAccessorGetInstanceName = binder.FirstCallTransaction + 1
)

type IAccessor interface {
	AsBinder() binder.IBinder
	AddConnection(ctx context.Context) (int32, error)
	GetInstanceName(ctx context.Context) (string, error)
}

const (
	IAccessorErrorConnectionInfoNotFound  int32 = 0
	IAccessorErrorFailedToCreateSocket    int32 = 1
	IAccessorErrorFailedToConnectToSocket int32 = 2
	IAccessorErrorFailedToConnectEacces   int32 = 3
	IAccessorErrorUnsupportedSocketFamily int32 = 4
)

type AccessorProxy struct {
	remote binder.IBinder
}

func NewAccessorProxy(
	remote binder.IBinder,
) *AccessorProxy {
	return &AccessorProxy{remote: remote}
}

func (p *AccessorProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAccessor = (*AccessorProxy)(nil)

func (p *AccessorProxy) AddConnection(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessor)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessor, "addConnection")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadFileDescriptor()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessorProxy) GetInstanceName(
	ctx context.Context,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessor)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessor, "getInstanceName")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

// AccessorStub dispatches incoming binder transactions
// to a typed IAccessor implementation.
type AccessorStub struct {
	Impl IAccessor
}

var _ binder.TransactionReceiver = (*AccessorStub)(nil)

func (s *AccessorStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIAccessorAddConnection:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.AddConnection(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteFileDescriptor(_result)
		return _reply, nil
	case TransactionIAccessorGetInstanceName:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetInstanceName(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteString16(_result)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
