package os

// Code generated by aidlgen. DO NOT EDIT.

type InputEventInjectionResult int32

const (
	InputEventInjectionResultPENDING        InputEventInjectionResult = -1
	InputEventInjectionResultSUCCEEDED      InputEventInjectionResult = 0
	InputEventInjectionResultTargetMismatch InputEventInjectionResult = 1
	InputEventInjectionResultFAILED         InputEventInjectionResult = 2
	InputEventInjectionResultTimedOut       InputEventInjectionResult = 3
	InputEventInjectionResultFtl_first      InputEventInjectionResult = InputEventInjectionResultPENDING
	InputEventInjectionResultFtl_last       InputEventInjectionResult = InputEventInjectionResultTimedOut
)
