package os

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIServiceCallback = "android.os.IServiceCallback"

const (
	TransactionIServiceCallbackOnRegistration = binder.FirstCallTransaction + 0
)

type IServiceCallback interface {
	AsBinder() binder.IBinder
	OnRegistration(ctx context.Context, name string, binder_ binder.IBinder) error
}

type ServiceCallbackProxy struct {
	remote binder.IBinder
}

func NewServiceCallbackProxy(
	remote binder.IBinder,
) *ServiceCallbackProxy {
	return &ServiceCallbackProxy{remote: remote}
}

func (p *ServiceCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IServiceCallback = (*ServiceCallbackProxy)(nil)

func (p *ServiceCallbackProxy) OnRegistration(
	ctx context.Context,
	name string,
	binder_ binder.IBinder,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIServiceCallback)
	_data.WriteString16(name)
	_data.WriteStrongBinder(binder_.Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIServiceCallback, "onRegistration")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ServiceCallbackStub dispatches incoming binder transactions
// to a typed IServiceCallback implementation.
type ServiceCallbackStub struct {
	Impl IServiceCallback
}

var _ binder.TransactionReceiver = (*ServiceCallbackStub)(nil)

func (s *ServiceCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIServiceCallbackOnRegistration:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_name, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_binder_ binder.IBinder
		_ = _arg_binder_
		_err = s.Impl.OnRegistration(ctx, _arg_name, _arg_binder_)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
