package os

import (
	"context"
	graphics "github.com/xaionaro-go/aidl/android/graphics"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIUserManager = "android.os.IUserManager"

const (
	TransactionIUserManagerGetCredentialOwnerProfile                       = binder.FirstCallTransaction + 0
	TransactionIUserManagerGetProfileParentId                              = binder.FirstCallTransaction + 1
	TransactionIUserManagerCreateUserWithThrow                             = binder.FirstCallTransaction + 2
	TransactionIUserManagerPreCreateUserWithThrow                          = binder.FirstCallTransaction + 3
	TransactionIUserManagerCreateProfileForUserWithThrow                   = binder.FirstCallTransaction + 4
	TransactionIUserManagerCreateRestrictedProfileWithThrow                = binder.FirstCallTransaction + 5
	TransactionIUserManagerGetPreInstallableSystemPackages                 = binder.FirstCallTransaction + 6
	TransactionIUserManagerSetUserEnabled                                  = binder.FirstCallTransaction + 7
	TransactionIUserManagerSetUserAdmin                                    = binder.FirstCallTransaction + 8
	TransactionIUserManagerRevokeUserAdmin                                 = binder.FirstCallTransaction + 9
	TransactionIUserManagerEvictCredentialEncryptionKey                    = binder.FirstCallTransaction + 10
	TransactionIUserManagerRemoveUser                                      = binder.FirstCallTransaction + 11
	TransactionIUserManagerRemoveUserEvenWhenDisallowed                    = binder.FirstCallTransaction + 12
	TransactionIUserManagerSetUserName                                     = binder.FirstCallTransaction + 13
	TransactionIUserManagerSetUserIcon                                     = binder.FirstCallTransaction + 14
	TransactionIUserManagerGetUserIcon                                     = binder.FirstCallTransaction + 15
	TransactionIUserManagerGetPrimaryUser                                  = binder.FirstCallTransaction + 16
	TransactionIUserManagerGetMainUserId                                   = binder.FirstCallTransaction + 17
	TransactionIUserManagerGetCommunalProfileId                            = binder.FirstCallTransaction + 18
	TransactionIUserManagerGetPreviousFullUserToEnterForeground            = binder.FirstCallTransaction + 19
	TransactionIUserManagerGetUsers                                        = binder.FirstCallTransaction + 20
	TransactionIUserManagerGetProfiles                                     = binder.FirstCallTransaction + 21
	TransactionIUserManagerGetProfileIds                                   = binder.FirstCallTransaction + 22
	TransactionIUserManagerIsUserTypeEnabled                               = binder.FirstCallTransaction + 23
	TransactionIUserManagerCanAddMoreUsersOfType                           = binder.FirstCallTransaction + 24
	TransactionIUserManagerGetRemainingCreatableUserCount                  = binder.FirstCallTransaction + 25
	TransactionIUserManagerGetRemainingCreatableProfileCount               = binder.FirstCallTransaction + 26
	TransactionIUserManagerCanAddMoreProfilesToUser                        = binder.FirstCallTransaction + 27
	TransactionIUserManagerCanAddMoreManagedProfiles                       = binder.FirstCallTransaction + 28
	TransactionIUserManagerGetProfileParent                                = binder.FirstCallTransaction + 29
	TransactionIUserManagerIsSameProfileGroup                              = binder.FirstCallTransaction + 30
	TransactionIUserManagerIsHeadlessSystemUserMode                        = binder.FirstCallTransaction + 31
	TransactionIUserManagerIsUserOfType                                    = binder.FirstCallTransaction + 32
	TransactionIUserManagerGetUserInfo                                     = binder.FirstCallTransaction + 33
	TransactionIUserManagerGetUserPropertiesCopy                           = binder.FirstCallTransaction + 34
	TransactionIUserManagerGetUserAccount                                  = binder.FirstCallTransaction + 35
	TransactionIUserManagerSetUserAccount                                  = binder.FirstCallTransaction + 36
	TransactionIUserManagerGetUserCreationTime                             = binder.FirstCallTransaction + 37
	TransactionIUserManagerGetUserSwitchability                            = binder.FirstCallTransaction + 38
	TransactionIUserManagerIsUserSwitcherEnabled                           = binder.FirstCallTransaction + 39
	TransactionIUserManagerIsRestricted                                    = binder.FirstCallTransaction + 40
	TransactionIUserManagerCanHaveRestrictedProfile                        = binder.FirstCallTransaction + 41
	TransactionIUserManagerCanAddPrivateProfile                            = binder.FirstCallTransaction + 42
	TransactionIUserManagerGetUserSerialNumber                             = binder.FirstCallTransaction + 43
	TransactionIUserManagerGetUserHandle                                   = binder.FirstCallTransaction + 44
	TransactionIUserManagerGetUserRestrictionSource                        = binder.FirstCallTransaction + 45
	TransactionIUserManagerGetUserRestrictionSources                       = binder.FirstCallTransaction + 46
	TransactionIUserManagerGetUserRestrictions                             = binder.FirstCallTransaction + 47
	TransactionIUserManagerHasBaseUserRestriction                          = binder.FirstCallTransaction + 48
	TransactionIUserManagerHasUserRestriction                              = binder.FirstCallTransaction + 49
	TransactionIUserManagerHasUserRestrictionOnAnyUser                     = binder.FirstCallTransaction + 50
	TransactionIUserManagerIsSettingRestrictedForUser                      = binder.FirstCallTransaction + 51
	TransactionIUserManagerAddUserRestrictionsListener                     = binder.FirstCallTransaction + 52
	TransactionIUserManagerSetUserRestriction                              = binder.FirstCallTransaction + 53
	TransactionIUserManagerSetApplicationRestrictions                      = binder.FirstCallTransaction + 54
	TransactionIUserManagerGetApplicationRestrictions                      = binder.FirstCallTransaction + 55
	TransactionIUserManagerGetApplicationRestrictionsForUser               = binder.FirstCallTransaction + 56
	TransactionIUserManagerSetDefaultGuestRestrictions                     = binder.FirstCallTransaction + 57
	TransactionIUserManagerGetDefaultGuestRestrictions                     = binder.FirstCallTransaction + 58
	TransactionIUserManagerRemoveUserWhenPossible                          = binder.FirstCallTransaction + 59
	TransactionIUserManagerMarkGuestForDeletion                            = binder.FirstCallTransaction + 60
	TransactionIUserManagerGetGuestUsers                                   = binder.FirstCallTransaction + 61
	TransactionIUserManagerIsQuietModeEnabled                              = binder.FirstCallTransaction + 62
	TransactionIUserManagerCreateUserWithAttributes                        = binder.FirstCallTransaction + 63
	TransactionIUserManagerSetSeedAccountData                              = binder.FirstCallTransaction + 64
	TransactionIUserManagerGetSeedAccountName                              = binder.FirstCallTransaction + 65
	TransactionIUserManagerGetSeedAccountType                              = binder.FirstCallTransaction + 66
	TransactionIUserManagerGetSeedAccountOptions                           = binder.FirstCallTransaction + 67
	TransactionIUserManagerClearSeedAccountData                            = binder.FirstCallTransaction + 68
	TransactionIUserManagerSomeUserHasSeedAccount                          = binder.FirstCallTransaction + 69
	TransactionIUserManagerSomeUserHasAccount                              = binder.FirstCallTransaction + 70
	TransactionIUserManagerGetProfileType                                  = binder.FirstCallTransaction + 71
	TransactionIUserManagerIsDemoUser                                      = binder.FirstCallTransaction + 72
	TransactionIUserManagerIsAdminUser                                     = binder.FirstCallTransaction + 73
	TransactionIUserManagerIsPreCreated                                    = binder.FirstCallTransaction + 74
	TransactionIUserManagerCreateProfileForUserEvenWhenDisallowedWithThrow = binder.FirstCallTransaction + 75
	TransactionIUserManagerIsUserUnlockingOrUnlocked                       = binder.FirstCallTransaction + 76
	TransactionIUserManagerGetUserIconBadgeResId                           = binder.FirstCallTransaction + 77
	TransactionIUserManagerGetUserBadgeResId                               = binder.FirstCallTransaction + 78
	TransactionIUserManagerGetUserBadgeNoBackgroundResId                   = binder.FirstCallTransaction + 79
	TransactionIUserManagerGetUserBadgeLabelResId                          = binder.FirstCallTransaction + 80
	TransactionIUserManagerGetUserBadgeColorResId                          = binder.FirstCallTransaction + 81
	TransactionIUserManagerGetUserBadgeDarkColorResId                      = binder.FirstCallTransaction + 82
	TransactionIUserManagerGetUserStatusBarIconResId                       = binder.FirstCallTransaction + 83
	TransactionIUserManagerHasBadge                                        = binder.FirstCallTransaction + 84
	TransactionIUserManagerGetProfileLabelResId                            = binder.FirstCallTransaction + 85
	TransactionIUserManagerGetProfileAccessibilityLabelResId               = binder.FirstCallTransaction + 86
	TransactionIUserManagerIsUserUnlocked                                  = binder.FirstCallTransaction + 87
	TransactionIUserManagerIsUserRunning                                   = binder.FirstCallTransaction + 88
	TransactionIUserManagerIsUserForeground                                = binder.FirstCallTransaction + 89
	TransactionIUserManagerIsUserVisible                                   = binder.FirstCallTransaction + 90
	TransactionIUserManagerGetVisibleUsers                                 = binder.FirstCallTransaction + 91
	TransactionIUserManagerGetMainDisplayIdAssignedToUser                  = binder.FirstCallTransaction + 92
	TransactionIUserManagerIsForegroundUserAdmin                           = binder.FirstCallTransaction + 93
	TransactionIUserManagerIsUserNameSet                                   = binder.FirstCallTransaction + 94
	TransactionIUserManagerHasRestrictedProfiles                           = binder.FirstCallTransaction + 95
	TransactionIUserManagerRequestQuietModeEnabled                         = binder.FirstCallTransaction + 96
	TransactionIUserManagerGetUserName                                     = binder.FirstCallTransaction + 97
	TransactionIUserManagerGetUserStartRealtime                            = binder.FirstCallTransaction + 98
	TransactionIUserManagerGetUserUnlockRealtime                           = binder.FirstCallTransaction + 99
	TransactionIUserManagerSetUserEphemeral                                = binder.FirstCallTransaction + 100
	TransactionIUserManagerSetBootUser                                     = binder.FirstCallTransaction + 101
	TransactionIUserManagerGetBootUser                                     = binder.FirstCallTransaction + 102
	TransactionIUserManagerGetProfileIdsExcludingHidden                    = binder.FirstCallTransaction + 103
)

type IUserManager interface {
	AsBinder() binder.IBinder
	GetCredentialOwnerProfile(ctx context.Context, userId int32) (int32, error)
	GetProfileParentId(ctx context.Context, userId int32) (int32, error)
	CreateUserWithThrow(ctx context.Context, name string, userType string, flags int32) (interface{}, error)
	PreCreateUserWithThrow(ctx context.Context, userType string) (interface{}, error)
	CreateProfileForUserWithThrow(ctx context.Context, name string, userType string, flags int32, userId int32, disallowedPackages []string) (interface{}, error)
	CreateRestrictedProfileWithThrow(ctx context.Context, name string, parentUserHandle int32) (interface{}, error)
	GetPreInstallableSystemPackages(ctx context.Context, userType string) ([]string, error)
	SetUserEnabled(ctx context.Context, userId int32) error
	SetUserAdmin(ctx context.Context, userId int32) error
	RevokeUserAdmin(ctx context.Context, userId int32) error
	EvictCredentialEncryptionKey(ctx context.Context, userId int32) error
	RemoveUser(ctx context.Context, userId int32) (bool, error)
	RemoveUserEvenWhenDisallowed(ctx context.Context, userId int32) (bool, error)
	SetUserName(ctx context.Context, userId int32, name string) error
	SetUserIcon(ctx context.Context, userId int32, icon graphics.Bitmap) error
	GetUserIcon(ctx context.Context, userId int32) (int32, error)
	GetPrimaryUser(ctx context.Context) (interface{}, error)
	GetMainUserId(ctx context.Context) (int32, error)
	GetCommunalProfileId(ctx context.Context) (int32, error)
	GetPreviousFullUserToEnterForeground(ctx context.Context) (int32, error)
	GetUsers(ctx context.Context, excludePartial bool, excludeDying bool, excludePreCreated bool) ([]interface{}, error)
	GetProfiles(ctx context.Context, userId int32, enabledOnly bool) ([]interface{}, error)
	GetProfileIds(ctx context.Context, userId int32, enabledOnly bool) ([]int32, error)
	IsUserTypeEnabled(ctx context.Context, userType string) (bool, error)
	CanAddMoreUsersOfType(ctx context.Context, userType string) (bool, error)
	GetRemainingCreatableUserCount(ctx context.Context, userType string) (int32, error)
	GetRemainingCreatableProfileCount(ctx context.Context, userType string, userId int32) (int32, error)
	CanAddMoreProfilesToUser(ctx context.Context, userType string, userId int32, allowedToRemoveOne bool) (bool, error)
	CanAddMoreManagedProfiles(ctx context.Context, userId int32, allowedToRemoveOne bool) (bool, error)
	GetProfileParent(ctx context.Context, userId int32) (interface{}, error)
	IsSameProfileGroup(ctx context.Context, userId int32, otherUserHandle int32) (bool, error)
	IsHeadlessSystemUserMode(ctx context.Context) (bool, error)
	IsUserOfType(ctx context.Context, userId int32, userType string) (bool, error)
	GetUserInfo(ctx context.Context, userId int32) (interface{}, error)
	GetUserPropertiesCopy(ctx context.Context, userId int32) (interface{}, error)
	GetUserAccount(ctx context.Context, userId int32) (string, error)
	SetUserAccount(ctx context.Context, userId int32, accountName string) error
	GetUserCreationTime(ctx context.Context, userId int32) (int64, error)
	GetUserSwitchability(ctx context.Context, userId int32) (int32, error)
	IsUserSwitcherEnabled(ctx context.Context, showEvenIfNotActionable bool, mUserId int32) (bool, error)
	IsRestricted(ctx context.Context, userId int32) (bool, error)
	CanHaveRestrictedProfile(ctx context.Context, userId int32) (bool, error)
	CanAddPrivateProfile(ctx context.Context, userId int32) (bool, error)
	GetUserSerialNumber(ctx context.Context, userId int32) (int32, error)
	GetUserHandle(ctx context.Context, userSerialNumber int32) (int32, error)
	GetUserRestrictionSource(ctx context.Context, restrictionKey string, userId int32) (int32, error)
	GetUserRestrictionSources(ctx context.Context, restrictionKey string, userId int32) ([]UserManagerEnforcingUser, error)
	GetUserRestrictions(ctx context.Context, userId int32) (Bundle, error)
	HasBaseUserRestriction(ctx context.Context, restrictionKey string, userId int32) (bool, error)
	HasUserRestriction(ctx context.Context, restrictionKey string, userId int32) (bool, error)
	HasUserRestrictionOnAnyUser(ctx context.Context, restrictionKey string) (bool, error)
	IsSettingRestrictedForUser(ctx context.Context, setting string, userId int32, value string, callingUid int32) (bool, error)
	AddUserRestrictionsListener(ctx context.Context, listener IUserRestrictionsListener) error
	SetUserRestriction(ctx context.Context, key string, value bool, userId int32) error
	SetApplicationRestrictions(ctx context.Context, packageName string, restrictions Bundle, userId int32) error
	GetApplicationRestrictions(ctx context.Context, packageName string) (Bundle, error)
	GetApplicationRestrictionsForUser(ctx context.Context, packageName string, userId int32) (Bundle, error)
	SetDefaultGuestRestrictions(ctx context.Context, restrictions Bundle) error
	GetDefaultGuestRestrictions(ctx context.Context) (Bundle, error)
	RemoveUserWhenPossible(ctx context.Context, userId int32, overrideDevicePolicy bool) (int32, error)
	MarkGuestForDeletion(ctx context.Context, userId int32) (bool, error)
	GetGuestUsers(ctx context.Context) ([]interface{}, error)
	IsQuietModeEnabled(ctx context.Context, userId int32) (bool, error)
	CreateUserWithAttributes(ctx context.Context, userName string, userType string, flags int32, userIcon graphics.Bitmap, accountName string, accountType string, accountOptions interface{}) (UserHandle, error)
	SetSeedAccountData(ctx context.Context, userId int32, accountName string, accountType string, accountOptions interface{}, persist bool) error
	GetSeedAccountName(ctx context.Context, userId int32) (string, error)
	GetSeedAccountType(ctx context.Context, userId int32) (string, error)
	GetSeedAccountOptions(ctx context.Context, userId int32) (interface{}, error)
	ClearSeedAccountData(ctx context.Context, userId int32) error
	SomeUserHasSeedAccount(ctx context.Context, accountName string, accountType string) (bool, error)
	SomeUserHasAccount(ctx context.Context, accountName string, accountType string) (bool, error)
	GetProfileType(ctx context.Context, userId int32) (string, error)
	IsDemoUser(ctx context.Context, userId int32) (bool, error)
	IsAdminUser(ctx context.Context, userId int32) (bool, error)
	IsPreCreated(ctx context.Context, userId int32) (bool, error)
	CreateProfileForUserEvenWhenDisallowedWithThrow(ctx context.Context, name string, userType string, flags int32, userId int32, disallowedPackages []string) (interface{}, error)
	IsUserUnlockingOrUnlocked(ctx context.Context, userId int32) (bool, error)
	GetUserIconBadgeResId(ctx context.Context, userId int32) (int32, error)
	GetUserBadgeResId(ctx context.Context, userId int32) (int32, error)
	GetUserBadgeNoBackgroundResId(ctx context.Context, userId int32) (int32, error)
	GetUserBadgeLabelResId(ctx context.Context, userId int32) (int32, error)
	GetUserBadgeColorResId(ctx context.Context, userId int32) (int32, error)
	GetUserBadgeDarkColorResId(ctx context.Context, userId int32) (int32, error)
	GetUserStatusBarIconResId(ctx context.Context, userId int32) (int32, error)
	HasBadge(ctx context.Context, userId int32) (bool, error)
	GetProfileLabelResId(ctx context.Context, userId int32) (int32, error)
	GetProfileAccessibilityLabelResId(ctx context.Context, userId int32) (int32, error)
	IsUserUnlocked(ctx context.Context, userId int32) (bool, error)
	IsUserRunning(ctx context.Context, userId int32) (bool, error)
	IsUserForeground(ctx context.Context, userId int32) (bool, error)
	IsUserVisible(ctx context.Context, userId int32) (bool, error)
	GetVisibleUsers(ctx context.Context) ([]int32, error)
	GetMainDisplayIdAssignedToUser(ctx context.Context, userId int32) (int32, error)
	IsForegroundUserAdmin(ctx context.Context) (bool, error)
	IsUserNameSet(ctx context.Context, userId int32) (bool, error)
	HasRestrictedProfiles(ctx context.Context, userId int32) (bool, error)
	RequestQuietModeEnabled(ctx context.Context, callingPackage string, enableQuietMode bool, userId int32, target interface{}, flags int32) (bool, error)
	GetUserName(ctx context.Context) (string, error)
	GetUserStartRealtime(ctx context.Context) (int64, error)
	GetUserUnlockRealtime(ctx context.Context) (int64, error)
	SetUserEphemeral(ctx context.Context, userId int32, enableEphemeral bool) (bool, error)
	SetBootUser(ctx context.Context, userId int32) error
	GetBootUser(ctx context.Context) (int32, error)
	GetProfileIdsExcludingHidden(ctx context.Context, userId int32, enabledOnly bool) ([]int32, error)
}

type UserManagerProxy struct {
	remote binder.IBinder
}

func NewUserManagerProxy(
	remote binder.IBinder,
) *UserManagerProxy {
	return &UserManagerProxy{remote: remote}
}

func (p *UserManagerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IUserManager = (*UserManagerProxy)(nil)

func (p *UserManagerProxy) GetCredentialOwnerProfile(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetCredentialOwnerProfile, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileParentId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileParentId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CreateUserWithThrow(
	ctx context.Context,
	name string,
	userType string,
	flags int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(name)
	_data.WriteString16(userType)
	_data.WriteInt32(flags)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCreateUserWithThrow, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) PreCreateUserWithThrow(
	ctx context.Context,
	userType string,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerPreCreateUserWithThrow, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) CreateProfileForUserWithThrow(
	ctx context.Context,
	name string,
	userType string,
	flags int32,
	userId int32,
	disallowedPackages []string,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(name)
	_data.WriteString16(userType)
	_data.WriteInt32(flags)
	_data.WriteInt32(userId)
	if disallowedPackages == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(disallowedPackages)))
		for _, _item := range disallowedPackages {
			_data.WriteString16(_item)
		}
	}

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCreateProfileForUserWithThrow, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) CreateRestrictedProfileWithThrow(
	ctx context.Context,
	name string,
	parentUserHandle int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(name)
	_data.WriteInt32(parentUserHandle)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCreateRestrictedProfileWithThrow, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) GetPreInstallableSystemPackages(
	ctx context.Context,
	userType string,
) ([]string, error) {
	var _result []string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetPreInstallableSystemPackages, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]string, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadString16()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) SetUserEnabled(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserEnabled, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) SetUserAdmin(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserAdmin, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) RevokeUserAdmin(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerRevokeUserAdmin, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) EvictCredentialEncryptionKey(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerEvictCredentialEncryptionKey, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) RemoveUser(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerRemoveUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) RemoveUserEvenWhenDisallowed(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerRemoveUserEvenWhenDisallowed, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetUserName(
	ctx context.Context,
	userId int32,
	name string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteString16(name)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserName, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) SetUserIcon(
	ctx context.Context,
	userId int32,
	icon graphics.Bitmap,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	if _err := icon.MarshalParcel(_data); _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserIcon, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetUserIcon(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserIcon, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadFileDescriptor()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetPrimaryUser(
	ctx context.Context,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetPrimaryUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) GetMainUserId(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetMainUserId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetCommunalProfileId(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetCommunalProfileId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetPreviousFullUserToEnterForeground(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetPreviousFullUserToEnterForeground, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUsers(
	ctx context.Context,
	excludePartial bool,
	excludeDying bool,
	excludePreCreated bool,
) ([]interface{}, error) {
	var _result []interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteBool(excludePartial)
	_data.WriteBool(excludeDying)
	_data.WriteBool(excludePreCreated)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUsers, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]interface{}, _count)
		for _i := int32(0); _i < _count; _i++ {
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfiles(
	ctx context.Context,
	userId int32,
	enabledOnly bool,
) ([]interface{}, error) {
	var _result []interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(enabledOnly)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfiles, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]interface{}, _count)
		for _i := int32(0); _i < _count; _i++ {
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileIds(
	ctx context.Context,
	userId int32,
	enabledOnly bool,
) ([]int32, error) {
	var _result []int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(enabledOnly)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileIds, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]int32, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadInt32()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserTypeEnabled(
	ctx context.Context,
	userType string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserTypeEnabled, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CanAddMoreUsersOfType(
	ctx context.Context,
	userType string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCanAddMoreUsersOfType, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetRemainingCreatableUserCount(
	ctx context.Context,
	userType string,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetRemainingCreatableUserCount, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetRemainingCreatableProfileCount(
	ctx context.Context,
	userType string,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetRemainingCreatableProfileCount, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CanAddMoreProfilesToUser(
	ctx context.Context,
	userType string,
	userId int32,
	allowedToRemoveOne bool,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userType)
	_data.WriteInt32(userId)
	_data.WriteBool(allowedToRemoveOne)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCanAddMoreProfilesToUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CanAddMoreManagedProfiles(
	ctx context.Context,
	userId int32,
	allowedToRemoveOne bool,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(allowedToRemoveOne)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCanAddMoreManagedProfiles, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileParent(
	ctx context.Context,
	userId int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileParent, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) IsSameProfileGroup(
	ctx context.Context,
	userId int32,
	otherUserHandle int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteInt32(otherUserHandle)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsSameProfileGroup, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsHeadlessSystemUserMode(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsHeadlessSystemUserMode, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserOfType(
	ctx context.Context,
	userId int32,
	userType string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteString16(userType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserOfType, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserInfo(
	ctx context.Context,
	userId int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserInfo, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) GetUserPropertiesCopy(
	ctx context.Context,
	userId int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserPropertiesCopy, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) GetUserAccount(
	ctx context.Context,
	userId int32,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserAccount, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetUserAccount(
	ctx context.Context,
	userId int32,
	accountName string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteString16(accountName)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserAccount, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetUserCreationTime(
	ctx context.Context,
	userId int32,
) (int64, error) {
	var _result int64
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserCreationTime, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserSwitchability(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserSwitchability, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserSwitcherEnabled(
	ctx context.Context,
	showEvenIfNotActionable bool,
	mUserId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteBool(showEvenIfNotActionable)
	_data.WriteInt32(mUserId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserSwitcherEnabled, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsRestricted(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsRestricted, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CanHaveRestrictedProfile(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCanHaveRestrictedProfile, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CanAddPrivateProfile(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCanAddPrivateProfile, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserSerialNumber(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserSerialNumber, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserHandle(
	ctx context.Context,
	userSerialNumber int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userSerialNumber)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserHandle, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserRestrictionSource(
	ctx context.Context,
	restrictionKey string,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(restrictionKey)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserRestrictionSource, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserRestrictionSources(
	ctx context.Context,
	restrictionKey string,
	userId int32,
) ([]UserManagerEnforcingUser, error) {
	var _result []UserManagerEnforcingUser
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(restrictionKey)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserRestrictionSources, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]UserManagerEnforcingUser, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserRestrictions(
	ctx context.Context,
	userId int32,
) (Bundle, error) {
	var _result Bundle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserRestrictions, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	if _err = _result.UnmarshalParcel(_reply); _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) HasBaseUserRestriction(
	ctx context.Context,
	restrictionKey string,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(restrictionKey)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerHasBaseUserRestriction, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) HasUserRestriction(
	ctx context.Context,
	restrictionKey string,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(restrictionKey)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerHasUserRestriction, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) HasUserRestrictionOnAnyUser(
	ctx context.Context,
	restrictionKey string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(restrictionKey)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerHasUserRestrictionOnAnyUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsSettingRestrictedForUser(
	ctx context.Context,
	setting string,
	userId int32,
	value string,
	callingUid int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(setting)
	_data.WriteInt32(userId)
	_data.WriteString16(value)
	_data.WriteInt32(callingUid)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsSettingRestrictedForUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) AddUserRestrictionsListener(
	ctx context.Context,
	listener IUserRestrictionsListener,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteStrongBinder(listener.AsBinder().Handle())

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerAddUserRestrictionsListener, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) SetUserRestriction(
	ctx context.Context,
	key string,
	value bool,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(key)
	_data.WriteBool(value)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserRestriction, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) SetApplicationRestrictions(
	ctx context.Context,
	packageName string,
	restrictions Bundle,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(packageName)
	if _err := restrictions.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetApplicationRestrictions, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetApplicationRestrictions(
	ctx context.Context,
	packageName string,
) (Bundle, error) {
	var _result Bundle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(packageName)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetApplicationRestrictions, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	if _err = _result.UnmarshalParcel(_reply); _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetApplicationRestrictionsForUser(
	ctx context.Context,
	packageName string,
	userId int32,
) (Bundle, error) {
	var _result Bundle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(packageName)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetApplicationRestrictionsForUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	if _err = _result.UnmarshalParcel(_reply); _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetDefaultGuestRestrictions(
	ctx context.Context,
	restrictions Bundle,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	if _err := restrictions.MarshalParcel(_data); _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetDefaultGuestRestrictions, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetDefaultGuestRestrictions(
	ctx context.Context,
) (Bundle, error) {
	var _result Bundle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetDefaultGuestRestrictions, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	if _err = _result.UnmarshalParcel(_reply); _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) RemoveUserWhenPossible(
	ctx context.Context,
	userId int32,
	overrideDevicePolicy bool,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(overrideDevicePolicy)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerRemoveUserWhenPossible, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) MarkGuestForDeletion(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerMarkGuestForDeletion, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetGuestUsers(
	ctx context.Context,
) ([]interface{}, error) {
	var _result []interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetGuestUsers, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]interface{}, _count)
		for _i := int32(0); _i < _count; _i++ {
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) IsQuietModeEnabled(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsQuietModeEnabled, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CreateUserWithAttributes(
	ctx context.Context,
	userName string,
	userType string,
	flags int32,
	userIcon graphics.Bitmap,
	accountName string,
	accountType string,
	accountOptions interface{},
) (UserHandle, error) {
	var _result UserHandle
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(userName)
	_data.WriteString16(userType)
	_data.WriteInt32(flags)
	if _err := userIcon.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteString16(accountName)
	_data.WriteString16(accountType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCreateUserWithAttributes, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	if _err = _result.UnmarshalParcel(_reply); _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetSeedAccountData(
	ctx context.Context,
	userId int32,
	accountName string,
	accountType string,
	accountOptions interface{},
	persist bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteString16(accountName)
	_data.WriteString16(accountType)
	_data.WriteBool(persist)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetSeedAccountData, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetSeedAccountName(
	ctx context.Context,
	userId int32,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetSeedAccountName, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetSeedAccountType(
	ctx context.Context,
	userId int32,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetSeedAccountType, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetSeedAccountOptions(
	ctx context.Context,
	userId int32,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetSeedAccountOptions, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) ClearSeedAccountData(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerClearSeedAccountData, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) SomeUserHasSeedAccount(
	ctx context.Context,
	accountName string,
	accountType string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(accountName)
	_data.WriteString16(accountType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSomeUserHasSeedAccount, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SomeUserHasAccount(
	ctx context.Context,
	accountName string,
	accountType string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(accountName)
	_data.WriteString16(accountType)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSomeUserHasAccount, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileType(
	ctx context.Context,
	userId int32,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileType, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsDemoUser(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsDemoUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsAdminUser(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsAdminUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsPreCreated(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsPreCreated, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) CreateProfileForUserEvenWhenDisallowedWithThrow(
	ctx context.Context,
	name string,
	userType string,
	flags int32,
	userId int32,
	disallowedPackages []string,
) (interface{}, error) {
	var _result interface{}
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(name)
	_data.WriteString16(userType)
	_data.WriteInt32(flags)
	_data.WriteInt32(userId)
	if disallowedPackages == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(disallowedPackages)))
		for _, _item := range disallowedPackages {
			_data.WriteString16(_item)
		}
	}

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerCreateProfileForUserEvenWhenDisallowedWithThrow, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *UserManagerProxy) IsUserUnlockingOrUnlocked(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserUnlockingOrUnlocked, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserIconBadgeResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserIconBadgeResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserBadgeResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserBadgeResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserBadgeNoBackgroundResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserBadgeNoBackgroundResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserBadgeLabelResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserBadgeLabelResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserBadgeColorResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserBadgeColorResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserBadgeDarkColorResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserBadgeDarkColorResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserStatusBarIconResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserStatusBarIconResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) HasBadge(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerHasBadge, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileLabelResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileLabelResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileAccessibilityLabelResId(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileAccessibilityLabelResId, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserUnlocked(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserUnlocked, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserRunning(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserRunning, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserForeground(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserForeground, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserVisible(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserVisible, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetVisibleUsers(
	ctx context.Context,
) ([]int32, error) {
	var _result []int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetVisibleUsers, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]int32, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadInt32()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *UserManagerProxy) GetMainDisplayIdAssignedToUser(
	ctx context.Context,
	userId int32,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetMainDisplayIdAssignedToUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsForegroundUserAdmin(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsForegroundUserAdmin, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) IsUserNameSet(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerIsUserNameSet, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) HasRestrictedProfiles(
	ctx context.Context,
	userId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerHasRestrictedProfiles, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) RequestQuietModeEnabled(
	ctx context.Context,
	callingPackage string,
	enableQuietMode bool,
	userId int32,
	target interface{},
	flags int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteString16(callingPackage)
	_data.WriteBool(enableQuietMode)
	_data.WriteInt32(userId)
	_data.WriteInt32(flags)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerRequestQuietModeEnabled, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserName(
	ctx context.Context,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserName, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserStartRealtime(
	ctx context.Context,
) (int64, error) {
	var _result int64
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserStartRealtime, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetUserUnlockRealtime(
	ctx context.Context,
) (int64, error) {
	var _result int64
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetUserUnlockRealtime, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetUserEphemeral(
	ctx context.Context,
	userId int32,
	enableEphemeral bool,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(enableEphemeral)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetUserEphemeral, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) SetBootUser(
	ctx context.Context,
	userId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerSetBootUser, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *UserManagerProxy) GetBootUser(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetBootUser, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *UserManagerProxy) GetProfileIdsExcludingHidden(
	ctx context.Context,
	userId int32,
	enabledOnly bool,
) ([]int32, error) {
	var _result []int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIUserManager)
	_data.WriteInt32(userId)
	_data.WriteBool(enabledOnly)

	_reply, _err := p.remote.Transact(ctx, TransactionIUserManagerGetProfileIdsExcludingHidden, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]int32, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadInt32()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}
