package os

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIVibratorStateListener = "android.os.IVibratorStateListener"

const (
	TransactionIVibratorStateListenerOnVibrating = binder.FirstCallTransaction + 0
)

type IVibratorStateListener interface {
	AsBinder() binder.IBinder
	OnVibrating(ctx context.Context, vibrating bool) error
}

type VibratorStateListenerProxy struct {
	remote binder.IBinder
}

func NewVibratorStateListenerProxy(
	remote binder.IBinder,
) *VibratorStateListenerProxy {
	return &VibratorStateListenerProxy{remote: remote}
}

func (p *VibratorStateListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IVibratorStateListener = (*VibratorStateListenerProxy)(nil)

func (p *VibratorStateListenerProxy) OnVibrating(
	ctx context.Context,
	vibrating bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIVibratorStateListener)
	_data.WriteBool(vibrating)

	_code, _err := p.remote.ResolveCode(DescriptorIVibratorStateListener, "onVibrating")
	if _err != nil {
		_code = TransactionIVibratorStateListenerOnVibrating
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// VibratorStateListenerStub dispatches incoming binder transactions
// to a typed IVibratorStateListener implementation.
type VibratorStateListenerStub struct {
	Impl IVibratorStateListener
}

var _ binder.TransactionReceiver = (*VibratorStateListenerStub)(nil)

func (s *VibratorStateListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIVibratorStateListenerOnVibrating:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_vibrating, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnVibrating(ctx, _arg_vibrating)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
