// Code generated by genparcelgo. DO NOT EDIT.

package os

import (
	"github.com/xaionaro-go/binder/parcel"
)

type ParcelableException struct {
	// T.getClass().getName(): opaque type — not yet supported
	// T.getMessage(): opaque type — not yet supported
}

var _ parcel.Parcelable = (*ParcelableException)(nil)

func (s *ParcelableException) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *ParcelableException) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
