// Code generated by genparcelgo. DO NOT EDIT.

package os

import (
	"github.com/xaionaro-go/binder/parcel"
)

type WorkSource struct {
	Num int32
	// Uids: opaque type — not yet supported
	// Names: opaque type — not yet supported
	// -1: opaque type — not yet supported
}

var _ parcel.Parcelable = (*WorkSource)(nil)

func (s *WorkSource) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Num)
	return nil
}

func (s *WorkSource) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Num, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
