package aics

// Code generated by aidlgen. DO NOT EDIT.

type GainMode byte

const (
	GainModeManualOnly    GainMode = 0
	GainModeAutomaticOnly GainMode = 1
	GainModeMANUAL        GainMode = 2
	GainModeAUTOMATIC     GainMode = 3
)
