package secure_element

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorISecureElementCallback = "android.hardware.secure_element.ISecureElementCallback"

const (
	TransactionISecureElementCallbackOnStateChange = binder.FirstCallTransaction + 0
)

type ISecureElementCallback interface {
	AsBinder() binder.IBinder
	OnStateChange(ctx context.Context, connected bool, debugReason string) error
}

type SecureElementCallbackProxy struct {
	remote binder.IBinder
}

func NewSecureElementCallbackProxy(
	remote binder.IBinder,
) *SecureElementCallbackProxy {
	return &SecureElementCallbackProxy{remote: remote}
}

func (p *SecureElementCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ISecureElementCallback = (*SecureElementCallbackProxy)(nil)

func (p *SecureElementCallbackProxy) OnStateChange(
	ctx context.Context,
	connected bool,
	debugReason string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorISecureElementCallback)
	_data.WriteBool(connected)
	_data.WriteString16(debugReason)

	_code, _err := p.remote.ResolveCode(DescriptorISecureElementCallback, "onStateChange")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// SecureElementCallbackStub dispatches incoming binder transactions
// to a typed ISecureElementCallback implementation.
type SecureElementCallbackStub struct {
	Impl ISecureElementCallback
}

var _ binder.TransactionReceiver = (*SecureElementCallbackStub)(nil)

func (s *SecureElementCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionISecureElementCallbackOnStateChange:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_connected, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_debugReason, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnStateChange(ctx, _arg_connected, _arg_debugReason)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
