// Code generated by genparcelgo. DO NOT EDIT.

package time

import (
	"github.com/xaionaro-go/binder/parcel"
)

type TimeConfiguration struct {
	// Bundle: opaque type — not yet supported
}

var _ parcel.Parcelable = (*TimeConfiguration)(nil)

func (s *TimeConfiguration) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *TimeConfiguration) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
