package impl

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PhysicalCaptureResultInfo struct {
	CameraId       string
	CameraMetadata CameraMetadataNative
}

var _ parcel.Parcelable = (*PhysicalCaptureResultInfo)(nil)

func (s *PhysicalCaptureResultInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString16(s.CameraId)
	if _err := s.CameraMetadata.MarshalParcel(p); _err != nil {
		return _err
	}
	return nil
}

func (s *PhysicalCaptureResultInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.CameraId, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	if _err := s.CameraMetadata.UnmarshalParcel(p); _err != nil {
		return _err
	}
	return nil
}
