package audio

// Code generated by aidlgen. DO NOT EDIT.

type AacObjectType byte

const (
	AacObjectTypeMpeg2Lc       AacObjectType = 0
	AacObjectTypeMpeg4Lc       AacObjectType = 1
	AacObjectTypeMpeg4Ltp      AacObjectType = 2
	AacObjectTypeMpeg4Scalable AacObjectType = 3
)
