package content

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorISyncStatusObserver = "android.content.ISyncStatusObserver"

const (
	TransactionISyncStatusObserverOnStatusChanged = binder.FirstCallTransaction + 0
)

type ISyncStatusObserver interface {
	AsBinder() binder.IBinder
	OnStatusChanged(ctx context.Context, which int32) error
}

type SyncStatusObserverProxy struct {
	remote binder.IBinder
}

func NewSyncStatusObserverProxy(
	remote binder.IBinder,
) *SyncStatusObserverProxy {
	return &SyncStatusObserverProxy{remote: remote}
}

func (p *SyncStatusObserverProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ISyncStatusObserver = (*SyncStatusObserverProxy)(nil)

func (p *SyncStatusObserverProxy) OnStatusChanged(
	ctx context.Context,
	which int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorISyncStatusObserver)
	_data.WriteInt32(which)

	_code, _err := p.remote.ResolveCode(DescriptorISyncStatusObserver, "onStatusChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// SyncStatusObserverStub dispatches incoming binder transactions
// to a typed ISyncStatusObserver implementation.
type SyncStatusObserverStub struct {
	Impl ISyncStatusObserver
}

var _ binder.TransactionReceiver = (*SyncStatusObserverStub)(nil)

func (s *SyncStatusObserverStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionISyncStatusObserverOnStatusChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_which, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnStatusChanged(ctx, _arg_which)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
