package content

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SyncRequest struct {
	SyncFlexTimeSecs int64
	SyncRunTimeSecs  int64
	Authority        string
}

var _ parcel.Parcelable = (*SyncRequest)(nil)

func (s *SyncRequest) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt64(s.SyncFlexTimeSecs)
	p.WriteInt64(s.SyncRunTimeSecs)
	p.WriteString16(s.Authority)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *SyncRequest) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.SyncFlexTimeSecs, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.SyncRunTimeSecs, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Authority, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
