package content

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SyncResult struct {
	DelayUntil int64
}

var _ parcel.Parcelable = (*SyncResult)(nil)

func (s *SyncResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt64(s.DelayUntil)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *SyncResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.DelayUntil, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
