package vehicle

// Code generated by aidlgen. DO NOT EDIT.

type CustomInputType int32

const (
	CustomInputTypeCustomEventF1  CustomInputType = 1001
	CustomInputTypeCustomEventF2  CustomInputType = 1002
	CustomInputTypeCustomEventF3  CustomInputType = 1003
	CustomInputTypeCustomEventF4  CustomInputType = 1004
	CustomInputTypeCustomEventF5  CustomInputType = 1005
	CustomInputTypeCustomEventF6  CustomInputType = 1006
	CustomInputTypeCustomEventF7  CustomInputType = 1007
	CustomInputTypeCustomEventF8  CustomInputType = 1008
	CustomInputTypeCustomEventF9  CustomInputType = 1009
	CustomInputTypeCustomEventF10 CustomInputType = 1010
)
