package vehicle

// Code generated by aidlgen. DO NOT EDIT.

type LowSpeedAutomaticEmergencyBrakingState int32

const (
	LowSpeedAutomaticEmergencyBrakingStateOTHER        LowSpeedAutomaticEmergencyBrakingState = 0
	LowSpeedAutomaticEmergencyBrakingStateENABLED      LowSpeedAutomaticEmergencyBrakingState = 1
	LowSpeedAutomaticEmergencyBrakingStateACTIVATED    LowSpeedAutomaticEmergencyBrakingState = 2
	LowSpeedAutomaticEmergencyBrakingStateUserOverride LowSpeedAutomaticEmergencyBrakingState = 3
)
