package vehicle

// Code generated by aidlgen. DO NOT EDIT.

type VehicleIgnitionState int32

const (
	VehicleIgnitionStateUNDEFINED VehicleIgnitionState = 0
	VehicleIgnitionStateLOCK      VehicleIgnitionState = 1
	VehicleIgnitionStateOFF       VehicleIgnitionState = 2
	VehicleIgnitionStateACC       VehicleIgnitionState = 3
	VehicleIgnitionStateON        VehicleIgnitionState = 4
	VehicleIgnitionStateSTART     VehicleIgnitionState = 5
)
