package vehicle

// Code generated by aidlgen. DO NOT EDIT.

type VehicleHwMotionButtonStateFlag int32

const (
	VehicleHwMotionButtonStateFlagButtonPrimary         VehicleHwMotionButtonStateFlag = 1
	VehicleHwMotionButtonStateFlagButtonSecondary       VehicleHwMotionButtonStateFlag = 2
	VehicleHwMotionButtonStateFlagButtonTertiary        VehicleHwMotionButtonStateFlag = 4
	VehicleHwMotionButtonStateFlagButtonBack            VehicleHwMotionButtonStateFlag = 8
	VehicleHwMotionButtonStateFlagButtonForward         VehicleHwMotionButtonStateFlag = 16
	VehicleHwMotionButtonStateFlagButtonStylusPrimary   VehicleHwMotionButtonStateFlag = 32
	VehicleHwMotionButtonStateFlagButtonStylusSecondary VehicleHwMotionButtonStateFlag = 64
)
