package vehicle

// Code generated by aidlgen. DO NOT EDIT.

type VehiclePropertyAccess int32

const (
	VehiclePropertyAccessNONE      VehiclePropertyAccess = 0
	VehiclePropertyAccessREAD      VehiclePropertyAccess = 1
	VehiclePropertyAccessWRITE     VehiclePropertyAccess = 2
	VehiclePropertyAccessReadWrite VehiclePropertyAccess = 3
)
