package network

// Code generated by aidlgen. DO NOT EDIT.

type CellConnectionStatus int32

const (
	CellConnectionStatusNONE             CellConnectionStatus = 0
	CellConnectionStatusPrimaryServing   CellConnectionStatus = 1
	CellConnectionStatusSecondaryServing CellConnectionStatus = 2
)
