package network

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type EutranRegistrationInfo struct {
	LteVopsInfo         LteVopsInfo
	NrIndicators        NrIndicators
	LteAttachResultType EutranRegistrationInfoAttachResultType
	ExtraInfo           int32
}

const (
	EutranRegistrationInfoExtraCsfbNotPreferred int32 = (1 << 0)
	EutranRegistrationInfoExtraSmsOnly          int32 = (1 << 1)
)

var _ parcel.Parcelable = (*EutranRegistrationInfo)(nil)

func (s *EutranRegistrationInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(1) // non-null indicator
	if _err := s.LteVopsInfo.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteInt32(1) // non-null indicator
	if _err := s.NrIndicators.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteInt32(int32(s.LteAttachResultType))
	p.WriteInt32(s.ExtraInfo)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *EutranRegistrationInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.LteVopsInfo.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.NrIndicators.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	_lteAttachResultTypeRaw, _err := p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.LteAttachResultType = EutranRegistrationInfoAttachResultType(_lteAttachResultTypeRaw)

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.ExtraInfo, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
