package network

import (
	"context"
	radio "github.com/xaionaro-go/aidl/android/hardware/radio"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIRadioNetworkResponse = "android.hardware.radio.network.IRadioNetworkResponse"

const (
	TransactionIRadioNetworkResponseAcknowledgeRequest                               = binder.FirstCallTransaction + 0
	TransactionIRadioNetworkResponseGetAllowedNetworkTypesBitmapResponse             = binder.FirstCallTransaction + 1
	TransactionIRadioNetworkResponseGetAvailableBandModesResponse                    = binder.FirstCallTransaction + 2
	TransactionIRadioNetworkResponseGetAvailableNetworksResponse                     = binder.FirstCallTransaction + 3
	TransactionIRadioNetworkResponseGetBarringInfoResponse                           = binder.FirstCallTransaction + 4
	TransactionIRadioNetworkResponseGetCdmaRoamingPreferenceResponse                 = binder.FirstCallTransaction + 5
	TransactionIRadioNetworkResponseGetCellInfoListResponse                          = binder.FirstCallTransaction + 6
	TransactionIRadioNetworkResponseGetDataRegistrationStateResponse                 = binder.FirstCallTransaction + 7
	TransactionIRadioNetworkResponseGetImsRegistrationStateResponse                  = binder.FirstCallTransaction + 8
	TransactionIRadioNetworkResponseGetNetworkSelectionModeResponse                  = binder.FirstCallTransaction + 9
	TransactionIRadioNetworkResponseGetOperatorResponse                              = binder.FirstCallTransaction + 10
	TransactionIRadioNetworkResponseGetSignalStrengthResponse                        = binder.FirstCallTransaction + 11
	TransactionIRadioNetworkResponseGetSystemSelectionChannelsResponse               = binder.FirstCallTransaction + 12
	TransactionIRadioNetworkResponseGetVoiceRadioTechnologyResponse                  = binder.FirstCallTransaction + 13
	TransactionIRadioNetworkResponseGetVoiceRegistrationStateResponse                = binder.FirstCallTransaction + 14
	TransactionIRadioNetworkResponseIsNrDualConnectivityEnabledResponse              = binder.FirstCallTransaction + 15
	TransactionIRadioNetworkResponseSetAllowedNetworkTypesBitmapResponse             = binder.FirstCallTransaction + 16
	TransactionIRadioNetworkResponseSetBandModeResponse                              = binder.FirstCallTransaction + 17
	TransactionIRadioNetworkResponseSetBarringPasswordResponse                       = binder.FirstCallTransaction + 18
	TransactionIRadioNetworkResponseSetCdmaRoamingPreferenceResponse                 = binder.FirstCallTransaction + 19
	TransactionIRadioNetworkResponseSetCellInfoListRateResponse                      = binder.FirstCallTransaction + 20
	TransactionIRadioNetworkResponseSetIndicationFilterResponse                      = binder.FirstCallTransaction + 21
	TransactionIRadioNetworkResponseSetLinkCapacityReportingCriteriaResponse         = binder.FirstCallTransaction + 22
	TransactionIRadioNetworkResponseSetLocationUpdatesResponse                       = binder.FirstCallTransaction + 23
	TransactionIRadioNetworkResponseSetNetworkSelectionModeAutomaticResponse         = binder.FirstCallTransaction + 24
	TransactionIRadioNetworkResponseSetNetworkSelectionModeManualResponse            = binder.FirstCallTransaction + 25
	TransactionIRadioNetworkResponseSetNrDualConnectivityStateResponse               = binder.FirstCallTransaction + 26
	TransactionIRadioNetworkResponseSetSignalStrengthReportingCriteriaResponse       = binder.FirstCallTransaction + 27
	TransactionIRadioNetworkResponseSetSuppServiceNotificationsResponse              = binder.FirstCallTransaction + 28
	TransactionIRadioNetworkResponseSetSystemSelectionChannelsResponse               = binder.FirstCallTransaction + 29
	TransactionIRadioNetworkResponseStartNetworkScanResponse                         = binder.FirstCallTransaction + 30
	TransactionIRadioNetworkResponseStopNetworkScanResponse                          = binder.FirstCallTransaction + 31
	TransactionIRadioNetworkResponseSupplyNetworkDepersonalizationResponse           = binder.FirstCallTransaction + 32
	TransactionIRadioNetworkResponseSetUsageSettingResponse                          = binder.FirstCallTransaction + 33
	TransactionIRadioNetworkResponseGetUsageSettingResponse                          = binder.FirstCallTransaction + 34
	TransactionIRadioNetworkResponseSetEmergencyModeResponse                         = binder.FirstCallTransaction + 35
	TransactionIRadioNetworkResponseTriggerEmergencyNetworkScanResponse              = binder.FirstCallTransaction + 36
	TransactionIRadioNetworkResponseExitEmergencyModeResponse                        = binder.FirstCallTransaction + 37
	TransactionIRadioNetworkResponseCancelEmergencyNetworkScanResponse               = binder.FirstCallTransaction + 38
	TransactionIRadioNetworkResponseSetNullCipherAndIntegrityEnabledResponse         = binder.FirstCallTransaction + 39
	TransactionIRadioNetworkResponseIsNullCipherAndIntegrityEnabledResponse          = binder.FirstCallTransaction + 40
	TransactionIRadioNetworkResponseIsN1ModeEnabledResponse                          = binder.FirstCallTransaction + 41
	TransactionIRadioNetworkResponseSetN1ModeEnabledResponse                         = binder.FirstCallTransaction + 42
	TransactionIRadioNetworkResponseIsCellularIdentifierTransparencyEnabledResponse  = binder.FirstCallTransaction + 43
	TransactionIRadioNetworkResponseSetCellularIdentifierTransparencyEnabledResponse = binder.FirstCallTransaction + 44
	TransactionIRadioNetworkResponseSetSecurityAlgorithmsUpdatedEnabledResponse      = binder.FirstCallTransaction + 45
	TransactionIRadioNetworkResponseIsSecurityAlgorithmsUpdatedEnabledResponse       = binder.FirstCallTransaction + 46
	TransactionIRadioNetworkResponseSetSatellitePlmnResponse                         = binder.FirstCallTransaction + 47
	TransactionIRadioNetworkResponseSetSatelliteEnabledForCarrierResponse            = binder.FirstCallTransaction + 48
	TransactionIRadioNetworkResponseIsSatelliteEnabledForCarrierResponse             = binder.FirstCallTransaction + 49
)

type IRadioNetworkResponse interface {
	AsBinder() binder.IBinder
	AcknowledgeRequest(ctx context.Context, serial int32) error
	GetAllowedNetworkTypesBitmapResponse(ctx context.Context, info radio.RadioResponseInfo, networkTypeBitmap int32) error
	GetAvailableBandModesResponse(ctx context.Context, info radio.RadioResponseInfo, bandModes []RadioBandMode) error
	GetAvailableNetworksResponse(ctx context.Context, info radio.RadioResponseInfo, networkInfos []OperatorInfo) error
	GetBarringInfoResponse(ctx context.Context, info radio.RadioResponseInfo, cellIdentity CellIdentity, barringInfos []BarringInfo) error
	GetCdmaRoamingPreferenceResponse(ctx context.Context, info radio.RadioResponseInfo, type_ CdmaRoamingType) error
	GetCellInfoListResponse(ctx context.Context, info radio.RadioResponseInfo, cellInfo []CellInfo) error
	GetDataRegistrationStateResponse(ctx context.Context, info radio.RadioResponseInfo, dataRegResponse RegStateResult) error
	GetImsRegistrationStateResponse(ctx context.Context, info radio.RadioResponseInfo, isRegistered bool, ratFamily radio.RadioTechnologyFamily) error
	GetNetworkSelectionModeResponse(ctx context.Context, info radio.RadioResponseInfo, manual bool) error
	GetOperatorResponse(ctx context.Context, info radio.RadioResponseInfo, longName string, shortName string, numeric string) error
	GetSignalStrengthResponse(ctx context.Context, info radio.RadioResponseInfo, signalStrength SignalStrength) error
	GetSystemSelectionChannelsResponse(ctx context.Context, info radio.RadioResponseInfo, specifiers []RadioAccessSpecifier) error
	GetVoiceRadioTechnologyResponse(ctx context.Context, info radio.RadioResponseInfo, rat radio.RadioTechnology) error
	GetVoiceRegistrationStateResponse(ctx context.Context, info radio.RadioResponseInfo, voiceRegResponse RegStateResult) error
	IsNrDualConnectivityEnabledResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
	SetAllowedNetworkTypesBitmapResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetBandModeResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetBarringPasswordResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetCdmaRoamingPreferenceResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetCellInfoListRateResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetIndicationFilterResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetLinkCapacityReportingCriteriaResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetLocationUpdatesResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetNetworkSelectionModeAutomaticResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetNetworkSelectionModeManualResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetNrDualConnectivityStateResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetSignalStrengthReportingCriteriaResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetSuppServiceNotificationsResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetSystemSelectionChannelsResponse(ctx context.Context, info radio.RadioResponseInfo) error
	StartNetworkScanResponse(ctx context.Context, info radio.RadioResponseInfo) error
	StopNetworkScanResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SupplyNetworkDepersonalizationResponse(ctx context.Context, info radio.RadioResponseInfo, remainingRetries int32) error
	SetUsageSettingResponse(ctx context.Context, info radio.RadioResponseInfo) error
	GetUsageSettingResponse(ctx context.Context, info radio.RadioResponseInfo, usageSetting UsageSetting) error
	SetEmergencyModeResponse(ctx context.Context, info radio.RadioResponseInfo, regState EmergencyRegResult) error
	TriggerEmergencyNetworkScanResponse(ctx context.Context, info radio.RadioResponseInfo) error
	ExitEmergencyModeResponse(ctx context.Context, info radio.RadioResponseInfo) error
	CancelEmergencyNetworkScanResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetNullCipherAndIntegrityEnabledResponse(ctx context.Context, info radio.RadioResponseInfo) error
	IsNullCipherAndIntegrityEnabledResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
	IsN1ModeEnabledResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
	SetN1ModeEnabledResponse(ctx context.Context, info radio.RadioResponseInfo) error
	IsCellularIdentifierTransparencyEnabledResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
	SetCellularIdentifierTransparencyEnabledResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetSecurityAlgorithmsUpdatedEnabledResponse(ctx context.Context, info radio.RadioResponseInfo) error
	IsSecurityAlgorithmsUpdatedEnabledResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
	SetSatellitePlmnResponse(ctx context.Context, info radio.RadioResponseInfo) error
	SetSatelliteEnabledForCarrierResponse(ctx context.Context, info radio.RadioResponseInfo) error
	IsSatelliteEnabledForCarrierResponse(ctx context.Context, info radio.RadioResponseInfo, isEnabled bool) error
}

type RadioNetworkResponseProxy struct {
	remote binder.IBinder
}

func NewRadioNetworkResponseProxy(
	remote binder.IBinder,
) *RadioNetworkResponseProxy {
	return &RadioNetworkResponseProxy{remote: remote}
}

func (p *RadioNetworkResponseProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IRadioNetworkResponse = (*RadioNetworkResponseProxy)(nil)

func (p *RadioNetworkResponseProxy) AcknowledgeRequest(
	ctx context.Context,
	serial int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	_data.WriteInt32(serial)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseAcknowledgeRequest, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetAllowedNetworkTypesBitmapResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	networkTypeBitmap int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(networkTypeBitmap)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetAllowedNetworkTypesBitmapResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetAvailableBandModesResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	bandModes []RadioBandMode,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if bandModes == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(bandModes)))
		for _, _item := range bandModes {
			_data.WriteInt32(int32(_item))
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetAvailableBandModesResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetAvailableNetworksResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	networkInfos []OperatorInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if networkInfos == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(networkInfos)))
		for _, _item := range networkInfos {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetAvailableNetworksResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetBarringInfoResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	cellIdentity CellIdentity,
	barringInfos []BarringInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if _err := cellIdentity.MarshalParcel(_data); _err != nil {
		return _err
	}
	if barringInfos == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(barringInfos)))
		for _, _item := range barringInfos {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetBarringInfoResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetCdmaRoamingPreferenceResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	type_ CdmaRoamingType,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(int32(type_))

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetCdmaRoamingPreferenceResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetCellInfoListResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	cellInfo []CellInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if cellInfo == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(cellInfo)))
		for _, _item := range cellInfo {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetCellInfoListResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetDataRegistrationStateResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	dataRegResponse RegStateResult,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if _err := dataRegResponse.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetDataRegistrationStateResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetImsRegistrationStateResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isRegistered bool,
	ratFamily radio.RadioTechnologyFamily,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isRegistered)
	_data.WriteInt32(int32(ratFamily))

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetImsRegistrationStateResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetNetworkSelectionModeResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	manual bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(manual)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetNetworkSelectionModeResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetOperatorResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	longName string,
	shortName string,
	numeric string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(longName)
	_data.WriteString16(shortName)
	_data.WriteString16(numeric)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetOperatorResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetSignalStrengthResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	signalStrength SignalStrength,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if _err := signalStrength.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetSignalStrengthResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetSystemSelectionChannelsResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	specifiers []RadioAccessSpecifier,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if specifiers == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(specifiers)))
		for _, _item := range specifiers {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetSystemSelectionChannelsResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetVoiceRadioTechnologyResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	rat radio.RadioTechnology,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(int32(rat))

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetVoiceRadioTechnologyResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetVoiceRegistrationStateResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	voiceRegResponse RegStateResult,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if _err := voiceRegResponse.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetVoiceRegistrationStateResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsNrDualConnectivityEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsNrDualConnectivityEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetAllowedNetworkTypesBitmapResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetAllowedNetworkTypesBitmapResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetBandModeResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetBandModeResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetBarringPasswordResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetBarringPasswordResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetCdmaRoamingPreferenceResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetCdmaRoamingPreferenceResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetCellInfoListRateResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetCellInfoListRateResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetIndicationFilterResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetIndicationFilterResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetLinkCapacityReportingCriteriaResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetLinkCapacityReportingCriteriaResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetLocationUpdatesResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetLocationUpdatesResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetNetworkSelectionModeAutomaticResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetNetworkSelectionModeAutomaticResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetNetworkSelectionModeManualResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetNetworkSelectionModeManualResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetNrDualConnectivityStateResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetNrDualConnectivityStateResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSignalStrengthReportingCriteriaResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSignalStrengthReportingCriteriaResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSuppServiceNotificationsResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSuppServiceNotificationsResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSystemSelectionChannelsResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSystemSelectionChannelsResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) StartNetworkScanResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseStartNetworkScanResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) StopNetworkScanResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseStopNetworkScanResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SupplyNetworkDepersonalizationResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	remainingRetries int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(remainingRetries)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSupplyNetworkDepersonalizationResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetUsageSettingResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetUsageSettingResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) GetUsageSettingResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	usageSetting UsageSetting,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(int32(usageSetting))

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseGetUsageSettingResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetEmergencyModeResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	regState EmergencyRegResult,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	if _err := regState.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetEmergencyModeResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) TriggerEmergencyNetworkScanResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseTriggerEmergencyNetworkScanResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) ExitEmergencyModeResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseExitEmergencyModeResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) CancelEmergencyNetworkScanResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseCancelEmergencyNetworkScanResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetNullCipherAndIntegrityEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetNullCipherAndIntegrityEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsNullCipherAndIntegrityEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsNullCipherAndIntegrityEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsN1ModeEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsN1ModeEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetN1ModeEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetN1ModeEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsCellularIdentifierTransparencyEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsCellularIdentifierTransparencyEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetCellularIdentifierTransparencyEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetCellularIdentifierTransparencyEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSecurityAlgorithmsUpdatedEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSecurityAlgorithmsUpdatedEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsSecurityAlgorithmsUpdatedEnabledResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsSecurityAlgorithmsUpdatedEnabledResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSatellitePlmnResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSatellitePlmnResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) SetSatelliteEnabledForCarrierResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseSetSatelliteEnabledForCarrierResponse, binder.FlagOneway, _data)
	return _err
}

func (p *RadioNetworkResponseProxy) IsSatelliteEnabledForCarrierResponse(
	ctx context.Context,
	info radio.RadioResponseInfo,
	isEnabled bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRadioNetworkResponse)
	if _err := info.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isEnabled)

	_, _err := p.remote.Transact(ctx, TransactionIRadioNetworkResponseIsSatelliteEnabledForCarrierResponse, binder.FlagOneway, _data)
	return _err
}
