package hardware

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type CameraPrivacyAllowlistEntry struct {
	PackageName string
	IsMandatory bool
}

var _ parcel.Parcelable = (*CameraPrivacyAllowlistEntry)(nil)

func (s *CameraPrivacyAllowlistEntry) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteString16(s.PackageName)
	p.WriteBool(s.IsMandatory)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *CameraPrivacyAllowlistEntry) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	s.IsMandatory, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
