// Code generated by spec2go. DO NOT EDIT.

package hardware

import (
	"context"
	"fmt"

	"github.com/AndroidGoLab/binder/servicemanager"
)

// GetSerialManager retrieves the SerialService service and returns a typed proxy.
func GetSerialManager(
	ctx context.Context,
	sm *servicemanager.ServiceManager,
) (*SerialManagerProxy, error) {
	svc, err := sm.GetService(ctx, servicemanager.SerialService)
	if err != nil {
		return nil, fmt.Errorf("GetSerialManager: %w", err)
	}
	return NewSerialManagerProxy(svc), nil
}
