package neuralnetworks

// Code generated by aidlgen. DO NOT EDIT.

type ExecutionPreference int32

const (
	ExecutionPreferenceLowPower         ExecutionPreference = 0
	ExecutionPreferenceFastSingleAnswer ExecutionPreference = 1
	ExecutionPreferenceSustainedSpeed   ExecutionPreference = 2
)
