package bluetooth

import (
	content "github.com/AndroidGoLab/binder/android/content"
	"github.com/AndroidGoLab/binder/binder"
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SystemServiceMessageDisable struct {
	AttributionSource content.AttributionSource
	BleToken          binder.IBinder
	Persist           bool
}

var _ parcel.Parcelable = (*SystemServiceMessageDisable)(nil)

func (s *SystemServiceMessageDisable) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(1) // non-null indicator
	if _err := s.AttributionSource.MarshalParcel(p); _err != nil {
		return _err
	}
	if s.BleToken == nil {
		p.WriteNullStrongBinder()
	} else {
		p.WriteStrongBinder(s.BleToken.Handle())
	}
	p.WriteBool(s.Persist)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *SystemServiceMessageDisable) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.AttributionSource.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	_bleTokenHandle, _err := p.ReadStrongBinder()
	if _err != nil {
		return _err
	}
	if _bleTokenHandle != 0 {
		s.BleToken = binder.NewProxyBinder(nil, binder.CallerIdentity{}, _bleTokenHandle)
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Persist, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
