package vibrator

// Code generated by aidlgen. DO NOT EDIT.

type Effect int32

const (
	EffectCLICK       Effect = 0
	EffectDoubleClick Effect = 1
	EffectTICK        Effect = 2
	EffectTHUD        Effect = 3
	EffectPOP         Effect = 4
	EffectHeavyClick  Effect = 5
	EffectRingtone1   Effect = 6
	EffectRingtone2   Effect = 7
	EffectRingtone3   Effect = 8
	EffectRingtone4   Effect = 9
	EffectRingtone5   Effect = 10
	EffectRingtone6   Effect = 11
	EffectRingtone7   Effect = 12
	EffectRingtone8   Effect = 13
	EffectRingtone9   Effect = 14
	EffectRingtone10  Effect = 15
	EffectRingtone11  Effect = 16
	EffectRingtone12  Effect = 17
	EffectRingtone13  Effect = 18
	EffectRingtone14  Effect = 19
	EffectRingtone15  Effect = 20
	EffectTextureTick Effect = 21
)
