package common

// Code generated by aidlgen. DO NOT EDIT.

type AudioStandard int32

const (
	AudioStandardNONE  AudioStandard = 0
	AudioStandardEDID  AudioStandard = 1
	AudioStandardSADB  AudioStandard = 2
	AudioStandardVSADB AudioStandard = 3
)
