package face

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type FaceEnrollOptions struct {
	EnrollReason int32
}

var _ parcel.Parcelable = (*FaceEnrollOptions)(nil)

func (s *FaceEnrollOptions) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.EnrollReason)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *FaceEnrollOptions) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.EnrollReason, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
