package nfc

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TransceiveResult struct {
}

var _ parcel.Parcelable = (*TransceiveResult)(nil)

func (s *TransceiveResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *TransceiveResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
