package bluetooth

import (
	"context"
	"fmt"
	content "github.com/xaionaro-go/binder/android/content"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBluetoothHapClient = "android.bluetooth.IBluetoothHapClient"

const (
	TransactionIBluetoothHapClientGetConnectedDevices                = binder.FirstCallTransaction + 0
	TransactionIBluetoothHapClientGetDevicesMatchingConnectionStates = binder.FirstCallTransaction + 1
	TransactionIBluetoothHapClientGetConnectionState                 = binder.FirstCallTransaction + 2
	TransactionIBluetoothHapClientSetConnectionPolicy                = binder.FirstCallTransaction + 3
	TransactionIBluetoothHapClientGetConnectionPolicy                = binder.FirstCallTransaction + 4
	TransactionIBluetoothHapClientGetHapGroup                        = binder.FirstCallTransaction + 5
	TransactionIBluetoothHapClientGetActivePresetIndex               = binder.FirstCallTransaction + 6
	TransactionIBluetoothHapClientGetActivePresetInfo                = binder.FirstCallTransaction + 7
	TransactionIBluetoothHapClientSelectPreset                       = binder.FirstCallTransaction + 8
	TransactionIBluetoothHapClientSelectPresetForGroup               = binder.FirstCallTransaction + 9
	TransactionIBluetoothHapClientSwitchToNextPreset                 = binder.FirstCallTransaction + 10
	TransactionIBluetoothHapClientSwitchToNextPresetForGroup         = binder.FirstCallTransaction + 11
	TransactionIBluetoothHapClientSwitchToPreviousPreset             = binder.FirstCallTransaction + 12
	TransactionIBluetoothHapClientSwitchToPreviousPresetForGroup     = binder.FirstCallTransaction + 13
	TransactionIBluetoothHapClientGetPresetInfo                      = binder.FirstCallTransaction + 14
	TransactionIBluetoothHapClientGetAllPresetInfo                   = binder.FirstCallTransaction + 15
	TransactionIBluetoothHapClientGetFeatures                        = binder.FirstCallTransaction + 16
	TransactionIBluetoothHapClientSetPresetName                      = binder.FirstCallTransaction + 17
	TransactionIBluetoothHapClientSetPresetNameForGroup              = binder.FirstCallTransaction + 18
	TransactionIBluetoothHapClientRegisterCallback                   = binder.FirstCallTransaction + 19
	TransactionIBluetoothHapClientUnregisterCallback                 = binder.FirstCallTransaction + 20
)

const (
	MethodIBluetoothHapClientGetConnectedDevices                = "getConnectedDevices"
	MethodIBluetoothHapClientGetDevicesMatchingConnectionStates = "getDevicesMatchingConnectionStates"
	MethodIBluetoothHapClientGetConnectionState                 = "getConnectionState"
	MethodIBluetoothHapClientSetConnectionPolicy                = "setConnectionPolicy"
	MethodIBluetoothHapClientGetConnectionPolicy                = "getConnectionPolicy"
	MethodIBluetoothHapClientGetHapGroup                        = "getHapGroup"
	MethodIBluetoothHapClientGetActivePresetIndex               = "getActivePresetIndex"
	MethodIBluetoothHapClientGetActivePresetInfo                = "getActivePresetInfo"
	MethodIBluetoothHapClientSelectPreset                       = "selectPreset"
	MethodIBluetoothHapClientSelectPresetForGroup               = "selectPresetForGroup"
	MethodIBluetoothHapClientSwitchToNextPreset                 = "switchToNextPreset"
	MethodIBluetoothHapClientSwitchToNextPresetForGroup         = "switchToNextPresetForGroup"
	MethodIBluetoothHapClientSwitchToPreviousPreset             = "switchToPreviousPreset"
	MethodIBluetoothHapClientSwitchToPreviousPresetForGroup     = "switchToPreviousPresetForGroup"
	MethodIBluetoothHapClientGetPresetInfo                      = "getPresetInfo"
	MethodIBluetoothHapClientGetAllPresetInfo                   = "getAllPresetInfo"
	MethodIBluetoothHapClientGetFeatures                        = "getFeatures"
	MethodIBluetoothHapClientSetPresetName                      = "setPresetName"
	MethodIBluetoothHapClientSetPresetNameForGroup              = "setPresetNameForGroup"
	MethodIBluetoothHapClientRegisterCallback                   = "registerCallback"
	MethodIBluetoothHapClientUnregisterCallback                 = "unregisterCallback"
)

type IBluetoothHapClient interface {
	AsBinder() binder.IBinder
	GetConnectedDevices(ctx context.Context, attributionSource content.AttributionSource, receiver interface{}) error
	GetDevicesMatchingConnectionStates(ctx context.Context, states []int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetConnectionState(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SetConnectionPolicy(ctx context.Context, device BluetoothDevice, connectionPolicy int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetConnectionPolicy(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetHapGroup(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetActivePresetIndex(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetActivePresetInfo(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SelectPreset(ctx context.Context, device BluetoothDevice, presetIndex int32, attributionSource content.AttributionSource) error
	SelectPresetForGroup(ctx context.Context, groupId int32, presetIndex int32, attributionSource content.AttributionSource) error
	SwitchToNextPreset(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) error
	SwitchToNextPresetForGroup(ctx context.Context, groupId int32, attributionSource content.AttributionSource) error
	SwitchToPreviousPreset(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) error
	SwitchToPreviousPresetForGroup(ctx context.Context, groupId int32, attributionSource content.AttributionSource) error
	GetPresetInfo(ctx context.Context, device BluetoothDevice, presetIndex int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetAllPresetInfo(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetFeatures(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SetPresetName(ctx context.Context, device BluetoothDevice, presetIndex int32, name string, attributionSource content.AttributionSource) error
	SetPresetNameForGroup(ctx context.Context, groupId int32, presetIndex int32, name string, attributionSource content.AttributionSource) error
	RegisterCallback(ctx context.Context, callback IBluetoothHapClientCallback, attributionSource content.AttributionSource, receiver interface{}) error
	UnregisterCallback(ctx context.Context, callback IBluetoothHapClientCallback, attributionSource content.AttributionSource, receiver interface{}) error
}

const (
	IBluetoothHapClientPresetIndexUnavailable             int32 = 0
	IBluetoothHapClientGroupIdUnavailable                 int32 = -1
	IBluetoothHapClientFeatureBitNumTypeMonaural          int32 = 0
	IBluetoothHapClientFeatureBitNumTypeBanded            int32 = 1
	IBluetoothHapClientFeatureBitNumSynchronizatedPresets int32 = 2
	IBluetoothHapClientFeatureBitNumIndependentPresets    int32 = 3
	IBluetoothHapClientFeatureBitNumDynamicPresets        int32 = 4
	IBluetoothHapClientFeatureBitNumWritablePresets       int32 = 5
)

type BluetoothHapClientProxy struct {
	Remote binder.IBinder
}

func NewBluetoothHapClientProxy(
	remote binder.IBinder,
) *BluetoothHapClientProxy {
	return &BluetoothHapClientProxy{Remote: remote}
}

func (p *BluetoothHapClientProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IBluetoothHapClient = (*BluetoothHapClientProxy)(nil)

func (p *BluetoothHapClientProxy) GetConnectedDevices(
	ctx context.Context,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectedDevices)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectedDevices, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetDevicesMatchingConnectionStates(
	ctx context.Context,
	states []int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	if states == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(states)))
		for _, _item := range states {
			_data.WriteInt32(_item)
		}
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetDevicesMatchingConnectionStates)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetDevicesMatchingConnectionStates, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetConnectionState(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectionState)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectionState, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	connectionPolicy int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(connectionPolicy)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetConnectionPolicy)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetConnectionPolicy, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectionPolicy)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetConnectionPolicy, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetHapGroup(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetHapGroup)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetHapGroup, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetActivePresetIndex(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetActivePresetIndex)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetActivePresetIndex, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetActivePresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetActivePresetInfo)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetActivePresetInfo, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SelectPreset(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(presetIndex)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSelectPreset)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSelectPreset, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SelectPresetForGroup(
	ctx context.Context,
	groupId int32,
	presetIndex int32,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(groupId)
	_data.WriteInt32(presetIndex)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSelectPresetForGroup)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSelectPresetForGroup, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SwitchToNextPreset(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToNextPreset)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToNextPreset, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SwitchToNextPresetForGroup(
	ctx context.Context,
	groupId int32,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(groupId)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToNextPresetForGroup)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToNextPresetForGroup, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SwitchToPreviousPreset(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToPreviousPreset)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToPreviousPreset, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SwitchToPreviousPresetForGroup(
	ctx context.Context,
	groupId int32,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(groupId)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToPreviousPresetForGroup)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSwitchToPreviousPresetForGroup, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetPresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(presetIndex)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetPresetInfo)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetPresetInfo, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetAllPresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetAllPresetInfo)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetAllPresetInfo, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) GetFeatures(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetFeatures)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientGetFeatures, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SetPresetName(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	name string,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(presetIndex)
	_data.WriteString16(name)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetPresetName)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetPresetName, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) SetPresetNameForGroup(
	ctx context.Context,
	groupId int32,
	presetIndex int32,
	name string,
	attributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	_data.WriteInt32(groupId)
	_data.WriteInt32(presetIndex)
	_data.WriteString16(name)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetPresetNameForGroup)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientSetPresetNameForGroup, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) RegisterCallback(
	ctx context.Context,
	callback IBluetoothHapClientCallback,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.Remote.Transport())
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientRegisterCallback)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientRegisterCallback, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BluetoothHapClientProxy) UnregisterCallback(
	ctx context.Context,
	callback IBluetoothHapClientCallback,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothHapClient)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.Remote.Transport())
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothHapClient, MethodIBluetoothHapClientUnregisterCallback)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothHapClient, MethodIBluetoothHapClientUnregisterCallback, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// BluetoothHapClientStub dispatches incoming binder transactions
// to a typed IBluetoothHapClient implementation.
type BluetoothHapClientStub struct {
	Impl IBluetoothHapClient
}

var _ binder.TransactionReceiver = (*BluetoothHapClientStub)(nil)

func (s *BluetoothHapClientStub) Descriptor() string {
	return DescriptorIBluetoothHapClient
}

func (s *BluetoothHapClientStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBluetoothHapClientGetConnectedDevices:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetConnectedDevices(ctx, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetDevicesMatchingConnectionStates:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_states []int32
		_ = _arg_states
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetDevicesMatchingConnectionStates(ctx, _arg_states, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetConnectionState:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetConnectionState(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSetConnectionPolicy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_connectionPolicy, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err = s.Impl.SetConnectionPolicy(ctx, _arg_device, _arg_connectionPolicy, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetConnectionPolicy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetConnectionPolicy(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetHapGroup:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetHapGroup(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetActivePresetIndex:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetActivePresetIndex(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetActivePresetInfo:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetActivePresetInfo(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSelectPreset:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_presetIndex, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SelectPreset(ctx, _arg_device, _arg_presetIndex, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSelectPresetForGroup:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_groupId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_presetIndex, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SelectPresetForGroup(ctx, _arg_groupId, _arg_presetIndex, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSwitchToNextPreset:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.SwitchToNextPreset(ctx, _arg_device, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSwitchToNextPresetForGroup:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_groupId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SwitchToNextPresetForGroup(ctx, _arg_groupId, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSwitchToPreviousPreset:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.SwitchToPreviousPreset(ctx, _arg_device, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSwitchToPreviousPresetForGroup:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_groupId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SwitchToPreviousPresetForGroup(ctx, _arg_groupId, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetPresetInfo:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_presetIndex, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err = s.Impl.GetPresetInfo(ctx, _arg_device, _arg_presetIndex, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetAllPresetInfo:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetAllPresetInfo(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientGetFeatures:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.GetFeatures(ctx, _arg_device, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSetPresetName:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_presetIndex, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_name, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SetPresetName(ctx, _arg_device, _arg_presetIndex, _arg_name, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientSetPresetNameForGroup:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_groupId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_presetIndex, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_name, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SetPresetNameForGroup(ctx, _arg_groupId, _arg_presetIndex, _arg_name, _arg_attributionSource)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientRegisterCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IBluetoothHapClientCallback
		_ = _arg_callback
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.RegisterCallback(ctx, _arg_callback, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	case TransactionIBluetoothHapClientUnregisterCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IBluetoothHapClientCallback
		_ = _arg_callback
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_receiver interface{}
		_err := s.Impl.UnregisterCallback(ctx, _arg_callback, _arg_attributionSource, _arg_receiver)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IBluetoothHapClientServer is the server-side interface that user implementations
// provide to NewBluetoothHapClientStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IBluetoothHapClientServer interface {
	GetConnectedDevices(ctx context.Context, attributionSource content.AttributionSource, receiver interface{}) error
	GetDevicesMatchingConnectionStates(ctx context.Context, states []int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetConnectionState(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SetConnectionPolicy(ctx context.Context, device BluetoothDevice, connectionPolicy int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetConnectionPolicy(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetHapGroup(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetActivePresetIndex(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetActivePresetInfo(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SelectPreset(ctx context.Context, device BluetoothDevice, presetIndex int32, attributionSource content.AttributionSource) error
	SelectPresetForGroup(ctx context.Context, groupId int32, presetIndex int32, attributionSource content.AttributionSource) error
	SwitchToNextPreset(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) error
	SwitchToNextPresetForGroup(ctx context.Context, groupId int32, attributionSource content.AttributionSource) error
	SwitchToPreviousPreset(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) error
	SwitchToPreviousPresetForGroup(ctx context.Context, groupId int32, attributionSource content.AttributionSource) error
	GetPresetInfo(ctx context.Context, device BluetoothDevice, presetIndex int32, attributionSource content.AttributionSource, receiver interface{}) error
	GetAllPresetInfo(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	GetFeatures(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource, receiver interface{}) error
	SetPresetName(ctx context.Context, device BluetoothDevice, presetIndex int32, name string, attributionSource content.AttributionSource) error
	SetPresetNameForGroup(ctx context.Context, groupId int32, presetIndex int32, name string, attributionSource content.AttributionSource) error
	RegisterCallback(ctx context.Context, callback IBluetoothHapClientCallback, attributionSource content.AttributionSource, receiver interface{}) error
	UnregisterCallback(ctx context.Context, callback IBluetoothHapClientCallback, attributionSource content.AttributionSource, receiver interface{}) error
}

type bluetoothHapClientStubWrapper struct {
	impl       IBluetoothHapClientServer
	stubBinder *binder.StubBinder
}

func (w *bluetoothHapClientStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *bluetoothHapClientStubWrapper) GetConnectedDevices(
	ctx context.Context,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetConnectedDevices(ctx, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetDevicesMatchingConnectionStates(
	ctx context.Context,
	states []int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetDevicesMatchingConnectionStates(ctx, states, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetConnectionState(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetConnectionState(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) SetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	connectionPolicy int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.SetConnectionPolicy(ctx, device, connectionPolicy, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetConnectionPolicy(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetHapGroup(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetHapGroup(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetActivePresetIndex(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetActivePresetIndex(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetActivePresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetActivePresetInfo(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) SelectPreset(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SelectPreset(ctx, device, presetIndex, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SelectPresetForGroup(
	ctx context.Context,
	groupId int32,
	presetIndex int32,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SelectPresetForGroup(ctx, groupId, presetIndex, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SwitchToNextPreset(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SwitchToNextPreset(ctx, device, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SwitchToNextPresetForGroup(
	ctx context.Context,
	groupId int32,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SwitchToNextPresetForGroup(ctx, groupId, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SwitchToPreviousPreset(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SwitchToPreviousPreset(ctx, device, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SwitchToPreviousPresetForGroup(
	ctx context.Context,
	groupId int32,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SwitchToPreviousPresetForGroup(ctx, groupId, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) GetPresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetPresetInfo(ctx, device, presetIndex, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetAllPresetInfo(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetAllPresetInfo(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) GetFeatures(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.GetFeatures(ctx, device, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) SetPresetName(
	ctx context.Context,
	device BluetoothDevice,
	presetIndex int32,
	name string,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SetPresetName(ctx, device, presetIndex, name, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) SetPresetNameForGroup(
	ctx context.Context,
	groupId int32,
	presetIndex int32,
	name string,
	attributionSource content.AttributionSource,
) error {
	return w.impl.SetPresetNameForGroup(ctx, groupId, presetIndex, name, attributionSource)
}

func (w *bluetoothHapClientStubWrapper) RegisterCallback(
	ctx context.Context,
	callback IBluetoothHapClientCallback,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.RegisterCallback(ctx, callback, attributionSource, receiver)
}

func (w *bluetoothHapClientStubWrapper) UnregisterCallback(
	ctx context.Context,
	callback IBluetoothHapClientCallback,
	attributionSource content.AttributionSource,
	receiver interface{},
) error {
	return w.impl.UnregisterCallback(ctx, callback, attributionSource, receiver)
}

var _ IBluetoothHapClient = (*bluetoothHapClientStubWrapper)(nil)

// NewBluetoothHapClientStub creates a server-side IBluetoothHapClient wrapping the given
// server implementation. The returned value satisfies IBluetoothHapClient
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewBluetoothHapClientStub(
	impl IBluetoothHapClientServer,
) IBluetoothHapClient {
	wrapper := &bluetoothHapClientStubWrapper{impl: impl}
	stub := &BluetoothHapClientStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
