package bluetooth

import (
	"context"
	"fmt"
	content "github.com/AndroidGoLab/binder/android/content"
	"github.com/AndroidGoLab/binder/binder"
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBluetoothPbapClient = "android.bluetooth.IBluetoothPbapClient"

const (
	TransactionIBluetoothPbapClientConnect                            = binder.FirstCallTransaction + 0
	TransactionIBluetoothPbapClientDisconnect                         = binder.FirstCallTransaction + 1
	TransactionIBluetoothPbapClientGetConnectedDevices                = binder.FirstCallTransaction + 2
	TransactionIBluetoothPbapClientGetDevicesMatchingConnectionStates = binder.FirstCallTransaction + 3
	TransactionIBluetoothPbapClientGetConnectionState                 = binder.FirstCallTransaction + 4
	TransactionIBluetoothPbapClientSetConnectionPolicy                = binder.FirstCallTransaction + 5
	TransactionIBluetoothPbapClientGetConnectionPolicy                = binder.FirstCallTransaction + 6
)

const (
	MethodIBluetoothPbapClientConnect                            = "connect"
	MethodIBluetoothPbapClientDisconnect                         = "disconnect"
	MethodIBluetoothPbapClientGetConnectedDevices                = "getConnectedDevices"
	MethodIBluetoothPbapClientGetDevicesMatchingConnectionStates = "getDevicesMatchingConnectionStates"
	MethodIBluetoothPbapClientGetConnectionState                 = "getConnectionState"
	MethodIBluetoothPbapClientSetConnectionPolicy                = "setConnectionPolicy"
	MethodIBluetoothPbapClientGetConnectionPolicy                = "getConnectionPolicy"
)

type IBluetoothPbapClient interface {
	AsBinder() binder.IBinder
	Connect(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (bool, error)
	Disconnect(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (bool, error)
	GetConnectedDevices(ctx context.Context, attributionSource content.AttributionSource) ([]BluetoothDevice, error)
	GetDevicesMatchingConnectionStates(ctx context.Context, states []int32, attributionSource content.AttributionSource) ([]BluetoothDevice, error)
	GetConnectionState(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (int32, error)
	SetConnectionPolicy(ctx context.Context, device BluetoothDevice, connectionPolicy int32, attributionSource content.AttributionSource) (bool, error)
	GetConnectionPolicy(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (int32, error)
}

type BluetoothPbapClientProxy struct {
	Remote binder.IBinder
}

func NewBluetoothPbapClientProxy(
	remote binder.IBinder,
) *BluetoothPbapClientProxy {
	return &BluetoothPbapClientProxy{Remote: remote}
}

func (p *BluetoothPbapClientProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IBluetoothPbapClient = (*BluetoothPbapClientProxy)(nil)

func (p *BluetoothPbapClientProxy) Connect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientConnect)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientConnect, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) Disconnect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientDisconnect)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientDisconnect, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) GetConnectedDevices(
	ctx context.Context,
	attributionSource content.AttributionSource,
) ([]BluetoothDevice, error) {
	var _result []BluetoothDevice
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectedDevices)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectedDevices, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _count > 1000000 {
		return _result, fmt.Errorf("array count too large: %d", _count)
	}

	if _count >= 0 {
		_result = make([]BluetoothDevice, _count)
		for _i := int32(0); _i < _count; _i++ {
			_nonNull, _err := _reply.ReadInt32()
			if _err != nil {
				break // end of inline elements (may be fewer than count)
			}
			if _nonNull != 0 {
				if _reply.Position() >= _reply.Len() {
					break // truncated list (element non-null but no data remaining)
				}
				_elemEnd, _hasElemHeader := parcel.ReadTypedListElementHeader(_reply)
				if _hasElemHeader {
					// Enforce element boundary so UnmarshalParcel
					// stops at the size-prefix envelope edge.
					_savedLimit := _reply.ReadLimit()
					_reply.SetReadLimit(_elemEnd)
					_ = _result[_i].UnmarshalParcel(_reply)
					_reply.SetReadLimit(_savedLimit)
					parcel.SkipToParcelableEnd(_reply, _elemEnd)
				} else {
					if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
						return _result, _err
					}
				}
			}
		}
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) GetDevicesMatchingConnectionStates(
	ctx context.Context,
	states []int32,
	attributionSource content.AttributionSource,
) ([]BluetoothDevice, error) {
	var _result []BluetoothDevice
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	if states == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(states)))
		for _, _item := range states {
			_data.WriteInt32(_item)
		}
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetDevicesMatchingConnectionStates)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetDevicesMatchingConnectionStates, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _count > 1000000 {
		return _result, fmt.Errorf("array count too large: %d", _count)
	}

	if _count >= 0 {
		_result = make([]BluetoothDevice, _count)
		for _i := int32(0); _i < _count; _i++ {
			_nonNull, _err := _reply.ReadInt32()
			if _err != nil {
				break // end of inline elements (may be fewer than count)
			}
			if _nonNull != 0 {
				if _reply.Position() >= _reply.Len() {
					break // truncated list (element non-null but no data remaining)
				}
				_elemEnd, _hasElemHeader := parcel.ReadTypedListElementHeader(_reply)
				if _hasElemHeader {
					// Enforce element boundary so UnmarshalParcel
					// stops at the size-prefix envelope edge.
					_savedLimit := _reply.ReadLimit()
					_reply.SetReadLimit(_elemEnd)
					_ = _result[_i].UnmarshalParcel(_reply)
					_reply.SetReadLimit(_savedLimit)
					parcel.SkipToParcelableEnd(_reply, _elemEnd)
				} else {
					if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
						return _result, _err
					}
				}
			}
		}
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) GetConnectionState(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectionState)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectionState, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) SetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	connectionPolicy int32,
	attributionSource content.AttributionSource,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(connectionPolicy)
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientSetConnectionPolicy)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientSetConnectionPolicy, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPbapClientProxy) GetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBluetoothPbapClient)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(1)
	if _err := attributionSource.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectionPolicy)
	if _err != nil {
		return _result, fmt.Errorf("resolving %s.%s: %w", DescriptorIBluetoothPbapClient, MethodIBluetoothPbapClientGetConnectionPolicy, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

// BluetoothPbapClientStub dispatches incoming binder transactions
// to a typed IBluetoothPbapClient implementation.
type BluetoothPbapClientStub struct {
	Impl      IBluetoothPbapClient
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*BluetoothPbapClientStub)(nil)

func (s *BluetoothPbapClientStub) Descriptor() string {
	return DescriptorIBluetoothPbapClient
}

func (s *BluetoothPbapClientStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIBluetoothPbapClientConnect:
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.Connect(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPbapClientDisconnect:
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.Disconnect(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPbapClientGetConnectedDevices:
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.GetConnectedDevices(ctx, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		if _result == nil {
			_reply.WriteInt32(-1)
		} else {
			_reply.WriteInt32(int32(len(_result)))
			for _, _item := range _result {
				_reply.WriteInt32(1)
				if _err := _item.MarshalParcel(_reply); _err != nil {
					return nil, _err
				}
			}
		}
		return _reply, nil
	case TransactionIBluetoothPbapClientGetDevicesMatchingConnectionStates:
		var _arg_states []int32
		{
			_count, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _count > 1000000 {
				return nil, fmt.Errorf("array count too large: %d", _count)
			}
			if _count >= 0 {
				_arg_states = make([]int32, _count)
				for _i := int32(0); _i < _count; _i++ {
					_arg_states[_i], _err = _data.ReadInt32()
					if _err != nil {
						return nil, _err
					}
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.GetDevicesMatchingConnectionStates(ctx, _arg_states, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		if _result == nil {
			_reply.WriteInt32(-1)
		} else {
			_reply.WriteInt32(int32(len(_result)))
			for _, _item := range _result {
				_reply.WriteInt32(1)
				if _err := _item.MarshalParcel(_reply); _err != nil {
					return nil, _err
				}
			}
		}
		return _reply, nil
	case TransactionIBluetoothPbapClientGetConnectionState:
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.GetConnectionState(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIBluetoothPbapClientSetConnectionPolicy:
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_connectionPolicy, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.SetConnectionPolicy(ctx, _arg_device, _arg_connectionPolicy, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPbapClientGetConnectionPolicy:
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource content.AttributionSource
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributionSource.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.GetConnectionPolicy(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IBluetoothPbapClientServer is the server-side interface that user implementations
// provide to NewBluetoothPbapClientStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IBluetoothPbapClientServer interface {
	Connect(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (bool, error)
	Disconnect(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (bool, error)
	GetConnectedDevices(ctx context.Context, attributionSource content.AttributionSource) ([]BluetoothDevice, error)
	GetDevicesMatchingConnectionStates(ctx context.Context, states []int32, attributionSource content.AttributionSource) ([]BluetoothDevice, error)
	GetConnectionState(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (int32, error)
	SetConnectionPolicy(ctx context.Context, device BluetoothDevice, connectionPolicy int32, attributionSource content.AttributionSource) (bool, error)
	GetConnectionPolicy(ctx context.Context, device BluetoothDevice, attributionSource content.AttributionSource) (int32, error)
}

type bluetoothPbapClientStubWrapper struct {
	impl       IBluetoothPbapClientServer
	stubBinder *binder.StubBinder
}

func (w *bluetoothPbapClientStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *bluetoothPbapClientStubWrapper) Connect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (bool, error) {
	return w.impl.Connect(ctx, device, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) Disconnect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (bool, error) {
	return w.impl.Disconnect(ctx, device, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) GetConnectedDevices(
	ctx context.Context,
	attributionSource content.AttributionSource,
) ([]BluetoothDevice, error) {
	return w.impl.GetConnectedDevices(ctx, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) GetDevicesMatchingConnectionStates(
	ctx context.Context,
	states []int32,
	attributionSource content.AttributionSource,
) ([]BluetoothDevice, error) {
	return w.impl.GetDevicesMatchingConnectionStates(ctx, states, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) GetConnectionState(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (int32, error) {
	return w.impl.GetConnectionState(ctx, device, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) SetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	connectionPolicy int32,
	attributionSource content.AttributionSource,
) (bool, error) {
	return w.impl.SetConnectionPolicy(ctx, device, connectionPolicy, attributionSource)
}

func (w *bluetoothPbapClientStubWrapper) GetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource content.AttributionSource,
) (int32, error) {
	return w.impl.GetConnectionPolicy(ctx, device, attributionSource)
}

var _ IBluetoothPbapClient = (*bluetoothPbapClientStubWrapper)(nil)

// NewBluetoothPbapClientStub creates a server-side IBluetoothPbapClient wrapping the given
// server implementation. The returned value satisfies IBluetoothPbapClient
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewBluetoothPbapClientStub(
	impl IBluetoothPbapClientServer,
) IBluetoothPbapClient {
	wrapper := &bluetoothPbapClientStubWrapper{impl: impl}
	stub := &BluetoothPbapClientStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
