package bluetooth

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBluetoothPan = "android.bluetooth.IBluetoothPan"

const (
	TransactionIBluetoothPanIsTetheringOn                      = binder.FirstCallTransaction + 0
	TransactionIBluetoothPanSetBluetoothTethering              = binder.FirstCallTransaction + 1
	TransactionIBluetoothPanConnect                            = binder.FirstCallTransaction + 2
	TransactionIBluetoothPanDisconnect                         = binder.FirstCallTransaction + 3
	TransactionIBluetoothPanGetConnectedDevices                = binder.FirstCallTransaction + 4
	TransactionIBluetoothPanGetDevicesMatchingConnectionStates = binder.FirstCallTransaction + 5
	TransactionIBluetoothPanGetConnectionState                 = binder.FirstCallTransaction + 6
	TransactionIBluetoothPanSetConnectionPolicy                = binder.FirstCallTransaction + 7
)

type IBluetoothPan interface {
	AsBinder() binder.IBinder
	IsTetheringOn(ctx context.Context, attributionSource interface{}) (bool, error)
	SetBluetoothTethering(ctx context.Context, callback IBluetoothPanCallback, id int32, value bool, attributionSource interface{}) error
	Connect(ctx context.Context, device BluetoothDevice, attributionSource interface{}) (bool, error)
	Disconnect(ctx context.Context, device BluetoothDevice, attributionSource interface{}) (bool, error)
	GetConnectedDevices(ctx context.Context, attributionSource interface{}) ([]BluetoothDevice, error)
	GetDevicesMatchingConnectionStates(ctx context.Context, states []int32, attributionSource interface{}) ([]BluetoothDevice, error)
	GetConnectionState(ctx context.Context, device BluetoothDevice, attributionSource interface{}) (int32, error)
	SetConnectionPolicy(ctx context.Context, device BluetoothDevice, connectionPolicy int32, attributionSource interface{}) (bool, error)
}

type BluetoothPanProxy struct {
	remote binder.IBinder
}

func NewBluetoothPanProxy(
	remote binder.IBinder,
) *BluetoothPanProxy {
	return &BluetoothPanProxy{remote: remote}
}

func (p *BluetoothPanProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBluetoothPan = (*BluetoothPanProxy)(nil)

func (p *BluetoothPanProxy) IsTetheringOn(
	ctx context.Context,
	attributionSource interface{},
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "isTetheringOn")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPanProxy) SetBluetoothTethering(
	ctx context.Context,
	callback IBluetoothPanCallback,
	id int32,
	value bool,
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	_data.WriteStrongBinder(callback.AsBinder().Handle())
	_data.WriteInt32(id)
	_data.WriteBool(value)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "setBluetoothTethering")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothPanProxy) Connect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource interface{},
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "connect")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPanProxy) Disconnect(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource interface{},
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "disconnect")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPanProxy) GetConnectedDevices(
	ctx context.Context,
	attributionSource interface{},
) ([]BluetoothDevice, error) {
	var _result []BluetoothDevice
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "getConnectedDevices")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]BluetoothDevice, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *BluetoothPanProxy) GetDevicesMatchingConnectionStates(
	ctx context.Context,
	states []int32,
	attributionSource interface{},
) ([]BluetoothDevice, error) {
	var _result []BluetoothDevice
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	if states == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(states)))
		for _, _item := range states {
			_data.WriteInt32(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "getDevicesMatchingConnectionStates")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]BluetoothDevice, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *BluetoothPanProxy) GetConnectionState(
	ctx context.Context,
	device BluetoothDevice,
	attributionSource interface{},
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "getConnectionState")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *BluetoothPanProxy) SetConnectionPolicy(
	ctx context.Context,
	device BluetoothDevice,
	connectionPolicy int32,
	attributionSource interface{},
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothPan)
	_data.WriteInt32(1)
	if _err := device.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(connectionPolicy)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothPan, "setConnectionPolicy")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

// BluetoothPanStub dispatches incoming binder transactions
// to a typed IBluetoothPan implementation.
type BluetoothPanStub struct {
	Impl IBluetoothPan
}

var _ binder.TransactionReceiver = (*BluetoothPanStub)(nil)

func (s *BluetoothPanStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBluetoothPanIsTetheringOn:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.IsTetheringOn(ctx, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPanSetBluetoothTethering:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IBluetoothPanCallback
		_ = _arg_callback
		_arg_id, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_value, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetBluetoothTethering(ctx, _arg_callback, _arg_id, _arg_value, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothPanConnect:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.Connect(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPanDisconnect:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.Disconnect(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIBluetoothPanGetConnectedDevices:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.GetConnectedDevices(ctx, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIBluetoothPanGetDevicesMatchingConnectionStates:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_states []int32
		_ = _arg_states
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.GetDevicesMatchingConnectionStates(ctx, _arg_states, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIBluetoothPanGetConnectionState:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.GetConnectionState(ctx, _arg_device, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIBluetoothPanSetConnectionPolicy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_device BluetoothDevice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_device.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_connectionPolicy, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_result, _err := s.Impl.SetConnectionPolicy(ctx, _arg_device, _arg_connectionPolicy, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
