package bluetooth

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBluetoothAdvertise = "android.bluetooth.IBluetoothAdvertise"

const (
	TransactionIBluetoothAdvertiseStartAdvertisingSet              = binder.FirstCallTransaction + 0
	TransactionIBluetoothAdvertiseStopAdvertisingSet               = binder.FirstCallTransaction + 1
	TransactionIBluetoothAdvertiseGetOwnAddress                    = binder.FirstCallTransaction + 2
	TransactionIBluetoothAdvertiseEnableAdvertisingSet             = binder.FirstCallTransaction + 3
	TransactionIBluetoothAdvertiseSetAdvertisingData               = binder.FirstCallTransaction + 4
	TransactionIBluetoothAdvertiseSetScanResponseData              = binder.FirstCallTransaction + 5
	TransactionIBluetoothAdvertiseSetAdvertisingParameters         = binder.FirstCallTransaction + 6
	TransactionIBluetoothAdvertiseSetPeriodicAdvertisingParameters = binder.FirstCallTransaction + 7
	TransactionIBluetoothAdvertiseSetPeriodicAdvertisingData       = binder.FirstCallTransaction + 8
	TransactionIBluetoothAdvertiseSetPeriodicAdvertisingEnable     = binder.FirstCallTransaction + 9
)

type IBluetoothAdvertise interface {
	AsBinder() binder.IBinder
	StartAdvertisingSet(ctx context.Context, parameters interface{}, advertiseData interface{}, scanResponse interface{}, periodicParameters interface{}, periodicData interface{}, duration int32, maxExtAdvEvents int32, gattServerIf int32, callback interface{}, attributionSource interface{}) error
	StopAdvertisingSet(ctx context.Context, callback interface{}, attributionSource interface{}) error
	GetOwnAddress(ctx context.Context, advertiserId int32, attributionSource interface{}) error
	EnableAdvertisingSet(ctx context.Context, advertiserId int32, enable bool, duration int32, maxExtAdvEvents int32, attributionSource interface{}) error
	SetAdvertisingData(ctx context.Context, advertiserId int32, data interface{}, attributionSource interface{}) error
	SetScanResponseData(ctx context.Context, advertiserId int32, data interface{}, attributionSource interface{}) error
	SetAdvertisingParameters(ctx context.Context, advertiserId int32, parameters interface{}, attributionSource interface{}) error
	SetPeriodicAdvertisingParameters(ctx context.Context, advertiserId int32, parameters interface{}, attributionSource interface{}) error
	SetPeriodicAdvertisingData(ctx context.Context, advertiserId int32, data interface{}, attributionSource interface{}) error
	SetPeriodicAdvertisingEnable(ctx context.Context, advertiserId int32, enable bool, attributionSource interface{}) error
}

type BluetoothAdvertiseProxy struct {
	remote binder.IBinder
}

func NewBluetoothAdvertiseProxy(
	remote binder.IBinder,
) *BluetoothAdvertiseProxy {
	return &BluetoothAdvertiseProxy{remote: remote}
}

func (p *BluetoothAdvertiseProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBluetoothAdvertise = (*BluetoothAdvertiseProxy)(nil)

func (p *BluetoothAdvertiseProxy) StartAdvertisingSet(
	ctx context.Context,
	parameters interface{},
	advertiseData interface{},
	scanResponse interface{},
	periodicParameters interface{},
	periodicData interface{},
	duration int32,
	maxExtAdvEvents int32,
	gattServerIf int32,
	callback interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(duration)
	_data.WriteInt32(maxExtAdvEvents)
	_data.WriteInt32(gattServerIf)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "startAdvertisingSet")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseStartAdvertisingSet
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) StopAdvertisingSet(
	ctx context.Context,
	callback interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "stopAdvertisingSet")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseStopAdvertisingSet
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) GetOwnAddress(
	ctx context.Context,
	advertiserId int32,
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "getOwnAddress")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseGetOwnAddress
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) EnableAdvertisingSet(
	ctx context.Context,
	advertiserId int32,
	enable bool,
	duration int32,
	maxExtAdvEvents int32,
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)
	_data.WriteBool(enable)
	_data.WriteInt32(duration)
	_data.WriteInt32(maxExtAdvEvents)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "enableAdvertisingSet")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseEnableAdvertisingSet
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetAdvertisingData(
	ctx context.Context,
	advertiserId int32,
	data interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setAdvertisingData")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetAdvertisingData
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetScanResponseData(
	ctx context.Context,
	advertiserId int32,
	data interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setScanResponseData")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetScanResponseData
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetAdvertisingParameters(
	ctx context.Context,
	advertiserId int32,
	parameters interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setAdvertisingParameters")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetAdvertisingParameters
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetPeriodicAdvertisingParameters(
	ctx context.Context,
	advertiserId int32,
	parameters interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setPeriodicAdvertisingParameters")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetPeriodicAdvertisingParameters
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetPeriodicAdvertisingData(
	ctx context.Context,
	advertiserId int32,
	data interface{},
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setPeriodicAdvertisingData")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetPeriodicAdvertisingData
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BluetoothAdvertiseProxy) SetPeriodicAdvertisingEnable(
	ctx context.Context,
	advertiserId int32,
	enable bool,
	attributionSource interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBluetoothAdvertise)
	_data.WriteInt32(advertiserId)
	_data.WriteBool(enable)

	_code, _err := p.remote.ResolveCode(DescriptorIBluetoothAdvertise, "setPeriodicAdvertisingEnable")
	if _err != nil {
		_code = TransactionIBluetoothAdvertiseSetPeriodicAdvertisingEnable
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// BluetoothAdvertiseStub dispatches incoming binder transactions
// to a typed IBluetoothAdvertise implementation.
type BluetoothAdvertiseStub struct {
	Impl IBluetoothAdvertise
}

var _ binder.TransactionReceiver = (*BluetoothAdvertiseStub)(nil)

func (s *BluetoothAdvertiseStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBluetoothAdvertiseStartAdvertisingSet:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_parameters interface{}
		var _arg_advertiseData interface{}
		var _arg_scanResponse interface{}
		var _arg_periodicParameters interface{}
		var _arg_periodicData interface{}
		_arg_duration, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_maxExtAdvEvents, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_gattServerIf, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_callback interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.StartAdvertisingSet(ctx, _arg_parameters, _arg_advertiseData, _arg_scanResponse, _arg_periodicParameters, _arg_periodicData, _arg_duration, _arg_maxExtAdvEvents, _arg_gattServerIf, _arg_callback, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseStopAdvertisingSet:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_callback interface{}
		var _arg_attributionSource interface{}
		_err := s.Impl.StopAdvertisingSet(ctx, _arg_callback, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseGetOwnAddress:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_err = s.Impl.GetOwnAddress(ctx, _arg_advertiserId, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseEnableAdvertisingSet:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_enable, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_duration, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_maxExtAdvEvents, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_err = s.Impl.EnableAdvertisingSet(ctx, _arg_advertiserId, _arg_enable, _arg_duration, _arg_maxExtAdvEvents, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetAdvertisingData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_data interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetAdvertisingData(ctx, _arg_advertiserId, _arg_data, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetScanResponseData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_data interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetScanResponseData(ctx, _arg_advertiserId, _arg_data, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetAdvertisingParameters:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_parameters interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetAdvertisingParameters(ctx, _arg_advertiserId, _arg_parameters, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetPeriodicAdvertisingParameters:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_parameters interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetPeriodicAdvertisingParameters(ctx, _arg_advertiserId, _arg_parameters, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetPeriodicAdvertisingData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_data interface{}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetPeriodicAdvertisingData(ctx, _arg_advertiserId, _arg_data, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBluetoothAdvertiseSetPeriodicAdvertisingEnable:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_advertiserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_enable, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		var _arg_attributionSource interface{}
		_err = s.Impl.SetPeriodicAdvertisingEnable(ctx, _arg_advertiserId, _arg_enable, _arg_attributionSource)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
