// Code generated by genparcelgo. DO NOT EDIT.

package biometrics

import (
	"github.com/xaionaro-go/binder/parcel"
)

type PromptVerticalListContentView struct {
	Description string
	// ContentList: opaque type — not yet supported
}

var _ parcel.Parcelable = (*PromptVerticalListContentView)(nil)

func (s *PromptVerticalListContentView) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString16(s.Description)
	return nil
}

func (s *PromptVerticalListContentView) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Description, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	return nil
}
