package back

import (
	"context"
	"fmt"
	view "github.com/xaionaro-go/binder/android/view"
	window "github.com/xaionaro-go/binder/android/window"
	"github.com/xaionaro-go/binder/binder"
	internalView "github.com/xaionaro-go/binder/com/android/internal_/view"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBackAnimation = "com.android.wm.shell.back.IBackAnimation"

const (
	TransactionIBackAnimationSetBackToLauncherCallback    = binder.FirstCallTransaction + 0
	TransactionIBackAnimationClearBackToLauncherCallback  = binder.FirstCallTransaction + 1
	TransactionIBackAnimationCustomizeStatusBarAppearance = binder.FirstCallTransaction + 2
)

type IBackAnimation interface {
	AsBinder() binder.IBinder
	SetBackToLauncherCallback(ctx context.Context, callback window.IOnBackInvokedCallback, runner view.IRemoteAnimationRunner) error
	ClearBackToLauncherCallback(ctx context.Context) error
	CustomizeStatusBarAppearance(ctx context.Context, appearance internalView.AppearanceRegion) error
}

type BackAnimationProxy struct {
	remote binder.IBinder
}

func NewBackAnimationProxy(
	remote binder.IBinder,
) *BackAnimationProxy {
	return &BackAnimationProxy{remote: remote}
}

func (p *BackAnimationProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBackAnimation = (*BackAnimationProxy)(nil)

func (p *BackAnimationProxy) SetBackToLauncherCallback(
	ctx context.Context,
	callback window.IOnBackInvokedCallback,
	runner view.IRemoteAnimationRunner,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackAnimation)
	_data.WriteStrongBinder(callback.AsBinder().Handle())
	_data.WriteStrongBinder(runner.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackAnimation, "setBackToLauncherCallback")
	if _err != nil {
		_code = TransactionIBackAnimationSetBackToLauncherCallback
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BackAnimationProxy) ClearBackToLauncherCallback(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackAnimation)

	_code, _err := p.remote.ResolveCode(DescriptorIBackAnimation, "clearBackToLauncherCallback")
	if _err != nil {
		_code = TransactionIBackAnimationClearBackToLauncherCallback
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *BackAnimationProxy) CustomizeStatusBarAppearance(
	ctx context.Context,
	appearance internalView.AppearanceRegion,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackAnimation)
	_data.WriteInt32(1)
	if _err := appearance.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackAnimation, "customizeStatusBarAppearance")
	if _err != nil {
		_code = TransactionIBackAnimationCustomizeStatusBarAppearance
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// BackAnimationStub dispatches incoming binder transactions
// to a typed IBackAnimation implementation.
type BackAnimationStub struct {
	Impl IBackAnimation
}

var _ binder.TransactionReceiver = (*BackAnimationStub)(nil)

func (s *BackAnimationStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBackAnimationSetBackToLauncherCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback window.IOnBackInvokedCallback
		_ = _arg_callback
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_runner view.IRemoteAnimationRunner
		_ = _arg_runner
		_err := s.Impl.SetBackToLauncherCallback(ctx, _arg_callback, _arg_runner)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBackAnimationClearBackToLauncherCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.ClearBackToLauncherCallback(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIBackAnimationCustomizeStatusBarAppearance:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_appearance internalView.AppearanceRegion
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_appearance.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.CustomizeStatusBarAppearance(ctx, _arg_appearance)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
