package can

import (
	"fmt"
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const (
	NativeInterfaceInterfaceIdTagIfname   int32 = 0
	NativeInterfaceInterfaceIdTagSerialno int32 = 1
)

type NativeInterfaceInterfaceId struct {
	Tag      int32
	Ifname   string
	Serialno []string
}

var _ parcel.Parcelable = (*NativeInterfaceInterfaceId)(nil)

func (u *NativeInterfaceInterfaceId) GetIfname() (string, bool) {
	if u.Tag != NativeInterfaceInterfaceIdTagIfname {
		var _zero string
		return _zero, false
	}
	return u.Ifname, true
}

func (u *NativeInterfaceInterfaceId) SetIfname(
	v string,
) {
	*u = NativeInterfaceInterfaceId{Tag: NativeInterfaceInterfaceIdTagIfname, Ifname: v}
}

func (u *NativeInterfaceInterfaceId) GetSerialno() ([]string, bool) {
	if u.Tag != NativeInterfaceInterfaceIdTagSerialno {
		var _zero []string
		return _zero, false
	}
	return u.Serialno, true
}

func (u *NativeInterfaceInterfaceId) SetSerialno(
	v []string,
) {
	*u = NativeInterfaceInterfaceId{Tag: NativeInterfaceInterfaceIdTagSerialno, Serialno: v}
}

func (u *NativeInterfaceInterfaceId) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(u.Tag)

	switch u.Tag {
	case NativeInterfaceInterfaceIdTagIfname:
		p.WriteString16(u.Ifname)
	case NativeInterfaceInterfaceIdTagSerialno:
		if u.Serialno == nil {
			p.WriteInt32(-1)
		} else {
			p.WriteInt32(int32(len(u.Serialno)))
			for _, _item := range u.Serialno {
				p.WriteString16(_item)
			}
		}
	default:
		return fmt.Errorf("unknown union tag %d for NativeInterfaceInterfaceId", u.Tag)
	}

	return nil
}

func (u *NativeInterfaceInterfaceId) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error

	u.Tag, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	switch u.Tag {
	case NativeInterfaceInterfaceIdTagIfname:
		u.Ifname, _err = p.ReadString16()
		if _err != nil {
			return _err
		}
	case NativeInterfaceInterfaceIdTagSerialno:

		var _count0 int32
		_count0, _err = p.ReadInt32()
		if _err != nil {
			return _err
		}
		if _count0 >= 0 {
			u.Serialno = make([]string, _count0)
			for _i := int32(0); _i < _count0; _i++ {
				u.Serialno[_i], _err = p.ReadString16()
				if _err != nil {
					return _err
				}
			}
		}
	default:
		return fmt.Errorf("unknown union tag %d for NativeInterfaceInterfaceId", u.Tag)
	}

	return nil
}
