package aidl

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIFeatureProvisioningCallback = "android.telephony.ims.aidl.IFeatureProvisioningCallback"

const (
	TransactionIFeatureProvisioningCallbackOnFeatureProvisioningChanged    = binder.FirstCallTransaction + 0
	TransactionIFeatureProvisioningCallbackOnRcsFeatureProvisioningChanged = binder.FirstCallTransaction + 1
)

type IFeatureProvisioningCallback interface {
	AsBinder() binder.IBinder
	OnFeatureProvisioningChanged(ctx context.Context, capability int32, tech int32, isProvisioned bool) error
	OnRcsFeatureProvisioningChanged(ctx context.Context, capability int32, tech int32, isProvisioned bool) error
}

type FeatureProvisioningCallbackProxy struct {
	remote binder.IBinder
}

func NewFeatureProvisioningCallbackProxy(
	remote binder.IBinder,
) *FeatureProvisioningCallbackProxy {
	return &FeatureProvisioningCallbackProxy{remote: remote}
}

func (p *FeatureProvisioningCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IFeatureProvisioningCallback = (*FeatureProvisioningCallbackProxy)(nil)

func (p *FeatureProvisioningCallbackProxy) OnFeatureProvisioningChanged(
	ctx context.Context,
	capability int32,
	tech int32,
	isProvisioned bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIFeatureProvisioningCallback)
	_data.WriteInt32(capability)
	_data.WriteInt32(tech)
	_data.WriteBool(isProvisioned)

	_code, _err := p.remote.ResolveCode(DescriptorIFeatureProvisioningCallback, "onFeatureProvisioningChanged")
	if _err != nil {
		_code = TransactionIFeatureProvisioningCallbackOnFeatureProvisioningChanged
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *FeatureProvisioningCallbackProxy) OnRcsFeatureProvisioningChanged(
	ctx context.Context,
	capability int32,
	tech int32,
	isProvisioned bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIFeatureProvisioningCallback)
	_data.WriteInt32(capability)
	_data.WriteInt32(tech)
	_data.WriteBool(isProvisioned)

	_code, _err := p.remote.ResolveCode(DescriptorIFeatureProvisioningCallback, "onRcsFeatureProvisioningChanged")
	if _err != nil {
		_code = TransactionIFeatureProvisioningCallbackOnRcsFeatureProvisioningChanged
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// FeatureProvisioningCallbackStub dispatches incoming binder transactions
// to a typed IFeatureProvisioningCallback implementation.
type FeatureProvisioningCallbackStub struct {
	Impl IFeatureProvisioningCallback
}

var _ binder.TransactionReceiver = (*FeatureProvisioningCallbackStub)(nil)

func (s *FeatureProvisioningCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIFeatureProvisioningCallbackOnFeatureProvisioningChanged:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_capability, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_tech, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_isProvisioned, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnFeatureProvisioningChanged(ctx, _arg_capability, _arg_tech, _arg_isProvisioned)
		_ = _err
		return nil, nil
	case TransactionIFeatureProvisioningCallbackOnRcsFeatureProvisioningChanged:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_capability, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_tech, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_isProvisioned, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRcsFeatureProvisioningChanged(ctx, _arg_capability, _arg_tech, _arg_isProvisioned)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
