// Code generated by spec2go. DO NOT EDIT.

package appwidget

import (
	"context"
	"fmt"

	"github.com/xaionaro-go/binder/servicemanager"
)

// GetAppWidgetService retrieves the AppwidgetService service and returns a typed proxy.
func GetAppWidgetService(
	ctx context.Context,
	sm *servicemanager.ServiceManager,
) (*AppWidgetServiceProxy, error) {
	svc, err := sm.GetService(ctx, servicemanager.AppwidgetService)
	if err != nil {
		return nil, fmt.Errorf("GetAppWidgetService: %w", err)
	}
	return NewAppWidgetServiceProxy(svc), nil
}
