package usb

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type UsbPortStatus struct {
	CurrentMode                 int32
	CurrentPowerRole            int32
	CurrentDataRole             int32
	SupportedRoleCombinations   int32
	ContaminantProtectionStatus int32
	ContaminantDetectionStatus  int32
	UsbDataStatus               int32
	PowerTransferLimited        bool
	PowerBrickConnectionStatus  int32
	PlugState                   int32
}

var _ parcel.Parcelable = (*UsbPortStatus)(nil)

func (s *UsbPortStatus) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.CurrentMode)
	p.WriteInt32(s.CurrentPowerRole)
	p.WriteInt32(s.CurrentDataRole)
	p.WriteInt32(s.SupportedRoleCombinations)
	p.WriteInt32(s.ContaminantProtectionStatus)
	p.WriteInt32(s.ContaminantDetectionStatus)
	p.WriteInt32(s.UsbDataStatus)
	p.WriteBool(s.PowerTransferLimited)
	p.WriteInt32(s.PowerBrickConnectionStatus)
	p.WriteInt32(s.PlugState)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *UsbPortStatus) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.CurrentMode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.CurrentPowerRole, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.CurrentDataRole, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.SupportedRoleCombinations, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ContaminantProtectionStatus, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.ContaminantDetectionStatus, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.UsbDataStatus, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.PowerTransferLimited, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.PowerBrickConnectionStatus, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.PlugState, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
