package credentials

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIClearCredentialStateCallback = "android.credentials.IClearCredentialStateCallback"

const (
	TransactionIClearCredentialStateCallbackOnSuccess = binder.FirstCallTransaction + 0
	TransactionIClearCredentialStateCallbackOnError   = binder.FirstCallTransaction + 1
)

type IClearCredentialStateCallback interface {
	AsBinder() binder.IBinder
	OnSuccess(ctx context.Context) error
	OnError(ctx context.Context, errorType string, message string) error
}

type ClearCredentialStateCallbackProxy struct {
	remote binder.IBinder
}

func NewClearCredentialStateCallbackProxy(
	remote binder.IBinder,
) *ClearCredentialStateCallbackProxy {
	return &ClearCredentialStateCallbackProxy{remote: remote}
}

func (p *ClearCredentialStateCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IClearCredentialStateCallback = (*ClearCredentialStateCallbackProxy)(nil)

func (p *ClearCredentialStateCallbackProxy) OnSuccess(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIClearCredentialStateCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIClearCredentialStateCallback, "onSuccess")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ClearCredentialStateCallbackProxy) OnError(
	ctx context.Context,
	errorType string,
	message string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIClearCredentialStateCallback)
	_data.WriteString16(errorType)
	_data.WriteString16(message)

	_code, _err := p.remote.ResolveCode(DescriptorIClearCredentialStateCallback, "onError")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ClearCredentialStateCallbackStub dispatches incoming binder transactions
// to a typed IClearCredentialStateCallback implementation.
type ClearCredentialStateCallbackStub struct {
	Impl IClearCredentialStateCallback
}

var _ binder.TransactionReceiver = (*ClearCredentialStateCallbackStub)(nil)

func (s *ClearCredentialStateCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIClearCredentialStateCallbackOnSuccess:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnSuccess(ctx)
		_ = _err
		return nil, nil
	case TransactionIClearCredentialStateCallbackOnError:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_errorType, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_message, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnError(ctx, _arg_errorType, _arg_message)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
