package fingerprint

// Code generated by aidlgen. DO NOT EDIT.

type FingerprintSensorType byte

const (
	FingerprintSensorTypeUNKNOWN                FingerprintSensorType = 0
	FingerprintSensorTypeREAR                   FingerprintSensorType = 1
	FingerprintSensorTypeUnderDisplayUltrasonic FingerprintSensorType = 2
	FingerprintSensorTypeUnderDisplayOptical    FingerprintSensorType = 3
	FingerprintSensorTypePowerButton            FingerprintSensorType = 4
	FingerprintSensorTypeHomeButton             FingerprintSensorType = 5
)
