package wifi

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PasnConfig struct {
	BaseAkm     int64
	CipherSuite int64
	Passphrase  []byte
	Pmkid       []byte
}

var _ parcel.Parcelable = (*PasnConfig)(nil)

func (s *PasnConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt64(s.BaseAkm)
	p.WriteInt64(s.CipherSuite)
	p.WriteByteArray(s.Passphrase)
	p.WriteByteArray(s.Pmkid)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *PasnConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.BaseAkm, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	s.CipherSuite, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	s.Passphrase, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	s.Pmkid, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
