package wifi

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type RttSecureConfig struct {
	PasnConfig                   PasnConfig
	EnableSecureHeLtf            bool
	EnableRangingFrameProtection bool
	PasnComebackCookie           []byte
}

var _ parcel.Parcelable = (*RttSecureConfig)(nil)

func (s *RttSecureConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if _err := s.PasnConfig.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteBool(s.EnableSecureHeLtf)
	p.WriteBool(s.EnableRangingFrameProtection)
	p.WriteByteArray(s.PasnComebackCookie)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *RttSecureConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if _err = s.PasnConfig.UnmarshalParcel(p); _err != nil {
		return _err
	}

	s.EnableSecureHeLtf, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	s.EnableRangingFrameProtection, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	s.PasnComebackCookie, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
