package cec

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIHdmiCecCallback = "android.hardware.tv.hdmi.cec.IHdmiCecCallback"

const (
	TransactionIHdmiCecCallbackOnCecMessage = binder.FirstCallTransaction + 0
)

type IHdmiCecCallback interface {
	AsBinder() binder.IBinder
	OnCecMessage(ctx context.Context, message CecMessage) error
}

type HdmiCecCallbackProxy struct {
	remote binder.IBinder
}

func NewHdmiCecCallbackProxy(
	remote binder.IBinder,
) *HdmiCecCallbackProxy {
	return &HdmiCecCallbackProxy{remote: remote}
}

func (p *HdmiCecCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IHdmiCecCallback = (*HdmiCecCallbackProxy)(nil)

func (p *HdmiCecCallbackProxy) OnCecMessage(
	ctx context.Context,
	message CecMessage,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIHdmiCecCallback)
	_data.WriteInt32(1)
	if _err := message.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIHdmiCecCallback, "onCecMessage")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// HdmiCecCallbackStub dispatches incoming binder transactions
// to a typed IHdmiCecCallback implementation.
type HdmiCecCallbackStub struct {
	Impl IHdmiCecCallback
}

var _ binder.TransactionReceiver = (*HdmiCecCallbackStub)(nil)

func (s *HdmiCecCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIHdmiCecCallbackOnCecMessage:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_message CecMessage
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_message.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.OnCecMessage(ctx, _arg_message)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
