package projection

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIMediaProjectionCallback = "android.media.projection.IMediaProjectionCallback"

const (
	TransactionIMediaProjectionCallbackOnStop                             = binder.FirstCallTransaction + 0
	TransactionIMediaProjectionCallbackOnCapturedContentResize            = binder.FirstCallTransaction + 1
	TransactionIMediaProjectionCallbackOnCapturedContentVisibilityChanged = binder.FirstCallTransaction + 2
)

type IMediaProjectionCallback interface {
	AsBinder() binder.IBinder
	OnStop(ctx context.Context) error
	OnCapturedContentResize(ctx context.Context, width int32, height int32) error
	OnCapturedContentVisibilityChanged(ctx context.Context, isVisible bool) error
}

type MediaProjectionCallbackProxy struct {
	remote binder.IBinder
}

func NewMediaProjectionCallbackProxy(
	remote binder.IBinder,
) *MediaProjectionCallbackProxy {
	return &MediaProjectionCallbackProxy{remote: remote}
}

func (p *MediaProjectionCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IMediaProjectionCallback = (*MediaProjectionCallbackProxy)(nil)

func (p *MediaProjectionCallbackProxy) OnStop(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onStop")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *MediaProjectionCallbackProxy) OnCapturedContentResize(
	ctx context.Context,
	width int32,
	height int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)
	_data.WriteInt32(width)
	_data.WriteInt32(height)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onCapturedContentResize")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *MediaProjectionCallbackProxy) OnCapturedContentVisibilityChanged(
	ctx context.Context,
	isVisible bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)
	_data.WriteBool(isVisible)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onCapturedContentVisibilityChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// MediaProjectionCallbackStub dispatches incoming binder transactions
// to a typed IMediaProjectionCallback implementation.
type MediaProjectionCallbackStub struct {
	Impl IMediaProjectionCallback
}

var _ binder.TransactionReceiver = (*MediaProjectionCallbackStub)(nil)

func (s *MediaProjectionCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIMediaProjectionCallbackOnStop:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnStop(ctx)
		_ = _err
		return nil, nil
	case TransactionIMediaProjectionCallbackOnCapturedContentResize:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_width, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_height, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnCapturedContentResize(ctx, _arg_width, _arg_height)
		_ = _err
		return nil, nil
	case TransactionIMediaProjectionCallbackOnCapturedContentVisibilityChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_isVisible, _err := data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnCapturedContentVisibilityChanged(ctx, _arg_isVisible)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
