package common

// Code generated by aidlgen. DO NOT EDIT.

type Compression int64

const (
	CompressionNONE                     Compression = 0
	CompressionDisplayStreamCompression Compression = 1
)
