package metadata

// Code generated by aidlgen. DO NOT EDIT.

type NoiseReductionMode int32

const (
	NoiseReductionModeAndroidNoiseReductionModeOff            NoiseReductionMode = 0
	NoiseReductionModeAndroidNoiseReductionModeFast           NoiseReductionMode = 1
	NoiseReductionModeAndroidNoiseReductionModeHighQuality    NoiseReductionMode = 2
	NoiseReductionModeAndroidNoiseReductionModeMinimal        NoiseReductionMode = 3
	NoiseReductionModeAndroidNoiseReductionModeZeroShutterLag NoiseReductionMode = 4
)
