package pm

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type Attribution struct {
	Tag   string
	Label int32
}

var _ parcel.Parcelable = (*Attribution)(nil)

func (s *Attribution) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteString16(s.Tag)
	p.WriteInt32(s.Label)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *Attribution) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Tag, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}
	s.Label, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
