// Code generated by genparcelgo. DO NOT EDIT.

package pm

import (
	"github.com/xaionaro-go/binder/parcel"
)

type ChangedPackages struct {
	SequenceNumber int32
	// PackageNames: opaque type — not yet supported
}

var _ parcel.Parcelable = (*ChangedPackages)(nil)

func (s *ChangedPackages) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.SequenceNumber)
	return nil
}

func (s *ChangedPackages) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.SequenceNumber, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
