package pm

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIShortcutChangeCallback = "android.content.pm.IShortcutChangeCallback"

const (
	TransactionIShortcutChangeCallbackOnShortcutsAddedOrUpdated = binder.FirstCallTransaction + 0
	TransactionIShortcutChangeCallbackOnShortcutsRemoved        = binder.FirstCallTransaction + 1
)

const (
	MethodIShortcutChangeCallbackOnShortcutsAddedOrUpdated = "onShortcutsAddedOrUpdated"
	MethodIShortcutChangeCallbackOnShortcutsRemoved        = "onShortcutsRemoved"
)

type IShortcutChangeCallback interface {
	AsBinder() binder.IBinder
	OnShortcutsAddedOrUpdated(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
	OnShortcutsRemoved(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
}

type ShortcutChangeCallbackProxy struct {
	Remote binder.IBinder
}

func NewShortcutChangeCallbackProxy(
	remote binder.IBinder,
) *ShortcutChangeCallbackProxy {
	return &ShortcutChangeCallbackProxy{Remote: remote}
}

func (p *ShortcutChangeCallbackProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IShortcutChangeCallback = (*ShortcutChangeCallbackProxy)(nil)

func (p *ShortcutChangeCallbackProxy) OnShortcutsAddedOrUpdated(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIShortcutChangeCallback)
	_data.WriteString16(packageName)
	if shortcuts == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(shortcuts)))
		for _, _item := range shortcuts {
			_data.WriteInt32(1)
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIShortcutChangeCallback, MethodIShortcutChangeCallbackOnShortcutsAddedOrUpdated)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIShortcutChangeCallback, MethodIShortcutChangeCallbackOnShortcutsAddedOrUpdated, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ShortcutChangeCallbackProxy) OnShortcutsRemoved(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIShortcutChangeCallback)
	_data.WriteString16(packageName)
	if shortcuts == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(shortcuts)))
		for _, _item := range shortcuts {
			_data.WriteInt32(1)
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIShortcutChangeCallback, MethodIShortcutChangeCallbackOnShortcutsRemoved)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIShortcutChangeCallback, MethodIShortcutChangeCallbackOnShortcutsRemoved, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ShortcutChangeCallbackStub dispatches incoming binder transactions
// to a typed IShortcutChangeCallback implementation.
type ShortcutChangeCallbackStub struct {
	Impl IShortcutChangeCallback
}

var _ binder.TransactionReceiver = (*ShortcutChangeCallbackStub)(nil)

func (s *ShortcutChangeCallbackStub) Descriptor() string {
	return DescriptorIShortcutChangeCallback
}

func (s *ShortcutChangeCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIShortcutChangeCallbackOnShortcutsAddedOrUpdated:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_shortcuts []ShortcutInfo
		_ = _arg_shortcuts
		var _arg_user interface{}
		_err = s.Impl.OnShortcutsAddedOrUpdated(ctx, _arg_packageName, _arg_shortcuts, _arg_user)
		_ = _err
		return nil, nil
	case TransactionIShortcutChangeCallbackOnShortcutsRemoved:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_shortcuts []ShortcutInfo
		_ = _arg_shortcuts
		var _arg_user interface{}
		_err = s.Impl.OnShortcutsRemoved(ctx, _arg_packageName, _arg_shortcuts, _arg_user)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IShortcutChangeCallbackServer is the server-side interface that user implementations
// provide to NewShortcutChangeCallbackStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IShortcutChangeCallbackServer interface {
	OnShortcutsAddedOrUpdated(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
	OnShortcutsRemoved(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
}

type shortcutChangeCallbackStubWrapper struct {
	impl       IShortcutChangeCallbackServer
	stubBinder *binder.StubBinder
}

func (w *shortcutChangeCallbackStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *shortcutChangeCallbackStubWrapper) OnShortcutsAddedOrUpdated(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	return w.impl.OnShortcutsAddedOrUpdated(ctx, packageName, shortcuts, user)
}

func (w *shortcutChangeCallbackStubWrapper) OnShortcutsRemoved(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	return w.impl.OnShortcutsRemoved(ctx, packageName, shortcuts, user)
}

var _ IShortcutChangeCallback = (*shortcutChangeCallbackStubWrapper)(nil)

// NewShortcutChangeCallbackStub creates a server-side IShortcutChangeCallback wrapping the given
// server implementation. The returned value satisfies IShortcutChangeCallback
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewShortcutChangeCallbackStub(
	impl IShortcutChangeCallbackServer,
) IShortcutChangeCallback {
	wrapper := &shortcutChangeCallbackStubWrapper{impl: impl}
	stub := &ShortcutChangeCallbackStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
