package pm

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type LabeledIntent struct {
	SourcePackage string
	LabelRes      int32
	Icon          int32
}

var _ parcel.Parcelable = (*LabeledIntent)(nil)

func (s *LabeledIntent) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null Super
	p.WriteString16(s.SourcePackage)
	p.WriteInt32(s.LabelRes)
	p.WriteInt32(-1) // null TextUtils
	p.WriteInt32(s.Icon)
	return nil
}

func (s *LabeledIntent) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	return nil // opaque Super: cannot skip without known wire format
	s.SourcePackage, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.LabelRes, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil // opaque TextUtils: cannot skip without known wire format
	s.Icon, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
