package mbms

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIDownloadProgressListener = "android.telephony.mbms.IDownloadProgressListener"

const (
	TransactionIDownloadProgressListenerOnProgressUpdated = binder.FirstCallTransaction + 0
)

type IDownloadProgressListener interface {
	AsBinder() binder.IBinder
	OnProgressUpdated(ctx context.Context, request DownloadRequest, fileInfo FileInfo, currentDownloadSize int32, fullDownloadSize int32, currentDecodedSize int32, fullDecodedSize int32) error
}

type DownloadProgressListenerProxy struct {
	remote binder.IBinder
}

func NewDownloadProgressListenerProxy(
	remote binder.IBinder,
) *DownloadProgressListenerProxy {
	return &DownloadProgressListenerProxy{remote: remote}
}

func (p *DownloadProgressListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IDownloadProgressListener = (*DownloadProgressListenerProxy)(nil)

func (p *DownloadProgressListenerProxy) OnProgressUpdated(
	ctx context.Context,
	request DownloadRequest,
	fileInfo FileInfo,
	currentDownloadSize int32,
	fullDownloadSize int32,
	currentDecodedSize int32,
	fullDecodedSize int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIDownloadProgressListener)
	_data.WriteInt32(1)
	if _err := request.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := fileInfo.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(currentDownloadSize)
	_data.WriteInt32(fullDownloadSize)
	_data.WriteInt32(currentDecodedSize)
	_data.WriteInt32(fullDecodedSize)

	_code, _err := p.remote.ResolveCode(DescriptorIDownloadProgressListener, "onProgressUpdated")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// DownloadProgressListenerStub dispatches incoming binder transactions
// to a typed IDownloadProgressListener implementation.
type DownloadProgressListenerStub struct {
	Impl IDownloadProgressListener
}

var _ binder.TransactionReceiver = (*DownloadProgressListenerStub)(nil)

func (s *DownloadProgressListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIDownloadProgressListenerOnProgressUpdated:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_request DownloadRequest
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_request.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_fileInfo FileInfo
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_fileInfo.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_currentDownloadSize, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_fullDownloadSize, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_currentDecodedSize, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_fullDecodedSize, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnProgressUpdated(ctx, _arg_request, _arg_fileInfo, _arg_currentDownloadSize, _arg_fullDownloadSize, _arg_currentDecodedSize, _arg_fullDecodedSize)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
