package supplicant

// Code generated by aidlgen. DO NOT EDIT.

type Hs20AnqpSubtypes int32

const (
	Hs20AnqpSubtypesOperatorFriendlyName Hs20AnqpSubtypes = 3
	Hs20AnqpSubtypesWanMetrics           Hs20AnqpSubtypes = 4
	Hs20AnqpSubtypesConnectionCapability Hs20AnqpSubtypes = 5
	Hs20AnqpSubtypesOsuProvidersList     Hs20AnqpSubtypes = 8
)
