package vcn

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type VcnUnderlyingNetworkPolicy struct {
}

var _ parcel.Parcelable = (*VcnUnderlyingNetworkPolicy)(nil)

func (s *VcnUnderlyingNetworkPolicy) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null VcnNetworkPolicyResult
	return nil
}

func (s *VcnUnderlyingNetworkPolicy) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
