package effect

import (
	"fmt"
	effectPresetReverb "github.com/xaionaro-go/binder/android/hardware/audio/effect/PresetReverb"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const (
	PresetReverbTagVendor           int32 = 0
	PresetReverbTagSupportedPresets int32 = 1
	PresetReverbTagPreset           int32 = 2
)

type PresetReverb struct {
	Tag              int32
	Vendor           VendorExtension
	SupportedPresets []effectPresetReverb.Presets
	Preset           effectPresetReverb.Presets
}

var _ parcel.Parcelable = (*PresetReverb)(nil)

func (u *PresetReverb) GetVendor() (VendorExtension, bool) {
	if u.Tag != PresetReverbTagVendor {
		var _zero VendorExtension
		return _zero, false
	}
	return u.Vendor, true
}

func (u *PresetReverb) SetVendor(
	v VendorExtension,
) {
	u.Tag = PresetReverbTagVendor
	u.Vendor = v
}

func (u *PresetReverb) GetSupportedPresets() ([]effectPresetReverb.Presets, bool) {
	if u.Tag != PresetReverbTagSupportedPresets {
		var _zero []effectPresetReverb.Presets
		return _zero, false
	}
	return u.SupportedPresets, true
}

func (u *PresetReverb) SetSupportedPresets(
	v []effectPresetReverb.Presets,
) {
	u.Tag = PresetReverbTagSupportedPresets
	u.SupportedPresets = v
}

func (u *PresetReverb) GetPreset() (effectPresetReverb.Presets, bool) {
	if u.Tag != PresetReverbTagPreset {
		var _zero effectPresetReverb.Presets
		return _zero, false
	}
	return u.Preset, true
}

func (u *PresetReverb) SetPreset(
	v effectPresetReverb.Presets,
) {
	u.Tag = PresetReverbTagPreset
	u.Preset = v
}

func (u *PresetReverb) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(u.Tag)

	switch u.Tag {
	case PresetReverbTagVendor:
		if _err := u.Vendor.MarshalParcel(p); _err != nil {
			return _err
		}
	case PresetReverbTagSupportedPresets:
		if u.SupportedPresets == nil {
			p.WriteInt32(-1)
		} else {
			p.WriteInt32(int32(len(u.SupportedPresets)))
			for _, _item := range u.SupportedPresets {
				p.WriteInt32(int32(_item))
			}
		}
	case PresetReverbTagPreset:
		p.WriteInt32(int32(u.Preset))
	default:
		return fmt.Errorf("unknown union tag %d for PresetReverb", u.Tag)
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (u *PresetReverb) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	u.Tag, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	switch u.Tag {
	case PresetReverbTagVendor:
		if _err = u.Vendor.UnmarshalParcel(p); _err != nil {
			return _err
		}
	case PresetReverbTagSupportedPresets:

		var _count0 int32
		_count0, _err = p.ReadInt32()
		if _err != nil {
			return _err
		}
		if _count0 >= 0 {
			u.SupportedPresets = make([]effectPresetReverb.Presets, _count0)
			for _i := int32(0); _i < _count0; _i++ {
				_raw, _err := p.ReadInt32()
				if _err != nil {
					return _err
				}
				u.SupportedPresets[_i] = effectPresetReverb.Presets(_raw)
			}
		}
	case PresetReverbTagPreset:
		_raw, _err := p.ReadInt32()
		if _err != nil {
			return _err
		}
		u.Preset = effectPresetReverb.Presets(_raw)
	default:
		return fmt.Errorf("unknown union tag %d for PresetReverb", u.Tag)
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
