package webkit

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type WebViewProviderResponse struct {
	Status int32
}

var _ parcel.Parcelable = (*WebViewProviderResponse)(nil)

func (s *WebViewProviderResponse) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null PackageInfo
	p.WriteInt32(s.Status)
	return nil
}

func (s *WebViewProviderResponse) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.Status, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
