package contentcapture

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type DataRemovalRequest struct {
	PackageName   string
	ForEverything bool
}

var _ parcel.Parcelable = (*DataRemovalRequest)(nil)

func (s *DataRemovalRequest) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString16(s.PackageName)
	p.WriteBool(s.ForEverything)
	p.WriteInt32(-1) // null Size
	return nil
}

func (s *DataRemovalRequest) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.ForEverything, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
