package c2

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type FieldSupportedValuesQueryResult struct {
	Status Status
	Values FieldSupportedValues
}

var _ parcel.Parcelable = (*FieldSupportedValuesQueryResult)(nil)

func (s *FieldSupportedValuesQueryResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(1) // non-null indicator
	if _err := s.Status.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteInt32(1) // non-null indicator
	if _err := s.Values.MarshalParcel(p); _err != nil {
		return _err
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *FieldSupportedValuesQueryResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.Status.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.Values.UnmarshalParcel(p); _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
