package c2

import (
	common "github.com/AndroidGoLab/binder/android/hardware/graphics/common"
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type IGraphicBufferAllocatorAllocation struct {
	Buffer common.HardwareBuffer
	Fence  int32
}

var _ parcel.Parcelable = (*IGraphicBufferAllocatorAllocation)(nil)

func (s *IGraphicBufferAllocatorAllocation) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(1) // non-null indicator
	if _err := s.Buffer.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteParcelFileDescriptor(s.Fence)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *IGraphicBufferAllocatorAllocation) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _, _err = p.ReadInt32(); _err != nil { // non-null indicator
		return _err
	}
	if _err = s.Buffer.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Fence, _err = p.ReadParcelFileDescriptor()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
