package policy

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIShortcutService = "com.android.internal.policy.IShortcutService"

const (
	TransactionIShortcutServiceNotifyShortcutKeyPressed = binder.FirstCallTransaction + 0
)

type IShortcutService interface {
	AsBinder() binder.IBinder
	NotifyShortcutKeyPressed(ctx context.Context, shortcutCode int64) error
}

type ShortcutServiceProxy struct {
	remote binder.IBinder
}

func NewShortcutServiceProxy(
	remote binder.IBinder,
) *ShortcutServiceProxy {
	return &ShortcutServiceProxy{remote: remote}
}

func (p *ShortcutServiceProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IShortcutService = (*ShortcutServiceProxy)(nil)

func (p *ShortcutServiceProxy) NotifyShortcutKeyPressed(
	ctx context.Context,
	shortcutCode int64,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIShortcutService)
	_data.WriteInt64(shortcutCode)

	_code, _err := p.remote.ResolveCode(DescriptorIShortcutService, "notifyShortcutKeyPressed")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ShortcutServiceStub dispatches incoming binder transactions
// to a typed IShortcutService implementation.
type ShortcutServiceStub struct {
	Impl IShortcutService
}

var _ binder.TransactionReceiver = (*ShortcutServiceStub)(nil)

func (s *ShortcutServiceStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIShortcutServiceNotifyShortcutKeyPressed:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_shortcutCode, _err := _data.ReadInt64()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.NotifyShortcutKeyPressed(ctx, _arg_shortcutCode)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
