package telephony

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorICarrierPrivilegesCallback = "com.android.internal.telephony.ICarrierPrivilegesCallback"

const (
	TransactionICarrierPrivilegesCallbackOnCarrierPrivilegesChanged = binder.FirstCallTransaction + 0
	TransactionICarrierPrivilegesCallbackOnCarrierServiceChanged    = binder.FirstCallTransaction + 1
)

type ICarrierPrivilegesCallback interface {
	AsBinder() binder.IBinder
	OnCarrierPrivilegesChanged(ctx context.Context, privilegedPackageNames []string, privilegedUids []int32) error
	OnCarrierServiceChanged(ctx context.Context, carrierServicePackageName string, carrierServiceUid int32) error
}

type CarrierPrivilegesCallbackProxy struct {
	remote binder.IBinder
}

func NewCarrierPrivilegesCallbackProxy(
	remote binder.IBinder,
) *CarrierPrivilegesCallbackProxy {
	return &CarrierPrivilegesCallbackProxy{remote: remote}
}

func (p *CarrierPrivilegesCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ICarrierPrivilegesCallback = (*CarrierPrivilegesCallbackProxy)(nil)

func (p *CarrierPrivilegesCallbackProxy) OnCarrierPrivilegesChanged(
	ctx context.Context,
	privilegedPackageNames []string,
	privilegedUids []int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICarrierPrivilegesCallback)
	if privilegedPackageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(privilegedPackageNames)))
		for _, _item := range privilegedPackageNames {
			_data.WriteString16(_item)
		}
	}
	if privilegedUids == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(privilegedUids)))
		for _, _item := range privilegedUids {
			_data.WriteInt32(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorICarrierPrivilegesCallback, "onCarrierPrivilegesChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *CarrierPrivilegesCallbackProxy) OnCarrierServiceChanged(
	ctx context.Context,
	carrierServicePackageName string,
	carrierServiceUid int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorICarrierPrivilegesCallback)
	_data.WriteString16(carrierServicePackageName)
	_data.WriteInt32(carrierServiceUid)

	_code, _err := p.remote.ResolveCode(DescriptorICarrierPrivilegesCallback, "onCarrierServiceChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// CarrierPrivilegesCallbackStub dispatches incoming binder transactions
// to a typed ICarrierPrivilegesCallback implementation.
type CarrierPrivilegesCallbackStub struct {
	Impl ICarrierPrivilegesCallback
}

var _ binder.TransactionReceiver = (*CarrierPrivilegesCallbackStub)(nil)

func (s *CarrierPrivilegesCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionICarrierPrivilegesCallbackOnCarrierPrivilegesChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_privilegedPackageNames []string
		_ = _arg_privilegedPackageNames
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_privilegedUids []int32
		_ = _arg_privilegedUids
		_err := s.Impl.OnCarrierPrivilegesChanged(ctx, _arg_privilegedPackageNames, _arg_privilegedUids)
		_ = _err
		return nil, nil
	case TransactionICarrierPrivilegesCallbackOnCarrierServiceChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_carrierServicePackageName, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_carrierServiceUid, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnCarrierServiceChanged(ctx, _arg_carrierServicePackageName, _arg_carrierServiceUid)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
