package media

// Code generated by aidlgen. DO NOT EDIT.

type RtpError int32

const (
	RtpErrorNONE            RtpError = 0
	RtpErrorInvalidParam    RtpError = 1
	RtpErrorNotReady        RtpError = 2
	RtpErrorNoMemory        RtpError = 3
	RtpErrorNoResources     RtpError = 4
	RtpErrorPortUnavailable RtpError = 5
	RtpErrorNotSupported    RtpError = 6
)
