// Code generated by genparcelgo. DO NOT EDIT.

package credentials

import (
	"github.com/xaionaro-go/binder/parcel"
)

type RemoteEntry struct {
	// Slice: opaque type — not yet supported
}

var _ parcel.Parcelable = (*RemoteEntry)(nil)

func (s *RemoteEntry) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *RemoteEntry) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
