// Code generated by genparcelgo. DO NOT EDIT.

package games

import (
	"github.com/xaionaro-go/binder/parcel"
)

type GameSessionActivityResult struct {
	ResultCode int32
	// Data: opaque type — not yet supported
}

var _ parcel.Parcelable = (*GameSessionActivityResult)(nil)

func (s *GameSessionActivityResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.ResultCode)
	return nil
}

func (s *GameSessionActivityResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.ResultCode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
