package ad

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITvAdSessionCallback = "android.media.tv.ad.ITvAdSessionCallback"

const (
	TransactionITvAdSessionCallbackOnSessionCreated            = binder.FirstCallTransaction + 0
	TransactionITvAdSessionCallbackOnLayoutSurface             = binder.FirstCallTransaction + 1
	TransactionITvAdSessionCallbackOnRequestCurrentVideoBounds = binder.FirstCallTransaction + 2
	TransactionITvAdSessionCallbackOnRequestCurrentChannelUri  = binder.FirstCallTransaction + 3
	TransactionITvAdSessionCallbackOnRequestTrackInfoList      = binder.FirstCallTransaction + 4
	TransactionITvAdSessionCallbackOnRequestCurrentTvInputId   = binder.FirstCallTransaction + 5
	TransactionITvAdSessionCallbackOnRequestSigning            = binder.FirstCallTransaction + 6
	TransactionITvAdSessionCallbackOnTvAdSessionData           = binder.FirstCallTransaction + 7
)

type ITvAdSessionCallback interface {
	AsBinder() binder.IBinder
	OnSessionCreated(ctx context.Context, session ITvAdSession) error
	OnLayoutSurface(ctx context.Context, left int32, top int32, right int32, bottom int32) error
	OnRequestCurrentVideoBounds(ctx context.Context) error
	OnRequestCurrentChannelUri(ctx context.Context) error
	OnRequestTrackInfoList(ctx context.Context) error
	OnRequestCurrentTvInputId(ctx context.Context) error
	OnRequestSigning(ctx context.Context, id string, algorithm string, alias string, data []byte) error
	OnTvAdSessionData(ctx context.Context, type_ string, data os.Bundle) error
}

type TvAdSessionCallbackProxy struct {
	remote binder.IBinder
}

func NewTvAdSessionCallbackProxy(
	remote binder.IBinder,
) *TvAdSessionCallbackProxy {
	return &TvAdSessionCallbackProxy{remote: remote}
}

func (p *TvAdSessionCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITvAdSessionCallback = (*TvAdSessionCallbackProxy)(nil)

func (p *TvAdSessionCallbackProxy) OnSessionCreated(
	ctx context.Context,
	session ITvAdSession,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)
	_data.WriteStrongBinder(session.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onSessionCreated")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnLayoutSurface(
	ctx context.Context,
	left int32,
	top int32,
	right int32,
	bottom int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)
	_data.WriteInt32(left)
	_data.WriteInt32(top)
	_data.WriteInt32(right)
	_data.WriteInt32(bottom)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onLayoutSurface")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnRequestCurrentVideoBounds(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onRequestCurrentVideoBounds")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnRequestCurrentChannelUri(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onRequestCurrentChannelUri")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnRequestTrackInfoList(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onRequestTrackInfoList")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnRequestCurrentTvInputId(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onRequestCurrentTvInputId")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnRequestSigning(
	ctx context.Context,
	id string,
	algorithm string,
	alias string,
	data []byte,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)
	_data.WriteString16(id)
	_data.WriteString16(algorithm)
	_data.WriteString16(alias)
	if data == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(data)))
		for _, _item := range data {
			_data.WritePaddedByte(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onRequestSigning")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdSessionCallbackProxy) OnTvAdSessionData(
	ctx context.Context,
	type_ string,
	data os.Bundle,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdSessionCallback)
	_data.WriteString16(type_)
	_data.WriteInt32(1)
	if _err := data.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorITvAdSessionCallback, "onTvAdSessionData")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// TvAdSessionCallbackStub dispatches incoming binder transactions
// to a typed ITvAdSessionCallback implementation.
type TvAdSessionCallbackStub struct {
	Impl ITvAdSessionCallback
}

var _ binder.TransactionReceiver = (*TvAdSessionCallbackStub)(nil)

func (s *TvAdSessionCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionITvAdSessionCallbackOnSessionCreated:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_session ITvAdSession
		_ = _arg_session
		_err := s.Impl.OnSessionCreated(ctx, _arg_session)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnLayoutSurface:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_left, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_top, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_right, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_bottom, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnLayoutSurface(ctx, _arg_left, _arg_top, _arg_right, _arg_bottom)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnRequestCurrentVideoBounds:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnRequestCurrentVideoBounds(ctx)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnRequestCurrentChannelUri:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnRequestCurrentChannelUri(ctx)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnRequestTrackInfoList:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnRequestTrackInfoList(ctx)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnRequestCurrentTvInputId:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnRequestCurrentTvInputId(ctx)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnRequestSigning:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_id, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_algorithm, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_alias, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_data []byte
		_ = _arg_data
		_err = s.Impl.OnRequestSigning(ctx, _arg_id, _arg_algorithm, _arg_alias, _arg_data)
		_ = _err
		return nil, nil
	case TransactionITvAdSessionCallbackOnTvAdSessionData:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_type_, _err := data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_data os.Bundle
		{
			_nullInd, _err := data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_data.UnmarshalParcel(data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.OnTvAdSessionData(ctx, _arg_type_, _arg_data)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
