package print

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PrinterId struct {
	LocalId string
}

var _ parcel.Parcelable = (*PrinterId)(nil)

func (s *PrinterId) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null ServiceName
	p.WriteString16(s.LocalId)
	return nil
}

func (s *PrinterId) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.LocalId, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	return nil
}
