package light

// Code generated by aidlgen. DO NOT EDIT.

type BrightnessMode int32

const (
	BrightnessModeUSER           BrightnessMode = 0
	BrightnessModeSENSOR         BrightnessMode = 1
	BrightnessModeLowPersistence BrightnessMode = 2
)
