package textclassifier

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SelectionEvent struct {
	AbsoluteStart              int32
	AbsoluteEnd                int32
	EventType                  int32
	EntityType                 string
	PackageName                string
	WidgetType                 string
	InvocationMethod           int32
	ResultId                   string
	EventTime                  int64
	DurationSinceSessionStart  int64
	DurationSincePreviousEvent int64
	EventIndex                 int32
	Start                      int32
	End                        int32
	SmartStart                 int32
	SmartEnd                   int32
}

var _ parcel.Parcelable = (*SelectionEvent)(nil)

func (s *SelectionEvent) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.AbsoluteStart)
	p.WriteInt32(s.AbsoluteEnd)
	p.WriteInt32(s.EventType)
	p.WriteString16(s.EntityType)
	p.WriteString16(s.PackageName)
	p.WriteString16(s.WidgetType)
	p.WriteInt32(s.InvocationMethod)
	p.WriteString16(s.ResultId)
	p.WriteInt64(s.EventTime)
	p.WriteInt64(s.DurationSinceSessionStart)
	p.WriteInt64(s.DurationSincePreviousEvent)
	p.WriteInt32(s.EventIndex)
	p.WriteInt32(s.Start)
	p.WriteInt32(s.End)
	p.WriteInt32(s.SmartStart)
	p.WriteInt32(s.SmartEnd)
	return nil
}

func (s *SelectionEvent) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.AbsoluteStart, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.AbsoluteEnd, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.EventType, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.EntityType, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.WidgetType, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.InvocationMethod, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.ResultId, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.EventTime, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.DurationSinceSessionStart, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.DurationSincePreviousEvent, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.EventIndex, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.Start, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.End, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.SmartStart, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.SmartEnd, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
