package tv

import (
	"context"
	content "github.com/xaionaro-go/aidl/android/content"
	hdmi "github.com/xaionaro-go/aidl/android/hardware/hdmi"
	view "github.com/xaionaro-go/aidl/android/view"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITvInputService = "android.media.tv.ITvInputService"

const (
	TransactionITvInputServiceRegisterCallback                    = binder.FirstCallTransaction + 0
	TransactionITvInputServiceUnregisterCallback                  = binder.FirstCallTransaction + 1
	TransactionITvInputServiceCreateSession                       = binder.FirstCallTransaction + 2
	TransactionITvInputServiceCreateRecordingSession              = binder.FirstCallTransaction + 3
	TransactionITvInputServiceGetAvailableExtensionInterfaceNames = binder.FirstCallTransaction + 4
	TransactionITvInputServiceGetExtensionInterface               = binder.FirstCallTransaction + 5
	TransactionITvInputServiceGetExtensionInterfacePermission     = binder.FirstCallTransaction + 6
	TransactionITvInputServiceNotifyHardwareAdded                 = binder.FirstCallTransaction + 7
	TransactionITvInputServiceNotifyHardwareRemoved               = binder.FirstCallTransaction + 8
	TransactionITvInputServiceNotifyHdmiDeviceAdded               = binder.FirstCallTransaction + 9
	TransactionITvInputServiceNotifyHdmiDeviceRemoved             = binder.FirstCallTransaction + 10
	TransactionITvInputServiceNotifyHdmiDeviceUpdated             = binder.FirstCallTransaction + 11
)

type ITvInputService interface {
	AsBinder() binder.IBinder
	RegisterCallback(ctx context.Context, callback ITvInputServiceCallback) error
	UnregisterCallback(ctx context.Context, callback ITvInputServiceCallback) error
	CreateSession(ctx context.Context, channel view.InputChannel, callback ITvInputSessionCallback, inputId string, sessionId string, tvAppAttributionSource content.AttributionSource) error
	CreateRecordingSession(ctx context.Context, callback ITvInputSessionCallback, inputId string, sessionId string) error
	GetAvailableExtensionInterfaceNames(ctx context.Context) ([]string, error)
	GetExtensionInterface(ctx context.Context, name string) (binder.IBinder, error)
	GetExtensionInterfacePermission(ctx context.Context, name string) (string, error)
	NotifyHardwareAdded(ctx context.Context, hardwareInfo TvInputHardwareInfo) error
	NotifyHardwareRemoved(ctx context.Context, hardwareInfo TvInputHardwareInfo) error
	NotifyHdmiDeviceAdded(ctx context.Context, deviceInfo hdmi.HdmiDeviceInfo) error
	NotifyHdmiDeviceRemoved(ctx context.Context, deviceInfo hdmi.HdmiDeviceInfo) error
	NotifyHdmiDeviceUpdated(ctx context.Context, deviceInfo hdmi.HdmiDeviceInfo) error
}

type TvInputServiceProxy struct {
	remote binder.IBinder
}

func NewTvInputServiceProxy(
	remote binder.IBinder,
) *TvInputServiceProxy {
	return &TvInputServiceProxy{remote: remote}
}

func (p *TvInputServiceProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITvInputService = (*TvInputServiceProxy)(nil)

func (p *TvInputServiceProxy) RegisterCallback(
	ctx context.Context,
	callback ITvInputServiceCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "registerCallback"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) UnregisterCallback(
	ctx context.Context,
	callback ITvInputServiceCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "unregisterCallback"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) CreateSession(
	ctx context.Context,
	channel view.InputChannel,
	callback ITvInputSessionCallback,
	inputId string,
	sessionId string,
	tvAppAttributionSource content.AttributionSource,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := channel.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteStrongBinder(callback.AsBinder().Handle())
	_data.WriteString16(inputId)
	_data.WriteString16(sessionId)
	if _err := tvAppAttributionSource.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "createSession"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) CreateRecordingSession(
	ctx context.Context,
	callback ITvInputSessionCallback,
	inputId string,
	sessionId string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	_data.WriteStrongBinder(callback.AsBinder().Handle())
	_data.WriteString16(inputId)
	_data.WriteString16(sessionId)

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "createRecordingSession"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) GetAvailableExtensionInterfaceNames(
	ctx context.Context,
) ([]string, error) {
	var _result []string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)

	_reply, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "getAvailableExtensionInterfaceNames"), 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]string, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadString16()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *TvInputServiceProxy) GetExtensionInterface(
	ctx context.Context,
	name string,
) (binder.IBinder, error) {
	var _result binder.IBinder
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	_data.WriteString16(name)

	_reply, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "getExtensionInterface"), 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = binder.NewProxyBinder(p.remote.Transport(), _handle)
	return _result, nil
}

func (p *TvInputServiceProxy) GetExtensionInterfacePermission(
	ctx context.Context,
	name string,
) (string, error) {
	var _result string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	_data.WriteString16(name)

	_reply, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "getExtensionInterfacePermission"), 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadString16()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *TvInputServiceProxy) NotifyHardwareAdded(
	ctx context.Context,
	hardwareInfo TvInputHardwareInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := hardwareInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "notifyHardwareAdded"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) NotifyHardwareRemoved(
	ctx context.Context,
	hardwareInfo TvInputHardwareInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := hardwareInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "notifyHardwareRemoved"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) NotifyHdmiDeviceAdded(
	ctx context.Context,
	deviceInfo hdmi.HdmiDeviceInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := deviceInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "notifyHdmiDeviceAdded"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) NotifyHdmiDeviceRemoved(
	ctx context.Context,
	deviceInfo hdmi.HdmiDeviceInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := deviceInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "notifyHdmiDeviceRemoved"), binder.FlagOneway, _data)
	return _err
}

func (p *TvInputServiceProxy) NotifyHdmiDeviceUpdated(
	ctx context.Context,
	deviceInfo hdmi.HdmiDeviceInfo,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvInputService)
	if _err := deviceInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_, _err := p.remote.Transact(ctx, p.remote.ResolveCode(DescriptorITvInputService, "notifyHdmiDeviceUpdated"), binder.FlagOneway, _data)
	return _err
}
