// Code generated by genparcelgo. DO NOT EDIT.

package tv

import (
	"github.com/xaionaro-go/binder/parcel"
)

type TvContentRatingSystemInfo struct {
	// XmlUri: opaque type — not yet supported
	// ApplicationInfo: opaque type — not yet supported
}

var _ parcel.Parcelable = (*TvContentRatingSystemInfo)(nil)

func (s *TvContentRatingSystemInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *TvContentRatingSystemInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}
