// Code generated by genparcelgo. DO NOT EDIT.

package input

import (
	"github.com/xaionaro-go/binder/parcel"
)

type VirtualTouchDeviceConfig struct {
	Width  int32
	Height int32
	// Dest: opaque type — not yet supported
}

var _ parcel.Parcelable = (*VirtualTouchDeviceConfig)(nil)

func (s *VirtualTouchDeviceConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Width)
	p.WriteInt32(s.Height)
	return nil
}

func (s *VirtualTouchDeviceConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Width, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Height, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
