package textservice

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorISpellCheckerService = "com.android.internal.textservice.ISpellCheckerService"

const (
	TransactionISpellCheckerServiceGetISpellCheckerSession = binder.FirstCallTransaction + 0
)

type ISpellCheckerService interface {
	AsBinder() binder.IBinder
	GetISpellCheckerSession(ctx context.Context, locale string, listener ISpellCheckerSessionListener, bundle os.Bundle, supportedAttributes int32, callback ISpellCheckerServiceCallback) error
}

type SpellCheckerServiceProxy struct {
	remote binder.IBinder
}

func NewSpellCheckerServiceProxy(
	remote binder.IBinder,
) *SpellCheckerServiceProxy {
	return &SpellCheckerServiceProxy{remote: remote}
}

func (p *SpellCheckerServiceProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ISpellCheckerService = (*SpellCheckerServiceProxy)(nil)

func (p *SpellCheckerServiceProxy) GetISpellCheckerSession(
	ctx context.Context,
	locale string,
	listener ISpellCheckerSessionListener,
	bundle os.Bundle,
	supportedAttributes int32,
	callback ISpellCheckerServiceCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorISpellCheckerService)
	_data.WriteString16(locale)
	_data.WriteStrongBinder(listener.AsBinder().Handle())
	_data.WriteInt32(1)
	if _err := bundle.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(supportedAttributes)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorISpellCheckerService, "getISpellCheckerSession")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// SpellCheckerServiceStub dispatches incoming binder transactions
// to a typed ISpellCheckerService implementation.
type SpellCheckerServiceStub struct {
	Impl ISpellCheckerService
}

var _ binder.TransactionReceiver = (*SpellCheckerServiceStub)(nil)

func (s *SpellCheckerServiceStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionISpellCheckerServiceGetISpellCheckerSession:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_locale, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_listener ISpellCheckerSessionListener
		_ = _arg_listener
		var _arg_bundle os.Bundle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_bundle.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_supportedAttributes, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback ISpellCheckerServiceCallback
		_ = _arg_callback
		_err = s.Impl.GetISpellCheckerSession(ctx, _arg_locale, _arg_listener, _arg_bundle, _arg_supportedAttributes, _arg_callback)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
