// Code generated by spec2go. DO NOT EDIT.

package app

import (
	"context"
	"fmt"

	"github.com/xaionaro-go/binder/servicemanager"
)

// GetSystemHealthService retrieves the SystemHealthService service and returns a typed proxy.
func GetSystemHealthService(
	ctx context.Context,
	sm *servicemanager.ServiceManager,
) (*BatteryStatsProxy, error) {
	svc, err := sm.GetService(ctx, servicemanager.SystemHealthService)
	if err != nil {
		return nil, fmt.Errorf("GetSystemHealthService: %w", err)
	}
	return NewBatteryStatsProxy(svc), nil
}
