package occupant_awareness

// Code generated by aidlgen. DO NOT EDIT.

type ConfidenceLevel byte

const (
	ConfidenceLevelNONE ConfidenceLevel = 0
	ConfidenceLevelLOW  ConfidenceLevel = 1
	ConfidenceLevelHIGH ConfidenceLevel = 2
	ConfidenceLevelMAX  ConfidenceLevel = 3
)
