package visibility_control

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIGnssVisibilityControl = "android.hardware.gnss.visibility_control.IGnssVisibilityControl"

const (
	TransactionIGnssVisibilityControlEnableNfwLocationAccess = binder.FirstCallTransaction + 0
	TransactionIGnssVisibilityControlSetCallback             = binder.FirstCallTransaction + 1
)

type IGnssVisibilityControl interface {
	AsBinder() binder.IBinder
	EnableNfwLocationAccess(ctx context.Context, proxyApps []string) error
	SetCallback(ctx context.Context, callback IGnssVisibilityControlCallback) error
}

type GnssVisibilityControlProxy struct {
	remote binder.IBinder
}

func NewGnssVisibilityControlProxy(
	remote binder.IBinder,
) *GnssVisibilityControlProxy {
	return &GnssVisibilityControlProxy{remote: remote}
}

func (p *GnssVisibilityControlProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IGnssVisibilityControl = (*GnssVisibilityControlProxy)(nil)

func (p *GnssVisibilityControlProxy) EnableNfwLocationAccess(
	ctx context.Context,
	proxyApps []string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIGnssVisibilityControl)
	if proxyApps == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(proxyApps)))
		for _, _item := range proxyApps {
			_data.WriteString(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIGnssVisibilityControl, "enableNfwLocationAccess")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *GnssVisibilityControlProxy) SetCallback(
	ctx context.Context,
	callback IGnssVisibilityControlCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIGnssVisibilityControl)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIGnssVisibilityControl, "setCallback")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// GnssVisibilityControlStub dispatches incoming binder transactions
// to a typed IGnssVisibilityControl implementation.
type GnssVisibilityControlStub struct {
	Impl IGnssVisibilityControl
}

var _ binder.TransactionReceiver = (*GnssVisibilityControlStub)(nil)

func (s *GnssVisibilityControlStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIGnssVisibilityControlEnableNfwLocationAccess:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_proxyApps []string
		_ = _arg_proxyApps
		_err := s.Impl.EnableNfwLocationAccess(ctx, _arg_proxyApps)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIGnssVisibilityControlSetCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IGnssVisibilityControlCallback
		_ = _arg_callback
		_err := s.Impl.SetCallback(ctx, _arg_callback)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
