package session

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorISession2TokensListener = "android.media.session.ISession2TokensListener"

const (
	TransactionISession2TokensListenerOnSession2TokensChanged = binder.FirstCallTransaction + 0
)

type ISession2TokensListener interface {
	AsBinder() binder.IBinder
	OnSession2TokensChanged(ctx context.Context, tokens []interface{}) error
}

type Session2TokensListenerProxy struct {
	remote binder.IBinder
}

func NewSession2TokensListenerProxy(
	remote binder.IBinder,
) *Session2TokensListenerProxy {
	return &Session2TokensListenerProxy{remote: remote}
}

func (p *Session2TokensListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ISession2TokensListener = (*Session2TokensListenerProxy)(nil)

func (p *Session2TokensListenerProxy) OnSession2TokensChanged(
	ctx context.Context,
	tokens []interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorISession2TokensListener)
	if tokens == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(tokens)))
	}

	_, _err := p.remote.Transact(ctx, TransactionISession2TokensListenerOnSession2TokensChanged, binder.FlagOneway, _data)
	return _err
}
