package job

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type JobSnapshot struct {
	SatisfiedConstraints int32
	IsRunnable           bool
	Job                  JobInfo
}

var _ parcel.Parcelable = (*JobSnapshot)(nil)

func (s *JobSnapshot) MarshalParcel(
	p *parcel.Parcel,
) error {
	if _err := s.Job.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteInt32(s.SatisfiedConstraints)
	p.WriteBool(s.IsRunnable)
	return nil
}

func (s *JobSnapshot) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	if _err := s.Job.UnmarshalParcel(p); _err != nil {
		return _err
	}
	s.SatisfiedConstraints, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.IsRunnable, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	return nil
}
